### ISSUE TITLE
Jdk for termux

### ISSUE THREAD

**Issue by bvcbvc** [termux/termux-app#1986] opened 2021-03-31 14:29 UTC
Me and probably others would like a jdk for this, if it's not possible due to certain issues, let me know in comments

**Comment by bvcbvc** [comment] 2021-03-31 14:31
As for a recommendation, latest stable version

**Comment by Grimler91** [comment] 2021-03-31 14:35
Duplicate of https://github.com/termux/termux-packages/issues/324

**Closed by Grimler91** 2021-03-31 14:35 UTC
