### ISSUE TITLE
Gem Segmentation Fault

### ISSUE THREAD

**Issue by jepunband** [termux/termux-app#1044] opened 2019-02-25 15:53 UTC
**Problem description**
fresh install termux and pkg install ruby. Error output 'segmentation fault' when i did 'gem -h'.

**Steps to reproduce**
install termux, install ruby. Type gem -h.

**Expected behavior**
should display correct info.

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

Welcome to Termux!
$ ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [arm-linux-androideabi]
$ gem -h
Segmentation fault
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.113-Deathly-1.0 #1 SMP PREEMPT Fri Feb 8 20:15:41 CST 2019 armv7l Android
Termux-packages arch:
arm
Android version:
7.1.2
Device manufacturer:
unknown
Device model:
SM-T705
$ termux-info

**Comment by xeffyr** [comment] 2019-02-25 16:17
Duplicate of https://github.com/termux/termux-packages/issues/3380.

**Closed by xeffyr** 2019-02-25 16:17 UTC
