### ISSUE TITLE
[Feature]: Don’t terminate Session when Device turn off

### ISSUE THREAD

**Issue by solct** [termux/termux-app#3963] opened 2024-05-24 21:08 UTC
### Feature description

Please update don’t terminate session when device turn off

### Additional information

Like Stopwatch on Android, when I turn off my device the app session always stay and running back

**Comment by agnostic-apollo** [comment] 2024-05-25 08:17
Duplicate of #3709

**Closed by agnostic-apollo** 2024-05-25 08:17 UTC
