### ISSUE TITLE
[Bug]: After update, php gd missing

### ISSUE THREAD

**Issue by freebrowser1** [termux/termux-app#4128] opened 2024-08-28 08:12 UTC
### Problem description

`pkg update && pkg upgrade `
installed php 8.3.10 over 8.3.8
```
sv stop httpd
sv start httpd
```
gd missing
```
pkg install php-gd
```
which installed gdf successfully.
```
sv stop httpd
sv start httpd
```
but still no gd active.
In PHP 8.3.8 gd was still active.

### Steps to reproduce the behavior.

see above

### What is the expected behavior?

That php-gd works when it is installed.

### System information

* Termux application version: 118.1
* Android OS version: 14
* Device model: Nothing 2a

**Comment by fornwall** [comment] 2024-08-28 08:37
Duplicate of https://github.com/termux/termux-packages/issues/21262 - follow that issue for progress!

**Closed by fornwall** 2024-08-28 08:37 UTC
Labels: bug report
