### ISSUE TITLE
[Bug]: `fg` doesn't work when using `fish` shell

### ISSUE THREAD

**Issue by anzhi0708** [termux/termux-app#3302] opened 2023-03-17 11:37 UTC
## Summary

Seems like `fish` automatically send the job back to background **AGAIN** on Termux.

```
u0_a202@localhost:~►nvim                                    20:28
fish: Job 1, 'nvim' has stopped
u0_a202@localhost:~►fg                               6.552s 20:29
Send job 1 (nvim) to foreground
fish: Job 1, 'nvim' has stopped
u0_a202@localhost:~►jobs                                    20:29
Job	Group	CPU	State	Command
1	18783	0%	stopped	nvim
u0_a202@localhost:~►fg 1                                    20:29
fg: No suitable job: 1
u0_a202@localhost:~[2]►ps -ef | rg nvim                     20:29
u0_a202  18783 18735  0  1970 pts/25   00:00:00 nvim
u0_a202  18818 18735  1  1970 pts/25   00:00:00 rg nvim
u0_a202@localhost:~►fg 18783                                20:29
Send job 1 (nvim) to foreground
fish: Job 1, 'nvim' has stopped
u0_a202@localhost:~►
```

## Steps to Reproduce

- Open `nvim` and enter anything under insert mode
- `Ctrl-Z` to suspend the process
- Type `fg` to see the bug

## Expected Behavior

I tried the **same** thing on macOS, the suspended `nvim` process was brought back to foreground successfully. 

## System information

* Termux application version: TERMUX_VERSION=0.118.0
* Android OS version: 11
* Device model: Redmi 21091116AC (rooted)

**Comment by 2096779623** [comment] 2023-03-17 12:19
Duplicate of https://github.com/termux/termux-packages/issues/15677 .

**Closed by 2096779623** 2023-03-17 12:19 UTC
Labels: bug report
