### ISSUE TITLE
Weechat causes system reboot

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-app#129] opened 2016-08-05 06:51 UTC
Hi, 
I am running [sopel ](https://github.com/sopel-irc/sopel) on termux, But whenever I try to quit sopel with CTRL+C there is a 1 in 5 chance that android will reboot. I am using a Sony Xperia X.

**Comment by fornwall** [comment] 2016-08-05 09:50
A non-system Android app does not even have the permission to reboot, so this must AFAIK be a bug in the system (perhaps kernel/system panic forcing a reboot)?

Would be interesting to see if people on more devices can reproduce the problem (if so, write down your device name!), and see if it's device/manufacturer specific or not!

**Comment by Neo-Oli** [comment] 2016-08-05 10:03
Yeah, I figured it must be something like that. I hope all these weird problems I've been having with my new phone get resolved in a system upgrade.

**Comment by Neo-Oli** [comment] 2016-10-10 06:22
I now have a better test case for this. `/quit`-ing weechat, with the weechat-python-plugin enabled will cause a system reboot. This only started happening as of Version 1.6 of weechat. 

Here's the last few lines of the logcat

```
10-10 08:07:07.756 10149 10149 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10232 <<<<<<
10-10 08:07:07.759 10149 10149 D AndroidRuntime: CheckJNI is OFF
10-10 08:07:07.761 10149 10149 W art     : Failed to find oatdata symbol at expected address: oatdata=0x7f814af000 != expected=0x71a40000, /data/dalvik-cache/arm64/system@framework@boot.oat. See process maps in the log.
10-10 08:07:07.782 10149 10149 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
10-10 08:07:07.814 10149 10149 I Radio-JNI: register_android_hardware_Radio DONE
10-10 08:07:07.832 10149 10149 D AndroidRuntime: Calling main entry com.android.commands.am.Am
10-10 08:07:07.847 10149 10149 D AndroidRuntime: Shutting down VM
10-10 08:07:08.076 10189 10189 W weechat : type=1400 audit(0.0:1485): avc: denied { create } for name="weechat_fifo_10189" scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:fuse:s0:c512,c768 tclass=fifo_file permissive=0 ppid=10009 pcomm="zsh" pgid=10009 pgcomm="zsh"
```

This is happening with just `weechat-python-plugin`. No scripts are actually loaded (`weechat --no-script`. The problem doesn't happen with `weechat --no-plugin`.

**Comment by Neo-Oli** [comment] 2016-12-22 09:12
Unfortunately this problem still exists on Android 7. But I've only ever observed it with sopel and weechat-python-plugin. And I use a lot of other python software.

**Comment by fornwall** [comment] 2016-12-22 19:30
Interesting! I found [an old bug report for python on Android](https://github.com/BeATz-UnKNoWN/python-for-android/issues/86) where python could cause a system reboot, could be related (the underlying thing in python and Android maybe remains the same).

**Comment by Neo-Oli** [comment] 2016-12-23 10:59
The steps in that bug report don't cause the problem with me. I ran a strace on weechat and caused the reboot. Here are the last few lines: 
```
recvfrom(12, ":discordia.ch 324 glow_ #lugs +n"..., 4096, 0, NULL, NULL) = 81
rt_sigaction(SIGTSTP, {SIG_IGN, [], SA_RESTART}, {0x7f8703787c, [], SA_RESTART}, 8) = 0
pselect6(1, [0], NULL, NULL, {0, 0}, NULL) = 0 (Timeout)
pselect6(1, [0], NULL, NULL, {0, 0}, NULL) = 0 (Timeout)
write(1, "\r\33[38A\33[37m11:50:18\33[97m        "..., 137) = 137
rt_sigaction(SIGTSTP, {0x7f8703787c, [], SA_RESTART}, NULL, 8) = 0
fcntl(0, F_GETFD)                       = 0
fcntl(10, F_GETFD)                      = 0
fcntl(12, F_GETFD)                      = 0
ppoll([{fd=0, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}], 3, {0, 4000000}, NULL, 0) = 0 (Timeout)
fcntl(0, F_GETFD)                       = 0
fcntl(10, F_GETFD)                      = 0
fcntl(12, F_GETFD)                      = 0
ppoll([{fd=0, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}], 3, {0, 939000000}, NULL, 0) = 0 (Timeout)
fcntl(0, F_GETFD)                       = 0
fcntl(10, F_GETFD)                      = 0
fcntl(12, F_GETFD)                      = 0
ppoll([{fd=0, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}], 3, {0, 1000000}, NULL, 0) = 0 (Timeout)
fcntl(0, F_GETFD)                       = 0
fcntl(10, F_GETFD)                      = 0
fcntl(12, F_GETFD)                      = 0
ppoll([{fd=0, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}], 3, {0, 55000000}, NULL, 0) = 0 (Timeout)
fcntl(0, F_GETFD)                       = 0
fcntl(10, F_GETFD)                      = 0
fcntl(12, F_GETFD)                      = 0
ppoll([{fd=0, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}], 3, {0, 1000000}, NULL, 0) = 0 (Timeout)
fcntl(0, F_GETFD)                       = 0
fcntl(10, F_GETFD)                      = 0
fcntl(12, F_GETFD)                      = 0
ppoll([{fd=0, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}], 3, {0, 939000000}, NULL, 0) = 1 ([{fd=12, revents=POLLIN}], left {0, 583478646})
recvfrom(12, ":logger!logger@localhost NOTICE "..., 4096, 0, NULL, NULL) = 167
rt_sigaction(SIGTSTP, {SIG_IGN, [], SA_RESTART}, {0x7f8703787c, [], SA_RESTART}, 8) = 0
pselect6(1, [0], NULL, NULL, {0, 0}, NULL) = 0 (Timeout)
pselect6(1, [0], NULL, NULL, {0, 0}, NULL) = 0 (Timeout)
rt_sigaction(SIGTSTP, {0x7f8703787c, [], SA_RESTART}, NULL, 8) = 0
rt_sigaction(SIGTSTP, {SIG_IGN, [], SA_RESTART}, {0x7f8703787c, [], SA_RESTART}, 8) = 0
pselect6(1, [0], NULL, NULL, {0, 0}, NULL) = 0 (Timeout)
pselect6(1, [0], NULL, NULL, {0, 0}, NULL) = 0 (Timeout)
rt_sigaction(SIGTSTP, {0x7f8703787c, [], SA_RESTART}, NULL, 8) = 0
fcntl(0, F_GETFD)                       = 0
fcntl(10, F_GETFD)                      = 0
fcntl(12, F_GETFD)                      = 0
ppoll([{fd=0, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}], 3, {0, 571000000}, NULL,
0^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@



```

**Comment by Neo-Oli** [comment] 2017-01-20 09:49
Just checking in. This still happens with Python 3.6.0

**Comment by tomty89** [comment] 2017-03-08 20:28
Experiencing similar issue here with emacs. It's not triggered by a key combination or quitting here tho, but merely rolling the screen can. Also Xperia X here.

**Comment by tomty89** [comment] 2017-03-10 09:34
Today I experienced the same thing on another phone (from a minor vendor in China). I was using ERC and sending a `/quit`.

**Comment by fornwall** [comment] 2017-03-10 10:44
Would be really interesting to find what causes this.

**Comment by Neo-Oli** [comment] 2017-03-10 10:59
I can reproduce this fairly consistently. Is there anything I can do that would give you insight as to what the problem is?

**Comment by tomty89** [comment] 2017-03-10 13:53
I wonder if it's a termux issue though. I mean, if a force reboot can be triggered like this, it's probably some bug in the kernel or the libc used in our Android?

**Comment by fornwall** [comment] 2017-03-10 14:25
@tomty89 Right, this is (probably) a kernel or Android framework bug (possibly due to vendor modifications), as an app shouldn't be able to cause an instant reboot.

It would still be interesting to know what causes this exactly and perhaps work around it, if possible.

**Comment by Neo-Oli** [comment] 2017-04-17 11:21
With the current version of weechat this also happens without weechat-python-plugin.

**Comment by Neo-Oli** [comment] 2017-07-10 11:41
Just checking in: The problem still happens in Android 7.1.1.

**Comment by Neo-Oli** [comment] 2017-08-11 14:37
This is still an issue for me. It happens with weechat without any weechat-*-plugin. It happens every time. 
I've made another interessting observation. 
When I SIGKILL weechat it doesn't reboot. but it will instantly reboot if I then start weechat again (tested multiple times).

**Comment by sdrausty** [comment] 2017-10-03 11:50
The weechat plugins were purged after initial reboots. 🚧🎼

**Comment by Neo-Oli** [comment] 2017-10-03 11:51
@sdrausty For me it happens with weechat without any plugins now.

**Comment by sdrausty** [comment] 2017-10-03 11:54
That's exactly what I was getting.

**Comment by sdrausty** [comment] 2017-12-16 15:07
This weechat behavior, "logging into freenode, then rebooting the Android OS after /nick change," is identical with https://sdrausty.github.io/TermuxArch/ on device.  :O

**Comment by Neo-Oli** [comment] 2018-02-09 10:31
Switched to LineageOS 14.1 (from Stock Sony Rom) and it is still happening.

**Comment by Neo-Oli** [comment] 2018-02-12 15:05
Here's a dmesg thing that occurs at the time of the crash:
```
<6>[  145.281957] psci: CPU1 killed.
<6>[  146.190349] psci: CPU1 killed.
<6>[  147.064996] nf_conntrack: automatic helper assignment is deprecated and it will be removed soon. Use the iptables CT target to attach helpers instead.
<6>[  147.098712] psci: CPU1 killed.
<6>[  148.530454] psci: CPU1 killed.
<4>[  149.189945] QSEECOM: qseecom_load_app: App (tzsuntory) does'nt exist, loading apps for first time
<4>[  149.203975] QSEECOM: qseecom_load_app: App with id 2752515 (tzsuntory) now loaded
<4>[  149.228842] QSEECOM: qseecom_unload_app: App id 2752515 now unloaded
<6>[  149.700329] psci: CPU1 killed.
<4>[  150.996550] migrate_irqs: 1170 callbacks suppressed
<4>[  150.996574] IRQ32 no longer affine to CPU1
<4>[  150.996587] IRQ33 no longer affine to CPU1
<4>[  150.996599] IRQ34 no longer affine to CPU1
<4>[  150.996612] IRQ36 no longer affine to CPU1
<4>[  150.996624] IRQ37 no longer affine to CPU1
<4>[  150.996635] IRQ38 no longer affine to CPU1
<4>[  150.996648] IRQ40 no longer affine to CPU1
<4>[  150.996659] IRQ41 no longer affine to CPU1
<4>[  150.996671] IRQ42 no longer affine to CPU1
<4>[  150.996682] IRQ43 no longer affine to CPU1
<6>[  150.999031] psci: CPU1 killed.
<6>[  152.042037] psci: CPU2 killed.
<6>[  152.820609] psci: CPU1 killed.
<1>[  153.154621] Unable to handle kernel paging request at virtual address 154fb65e9ef1b08
<1>[  153.154639] pgd = ffffffc09794e000
<1>[  153.154645] [154fb65e9ef1b08] *pgd=0000000000000000
<0>[  153.154658] Internal error: Oops: 96000004 [#1] PREEMPT SMP
<6>[  153.154670] CPU: 1 PID: 5369 Comm: weechat Tainted: G        W    3.10.84-LineageOS-g3be0891 #1
<6>[  153.154678] task: ffffffc0a038b100 ti: ffffffc09783c000 task.ti: ffffffc09783c000
<6>[  153.154692] PC is at kfree+0xb4/0x1ec
<6>[  153.154702] LR is at help+0x36c/0x818
<6>[  153.154708] pc : [<ffffffc000171f1c>] lr : [<ffffffc000a56eac>] pstate: 20000145
<6>[  153.154713] sp : ffffffc09783f750
<6>[  153.154719] x29: ffffffc09783f750 x28: ffffffc0010efdc5
<6>[  153.154729] x27: ffffffc0a8bac11f x26: 0000000000000014
<6>[  153.154739] x25: ffffffc0a8bac0f0 x24: ffffffc0a8bac110
<6>[  153.154749] x23: ffffffc00159c000 x22: ffffffc000a56eac
<6>[  153.154759] x21: 616c79706d757266 x20: ffffffc0a8bac125
<6>[  153.154769] x19: 0154fb65e9ef1b08 x18: 0000000000000000
<6>[  153.154779] x17: 0000007fa538de1c x16: ffffffc0009fd88c
<6>[  153.154789] x15: 0000007fa53c8908 x14: 0000000000000000
<6>[  153.154798] x13: 0000000000000000 x12: 0000000000000000
<6>[  153.154808] x11: 000000000000003a x10: 000000000000000b
<6>[  153.154818] x9 : 00ffffffffffffff x8 : 00000000a9b43cd5
<6>[  153.154827] x7 : 00000000936412ac x6 : 00000000174a8481
<6>[  153.154837] x5 : ffffffc0a4441180 x4 : ffffffc0a7416b98
<6>[  153.154847] x3 : ffffffc08fa1e9d8 x2 : ffffffc0a4441198
<6>[  153.154856] x1 : ffffffbc00000000 x0 : 0154fba9e9ef1b08
<6>[  153.154866]
<0>[  153.154872] Process weechat (pid: 5369, stack limit = 0xffffffc09783c058)
<6>[  153.154878] Call trace:
<6>[  153.154888] [<ffffffc000171f1c>] kfree+0xb4/0x1ec
<6>[  153.154895] [<ffffffc000a56ea8>] help+0x368/0x818
<6>[  153.154906] [<ffffffc000aba91c>] ipv4_helper+0x80/0x8c
<6>[  153.154916] [<ffffffc000a3e618>] nf_iterate+0x7c/0xb8
<6>[  153.154925] [<ffffffc000a3e6d8>] nf_hook_slow+0x84/0x12c
<6>[  153.154935] [<ffffffc000a7b7ac>] ip_output+0xb8/0xd0
<6>[  153.154943] [<ffffffc000a7a4c8>] ip_local_out+0x2c/0x3c
<6>[  153.154951] [<ffffffc000a7a96c>] ip_queue_xmit+0x2cc/0x350
<6>[  153.154960] [<ffffffc000a8f4c0>] tcp_transmit_skb+0x774/0x7b4
<6>[  153.154968] [<ffffffc000a8fdc8>] tcp_write_xmit+0x8c8/0x9d0
<6>[  153.154976] [<ffffffc000a90120>] __tcp_push_pending_frames+0x30/0xbc
<6>[  153.154985] [<ffffffc000a83484>] tcp_sendmsg+0xa48/0xc38
<6>[  153.154994] [<ffffffc000aa5c24>] inet_sendmsg+0x84/0xb8
<6>[  153.155004] [<ffffffc0009fc5e4>] sock_sendmsg+0x8c/0xb0
<6>[  153.155012] [<ffffffc0009fd9fc>] SyS_sendto+0x170/0x1bc
```

**Comment by Neo-Oli** [comment] 2018-02-12 15:06
By the way, I just had a very similar crash occurring with irssi. I find it very suspicious that all 3 programs that can crash my phone are IRC clients (sopel, weechat, irssi).

**Comment by Neo-Oli** [comment] 2018-02-12 15:34
Alright I can also cause my phone to reboot if I use telnet to connect to an irc server and then quitting telnet again. It must be something in the IRC protocol. Maybe something the server sends me?_

**Comment by Auxilus** [comment] 2018-02-12 15:44
You can use packet Capture to see what traffic is coming without root

**Comment by Neo-Oli** [comment] 2018-02-12 15:59
@Auxilus I just tried that. I used proxychains to route the traffic through a proxy to capture the packets, but when the traffic goes through an SSH tunnel it doesn't seem to cause a reboot. It must be something very low level in the system. Probably in some network driver (since these would be the same in both LineageOS and stock Rom. I'll try again later, when I am in a network where I can more easily capture my packets.

**Comment by Neo-Oli** [comment] 2018-02-12 17:05
@Auxilus Curiously I can not reproduce the telnet reboot under testing conditions. I will try again some other time. When letting weechat reboot the phone I don't see any traffic at the time of reboot (when issuing /quit). So it does look like it crashes even before sending the QUIT commands. Weird.

**Comment by sw2wolf** [comment] 2018-02-20 12:42
On a huawei phone(Android 6.0), it will irregularly reboot while running ERC in emacs.

**Comment by xeffyr** [comment] 2020-10-02 11:23
Closing as this rather a kernel (specifically netfilter framework) bug.

**Closed by xeffyr** 2020-10-02 11:23 UTC
Labels: bug report, help wanted
