### ISSUE TITLE
Push commands from a different application to Termux command line

### ISSUE THREAD

**Issue by imprakharshukla** [termux/termux-app#1106] opened 2019-04-19 13:04 UTC
**Problem description**
I am designing an app that requires the users to copy some commands and run it on Termux. I really wanted to automate this process but I didn't found any documentation for the same.

I wanted to know if that is possible.
**Expected scenario**
My user clicks a button and it sends the command to Termux terminal and it executes.

**Comment by xeffyr** [comment] 2019-04-19 13:10
Implemented in PR https://github.com/termux/termux-app/pull/1029. Not merged because incomplete (feedback: https://github.com/termux/termux-app/pull/1029#issuecomment-466814059).

Duplicate of https://github.com/termux/termux-app/issues/804.

**Closed by xeffyr** 2019-04-19 13:10 UTC
