### ISSUE TITLE
Python script not executing rather showing code of script on python cgi webserver using http.server

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-app#1601] opened 2020-06-15 10:52 UTC
**Problem description**

While using python cgi webserver when tried to execute script over localhost on browser, script doesn't get executed rather it just displays the script content.

**Steps to reproduce**
Created a python script with following content
```
#!/data/data/com.termux/files/usr/bin/python3
import cgi
import cgitb; cgitb.enable()  # for troubleshooting
print ("Content-type: text/html")
print('<html>')
print(' <head>')
print(' <title>test</title>')
print(' </head>')
print(' <body>')
print(' <h2>teeeeeeeeeest</h2>')
print(' </body>')
print(' </html>')
```
```
chmod a+x+r test.py
```
When executed
```
python3 -m http.server --cgi 8000
curl -i http://localhost:8000/cgi-bin/test.py
HTTP/1.0 200 Script output follows
Server: SimpleHTTP/0.6 Python/3.8.3
Date: Sat, 16 May 2020 10:06:21 GMT
#!/data/data/com.termux/files/usr/bin/python3
import cgi
import cgitb; cgitb.enable()  # for troubleshooting
print ("Content-type: text/html")
print('<html>')
print(' <head>')
print(' <title>test</title>')
print(' </head>')
print(' <body>')
print('<h2>teeeeeeeeeest</h2>')
print(' </body>')
print(' </html>')
```
**Expected behavior**

Expected result in terminal:
```
Content-type: text/html
<html>
 <head>
 <title>test</title>
 </head>
 <body>
 <h2>teeeeeeeeeest</h2>
 </body>
 </html>
```

Expected result on browser
teeeeeeeeeest

The script should execute and so print in script will display the text within parenthesis and that when viewed in browser appears to be executed

But it wasn't executing rather showing the content of file.

**Additional information**

* Termux application version:0.95
* Android OS version:10
* Device model:SMA750F

**Comment by Grimler91** [comment] 2020-06-15 12:07
According to https://stackoverflow.com/questions/44934615/having-problems-outputting-proper-cgi-python-script you need to print the http header with /r/n instead of /n, try changing your script as in the top answer to that question

**Comment by tathastu871** [comment] 2020-06-15 15:55
Already tried but didn't work

**Comment by tathastu871** [comment] 2020-06-16 08:31
Tried all options given in official docs and on solutions from stack community. But nothing worked. It was occuring on termux only because same when used from my laptop it worked properly on both wimdows and linux

**Comment by Grimler91** [comment] 2020-06-16 10:38
Your example works for me so I cannot reproduce the problem

**Comment by tathastu871** [comment] 2020-06-16 15:27
> Your example works for me so I cannot reproduce the problem

Can you post screenshot of output in browser when python http server was started on termux. And whether you used apache server or python's cgi server.

Please answer

**Comment by xeffyr** [comment] 2020-06-16 15:44
CGI works with curl but web browser page is blank.

***

Write script and launch http server with cgi:
![Screenshot_20200616-184036_Termux](https://user-images.githubusercontent.com/25881154/84796330-2c206d80-b001-11ea-9cdc-bbabdba8132b.jpg)
\- no issues.

Run `curl` in another session:
![Screenshot_20200616-184049_Termux](https://user-images.githubusercontent.com/25881154/84796406-42c6c480-b001-11ea-94a2-1af9c36af001.jpg)
\- no issues.

Open Google Chrome:
![Screenshot_20200616-184123_Chrome](https://user-images.githubusercontent.com/25881154/84796468-54a86780-b001-11ea-83b8-7bfd143de318.jpg)
\- page is blank as @tathastu871 had.

**Comment by xeffyr** [comment] 2020-06-16 15:50
Changing code to this fixes the issue:
```
#!/data/data/com.termux/files/usr/bin/python3
import cgi
import cgitb; cgitb.enable()  # for troubleshooting
print ("Content-type: text/html\n")
print('<html>')
print(' <head>')
print(' <title>test</title>')
print(' </head>')
print(' <body>')
print(' <h2>teeeeeeeeeest</h2>')
print(' </body>')
print(' </html>')
```

There must be a newline after `Content-type: text/html`.

Closing issue because it is user error and not Termux bug.

**Closed by xeffyr** 2020-06-16 15:50 UTC

**Comment by tathastu871** [comment] 2020-06-16 16:24
Did not work on my phone
![Screenshot_20200616-215257_Termux](https://user-images.githubusercontent.com/65007212/84800746-db6a3e00-b01b-11ea-8cf3-878d882c2a36.jpg)
![Screenshot_20200616-215304_Termux](https://user-images.githubusercontent.com/65007212/84800753-dd340180-b01b-11ea-8aaf-131d8d9e112a.jpg)
![Screenshot_20200616-215314_Chrome Dev](https://user-images.githubusercontent.com/65007212/84800755-de652e80-b01b-11ea-8622-f80367e7b9b0.jpg)

**Comment by xeffyr** [comment] 2020-06-16 16:34
@tathastu871 Script must be in cgi-bin directory !!! Not somewhere else.

**Comment by xeffyr** [comment] 2020-06-16 16:36
Here is a Python CGI documentation: https://docs.python.org/3/library/cgi.html.

**Comment by xeffyr** [comment] 2020-06-16 16:38
On first screenshot at https://github.com/termux/termux-app/issues/1601#issuecomment-644869692 you are running wrong command:
```
curl localhost:8000/test.py
```

Should be:
```
curl localhost:8000/cgi-bin/test.py
```

***

Check what you are typing before posting bugs.
