### ISSUE TITLE
Error termux

### ISSUE THREAD

**Issue by brayanduran** [termux/termux-app#625] opened 2018-03-15 13:28 UTC
hi, I would like you to help me decrypt a .dll file I was tried and I get the following error
first I leave captures of my operating system

Android version
http://img.fenixzone.net/i/u1cI09U.png

Root Only
http://img.fenixzone.net/i/VrZMA9v.png

Termux SuperSu
http://img.fenixzone.net/i/2OMfvKn.png

permission of SuperSu termux
http://img.fenixzone.net/i/j0Cde6o.png

when I enter a termux and write apt update I get an error
http://img.fenixzone.net/i/mi6vlxc.png

I have another doubt, when I write the code SU should not put me first "@root"
http://img.fenixzone.net/i/H6lrxQW.png

**Comment by Neo-Oli** [comment] 2018-03-15 13:58
Duplicate of #384

**Closed by Neo-Oli** 2018-03-15 13:58 UTC
