### ISSUE TITLE
I can't do any apt or pkg operations

### ISSUE THREAD

**Issue by BokuNoCode** [termux/termux-app#1150] opened 2019-06-01 17:58 UTC
I can't do any pkg or apt operations, but ping and wget still work.
![Screenshot_2019-06-02-00-51-08](https://user-images.githubusercontent.com/35252089/58752005-95564100-84d1-11e9-815e-bf4ae06b230c.png)

**Comment by BokuNoCode** [comment] 2019-06-01 17:59
Android 5

Asus zenfone 2 laser

**Comment by xeffyr** [comment] 2019-06-01 20:00
Duplicate of https://github.com/termux/termux-packages/issues/3872.
***
For now considered as device/rom bug.

**Closed by xeffyr** 2019-06-01 20:00 UTC
