### ISSUE TITLE
Keys not showing [Bug]: 

### ISSUE THREAD

**Issue by kaiminz** [termux/termux-app#3349] opened 2023-04-18 00:01 UTC
### Problem description

5 keys do not showing
![screenshot_20230418_073942](https://user-images.githubusercontent.com/89754237/232635626-1a4448dc-34f4-4af2-a128-87c039f369bc.jpg)

### Steps to reproduce the behavior.

5 keys do not showing 
![Uploading screenshot_20230418_073942.jpg…]()

### What is the expected behavior?

Showing keys properly 

### System information

* Termux application version: the latest 
* Android OS version:  android 9
* Device model: OnePlus 6

**Comment by Paguiar735** [comment] 2023-04-18 03:21
Do they show up when you switch to landscape mode?

**Comment by agnostic-apollo** [comment] 2023-04-18 03:25
Possible duplicate of #2095

**Closed by agnostic-apollo** 2023-04-18 03:25 UTC
Labels: bug report
