### ISSUE TITLE
termux-file-editor running after sharing link (supposed to run termux-url-opener?)

### ISSUE THREAD

**Issue by l0ophole** [termux/termux-app#1339] opened 2019-11-08 05:42 UTC
termux-file-editor is running after I share a link to termux in chrome. my script is in  termux-url-opener and everything I've read says that that is the file that runs when a link is shared to termux but that's not working for me.)

It's weird because if I click share from the hamburger menu it works, but if I long press on a link and share it then it brings up this dialog box asking me to save the file. I have to long click and share to get to the right URL, because the URL that is shared from the hamburger menu isn't one that I can use.
 
```
$ termux-info
Updatable packages:
qemu-user-i386/unstable 1:3.1.0-1 aarch64 [upgradable from: 1:3.1.0]
qemu-user-x86_64/unstable 1:3.1.0-1 aarch64 [upgradable from: 1:3.1.0]
Subscribed repositories:
https://dl.bintray.com/xeffyr/unstable-packages unstable/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://termux.org/packages stable/main
System information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Thu Sep 12 18:32:44 WIB 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
Mi A2
$
```
```
$ pwd
/data/data/com.termux/files/home/bin
$ ls -lh                                               
total 20K
lrwxrwxrwx 1 u0_a155 u0_a155  46 Sep 19 04:57 sshpass -> /data/data/com.termux/files/usr/bin/sshpass
-rwxr-xr-x 1 u0_a155 u0_a155 470 Nov  7 23:09 termux-file-editor
-rwxr-xr-x 1 u0_a155 u0_a155 342 Nov  7 23:05 termux-url-opener
```
![Screenshot_20191107-234633](https://user-images.githubusercontent.com/19521547/68452700-ee30b080-01b8-11ea-8991-39ec1e35be3d.png)

**Comment by AbdullahM0hamed** [comment] 2019-12-04 21:39
I've been unable to replicate this problem, any particular link that this issue occurs with (that you don't mind providing)?

**Comment by l0ophole** [comment] 2019-12-05 14:02
@AbdullahM0hamed it does it for any magnet link

**Comment by AbdullahM0hamed** [comment] 2019-12-05 21:23
I see.

I believe the problem is: https://github.com/termux/termux-app/blob/b61da23be761a874ccd610835946f0b9b352b22f/app/src/main/java/com/termux/filepicker/TermuxFileReceiverActivity.java#L53


I think that: `Patterns.WEB_URL.matcher(sharedText).matches()` isn't matching magnet links. 

Likely, a new regex will have to be used, or an or in the if statement.

**Comment by l0ophole** [comment] 2019-12-06 01:00
@AbdullahM0hamed I see. I'm assuming Pattern.WEB_URL.matcher is a function in the android.util.Patterns library. I guess Android wasn't written to recognize magnet links as Web URLs.
```
public static final Pattern WEB_URL = Pattern.compile(
--
  | "((?:(http\|https\|Http\|Https\|rtsp\|Rtsp):\\/\\/(?:(?:[a-zA-Z0-9\\$\\-\\_\\.\\+\\!\\*\\'\\(\\)"
  | + "\\,\\;\\?\\&\\=]\|(?:\\%[a-fA-F0-9]{2})){1,64}(?:\\:(?:[a-zA-Z0-9\\$\\-\\_"
  | + "\\.\\+\\!\\*\\'\\(\\)\\,\\;\\?\\&\\=]\|(?:\\%[a-fA-F0-9]{2})){1,25})?\\@)?)?"
  | + "((?:(?:[" + GOOD_IRI_CHAR + "][" + GOOD_IRI_CHAR + "\\-]{0,64}\\.)+"   // named host
  | + TOP_LEVEL_DOMAIN_STR_FOR_WEB_URL
  | + "\|(?:(?:25[0-5]\|2[0-4]" // or ip address
  | + "[0-9]\|[0-1][0-9]{2}\|[1-9][0-9]\|[1-9])\\.(?:25[0-5]\|2[0-4][0-9]"
  | + "\|[0-1][0-9]{2}\|[1-9][0-9]\|[1-9]\|0)\\.(?:25[0-5]\|2[0-4][0-9]\|[0-1]"
  | + "[0-9]{2}\|[1-9][0-9]\|[1-9]\|0)\\.(?:25[0-5]\|2[0-4][0-9]\|[0-1][0-9]{2}"
  | + "\|[1-9][0-9]\|[0-9])))"
  | + "(?:\\:\\d{1,5})?)" // plus option port number
  | + "(\\/(?:(?:[a-zA-Z0-9\\;\\/\\?\\:\\@\\&\\=\\#\\~"  // plus option query params
  | + "\\-\\.\\+\\!\\*\\'\\(\\)\\,\\_])\|(?:\\%[a-fA-F0-9]{2}))*)?"
  | + "(?:\\b\|$)");
```

**Comment by AbdullahM0hamed** [comment] 2019-12-07 14:20
@l0ophole That works.

Alternatively, this `if (Patterns.WEB_URL.matcher(sharedText).matches() || Patterns.WEB_URL.matches("magnet:\\?xt=urn:btih:.*?", sharedText))` 

as it doesn't match invalid magnets such as "magnet:" etc. 

Now all that's left is to make a PR, but I won't since I get far too many errors when trying to compile termux (I use Aide, and it gives me 768 errors).

**Comment by l0ophole** [comment] 2019-12-07 14:29
@AbdullahM0hamed nice. I got what I was trying to accomplish to work a different way, so I'm not too worried about it now. Is that how I would suggest a code modification? Checkout the repo, edit the file, create a diff and then attach that to a pull request?

**Comment by AbdullahM0hamed** [comment] 2019-12-07 14:37
@l0ophole I've done it before, but from what I understand, you create your own branch, edit the code, and then make a pull request from your branch.

**Comment by fornwall** [comment] 2020-01-05 00:03
Thanks a lot! This change will be part of version 0.86 of the Termux app, to be released within a day.

**Closed** 2020-01-05 00:02 UTC

**Comment by kr-cr** [comment] 2021-05-13 11:21
Hi, I am facing the same issue with gemini:// url, is there a specific reason to even check if the input is a 'correct' url? I would be ok with Termux just putting the plain text it gets as argument of my script. (and It would prevent adding as many exception as protocol not recognised by android)

Thank you.
