### ISSUE TITLE
How to make termux support the Arabic language? 

### ISSUE THREAD

**Issue by alprofmahmoud** [termux/termux-app#3799] opened 2024-01-24 18:46 UTC
### Problem description

Support arabic 

### Steps to reproduce the behavior.

I tried to install bidi not found in repositories.

### What is the expected behavior?

Display world arabic right to left

### System information

* Termux application version:
* Android OS [version:]
* Device model:
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=19712
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
apt/stable 2.7.10 aarch64 [upgradable from: 2.7.7]
command-not-found/stable 2.4.0-8 aarch64 [upgradable from: 2.4.0-7]
ffmpeg/stable 6.1.1-1 aarch64 [upgradable from: 6.1-2]
fzf/stable 0.46.0 aarch64 [upgradable from: 0.45.0]
glib-bin/stable 2.78.4 aarch64 [upgradable from: 2.78.3-1]
glib/stable 2.78.4 aarch64 [upgradable from: 2.78.3-1]
gst-plugins-good/stable 1.22.8-1 aarch64 [upgradable from: 1.22.8]
libnghttp2/stable 1.59.0 aarch64 [upgradable from: 1.58.0]
libnpth/stable 1.6-2 aarch64 [upgradable from: 1.6-1]
libvpx/stable 1:1.14.0 aarch64 [upgradable from: 1:1.13.1]
mesa/stable 23.3.3-3 aarch64 [upgradable from: 23.3.3-1]
termux-tools version:
1.40.5
Android version:
14
Kernel build information:
Linux localhost 5.10.177-android12-9-27760517 #1 SMP PREEMPT Sun Nov 19 23:20:48 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A245F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.api versionCode:51

**Comment by alprofmahmoud** [comment] 2024-01-24 18:47
![Uploading Screenshot_20240124_203651_Termux.jpg…]()

**Comment by sukronc** [comment] 2024-01-24 23:33
null


Kam, 25 Jan 2024 pukul 01.50 Mahmoud M. Noureldin ***@***.***>
menulis:

**Comment by agnostic-apollo** [comment] 2024-01-25 10:45
Duplicate of #2953

**Closed by agnostic-apollo** 2024-01-25 10:45 UTC
Labels: bug report
