### ISSUE TITLE
trigger reboot when i try use /nick myname in weechat

### ISSUE THREAD

**Issue by jacktsui** [termux/termux-app#490] opened 2017-11-24 08:15 UTC
trigger reboot when i try use "/nick myname" in weechat, i try two times, it happened again.

**Comment by jacktsui** [comment] 2017-11-24 08:23
where can i find some logs about this?
i have try search  both in "/data/data/com.termux/" and "/data/data/com.termux/files/home/.weechat" nothing log about this.

**Comment by Neo-Oli** [comment] 2017-11-24 14:56
Duplicate of https://github.com/termux/termux-app/issues/490#issuecomment-346769130

**Comment by Neo-Oli** [comment] 2017-11-24 14:57
Sorry, Duplcate of https://github.com/termux/termux-app/issues/129

**Closed by Neo-Oli** 2017-11-24 14:57 UTC
Labels: duplicate
