### ISSUE TITLE
Termux 0.114 Bug

### ISSUE THREAD

**Issue by rasty26** [termux/termux-app#2137] opened 2021-06-19 06:46 UTC
I just installed the new release of termux and found that the curser isn't working... Please test the app before making it public (termux 0.114 f droid)

**Comment by agnostic-apollo** [comment] 2021-06-19 17:47
> cursor sometimes disappears

Did you try `Reset` from menu? Reproducible instructions would be great, although crashing ssh could be tried. But if a program like nano (possibly ssh), etc, requests cursor to be disabled, termux shouldn't/can't enable it again automatically, since it can't know that `ssh` crashed without enabling it again, if that's what's happening. Reset should enable it again. You can also test with `tput civis` to hide and `tput cnorm` to make it visible again.

Although, after `tput civis` and `Reset`, blinking doesn't start again until `tput cnorm` is run, needs looking into.

There was a issue in `< v0.114` where cursor blinking wouldn't start again after returning to termux from a different app. So if you initially changed from termux to a different app at the point when cursor was in an off state, then it wouldn't be visible again when you returned. But that was fixed in `v0.114` by e119d34b and didn't affect default configuration.

**Comment by buttaface** [comment] 2021-06-19 21:20
I didn't know what the `Reset` option did, will try it next time.

**Comment by agnostic-apollo** [comment] 2021-06-19 21:31
Technically it calls [this](https://github.com/termux/termux-app/blob/v0.114/terminal-emulator/src/main/java/com/termux/terminal/TerminalEmulator.java#L2367) if that makes some sense, but should reset cursor state due to setting `DECSET_BIT_CURSOR_ENABLED`.

**Comment by freebrowser1** [comment] 2021-06-21 08:19
Are you using the terminal in Termux itself (i.e. on the device itself) or are you using a terminal app on a PC which SSH's into Termux ?

**Comment by agnostic-apollo** [comment] 2021-07-08 16:56
Closing due to inactivity.

**Closed by agnostic-apollo** 2021-07-08 16:56 UTC
