### ISSUE TITLE
[Bug]: Backspace key does not function as expected in Termux with Typewise keyboard

### ISSUE THREAD

**Issue by sukipop** [termux/termux-app#3148] opened 2022-12-18 03:12 UTC
### Problem description

The backspace key does not function as expected in Termux when using the Typewise keyboard (version 4.0.61). When text is entered into the app and the app is subsequently left and reentered, the backspace key is unable to remove the previously entered text. Other keyboards, such as the default keyboard, do not exhibit this behavior.

### Steps to reproduce the behavior.

1. Install Termux version 0.118.0 from F-Droid.
2. Install the Typewise keyboard from the Google Play Store.
3. Open Termux and enter some text.
4. Leave the app and then reenter it.
5. Attempt to remove the text using the backspace key.

### System information

* Termux application version: 0.118.0
* Android OS version: 13
* Device model: Pixel 4a (5G)

**Comment by milanJ** [comment] 2022-12-20 10:27
Hi @sukipop this is likely an issue with the Typewise keyboard and not with the Termux app. I'm one of the developers working on Typewise. We've logged the bug and will check it out.

**Comment by sukipop** [comment] 2022-12-20 13:18
Thank you @milanJ, I wan't sure if that was the case or not because I only have this issue with termux.

**Comment by Haiz14** [comment] 2022-12-23 14:48
Since the issue isn't related to termux, you should close it.

**Closed** 2022-12-23 14:49 UTC
Labels: bug report

**Comment by joneldiablo** [comment] 2023-02-21 07:47
is not the keyboard!
I have the same problem
