### ISSUE TITLE
[Bug]: Unable to install bootstrap packages after reinstalling on a rooted android 10 device

### ISSUE THREAD

**Issue by NukedBart** [termux/termux-app#2264] opened 2021-09-10 12:00 UTC
### Problem description

unable to install the bootstrap packages
termux.net/bootstrap is accessable

### Steps to reproduce the behavior.

uninstalled termux
reinstalled termux apk from fdroid
unable to install the bootstrap packages

### What is the expected behavior?

showing the hello message and run termux

### System information

* Termux application version: 0.117
* Android OS version: 10
* Device model: Redmi Note 8 Pro

**Comment by Grimler91** [comment] 2021-09-10 12:34
What does the error message say? Probably you have termux apps from google play still installed, for example termux-widget.

**Comment by WMCB-Tech** [comment] 2021-09-10 12:51
that is very unclear, latest versions of Termux doesn't use `termux.net` anymore instead it locally installs the bootstrap. maybe you chose the older version of termux or didn't see the version properly. (eg. 0.17 instead of 0.117)

**Comment by xeffyr** [comment] 2021-09-10 14:19
Duplicate of https://github.com/termux/termux-app/issues/2221.

**Comment by NukedBart** [comment] 2021-09-11 00:07
Downloaded the latest version of termux from F-Droid, SELinux is disabled from recovery

**Comment by NukedBart** [comment] 2021-09-11 02:08
found the reason, it was from my last installation.
There was a uuid file marked as immutable, thus termux can't delete that file.
Tried installing terminal emulator and busybox, use chattr -i to remove the attribute, then delete the com.termux folder, reinstall the termux app.
Thanks for the hints on permissions though.
Issue solved, safe to close.

> that is very unclear, latest versions of Termux doesn't use `termux.net/bootstraps` anymore to setup bootstraps by downloading it and termux.net is for legacy versions. instead it locally installs the bootstrap. maybe you chose the older version of termux or didn't see the version properly. (eg. 0.17 instead of 0.117)
> 
> Also if you're rooted, you could have played around with ~fire~ root. in that case you may try restoring correct permissions and selinux contexts using `restorecon`

**Closed** 2021-09-11 02:08 UTC
Labels: bug report
