### ISSUE TITLE
[Feature Request]Disable VolumeUp/VolumeDown

### ISSUE THREAD

**Issue by rubikitch** [termux/termux-app#481] opened 2017-11-17 01:31 UTC
I use info.repy.android.FullKeyboard for keyboard app.
I know VolumeUP+V shows volume control.

I want to disable special handling of VolumeUp/VolumeDown keys (back to default). Because:

1. info.repy.android.FullKeyboard has arrow keys, function keys and many special keys.
2. I have difficulty to handle Volume hard keys in my giant 7-inch phone.
3. Extra key view is very useful
4. I use mpv to play music and want to control volume INSTANTLY

So I want "Disable Volume keys" customize item as a feature request.

**Comment by Neo-Oli** [comment] 2017-11-17 07:02
Duplicate of #119.

**Closed by Neo-Oli** 2017-11-17 07:02 UTC
Labels: duplicate
