### ISSUE TITLE
[feature] calibre arm app for termux pls?

### ISSUE THREAD

**Issue by valtoree** [termux/termux-app#3211] opened 2023-01-25 01:40 UTC
Hi I was wanting to get calibre app ported to termux as it can convert pdf to epub and vice versa via ebook-convert command line app.

It is available as arm app now (see below link) so just need to build it I guess 🤷
https://9to5linux.com/calibre-6-0-released-with-full-text-search-arm64-support-on-linux-qt-6-port

Thanks for reading

**Comment by 2096779623** [comment] 2023-01-25 03:05
Duplicate of https://github.com/termux/termux-packages/issues/6583

**Closed by 2096779623** 2023-01-25 03:05 UTC
