### ISSUE TITLE
Android 4.4 support

### ISSUE THREAD

**Issue by TheComputerGuy96** [termux/termux-app#191] opened 2016-11-13 08:01 UTC
Can someone add Android 4.4 support for this app?

**Comment by kilroythe5th** [comment] 2016-11-16 17:54
great app otherwise, but there is still us 33% that use kitkat

**Comment by fornwall** [comment] 2016-11-16 21:06
Duplicate of https://github.com/termux/termux-app/issues/6.

**Closed by fornwall** 2016-11-16 21:06 UTC
