### ISSUE TITLE
[Feature Request] Ability to use Images as Terminal Background

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/termux-app#1878] opened 2021-01-10 10:47 UTC
**Feature description**
it would be cool if Termux can use pictures as background and the terminal will look aesthetic like anime background in your Terminal or matrix image background

**Reference implementation**

Does another app/terminal emulator have this feature?

Afaik, XFCE Terminal can set pictures as Terminal Background, so yeah it would be cool if termux does that the same

**Comment by GxmerSam** [comment] 2021-01-10 10:55
I agree too, maybe can be added with termux styling

**Comment by xeffyr** [comment] 2021-01-10 11:12
Duplicate of https://github.com/termux/termux-app/issues/365.

**Closed by xeffyr** 2021-01-10 11:12 UTC
