### ISSUE TITLE
Metasploit not running on Termux

### ISSUE THREAD

**Issue by AadiRajUthup** [termux/termux-app#1046] opened 2019-02-27 14:32 UTC
I have the same issue on Termux as this guy issued in this link https://github.com/rapid7/metasploit-framework/issues/11492

Please help us...

**Comment by xeffyr** [comment] 2019-02-27 14:37
Metasploit is not official package for Termux.
Duplicate of https://github.com/termux/termux-packages/issues/3394

Likely you have to reinstall not only metasploit but all it's dependencies.

**Closed by xeffyr** 2019-02-27 14:37 UTC

**Comment by AadiRajUthup** [comment] 2019-02-27 14:38
I've tried everything I reinstalled it more than 7 time. It is the new version of the package which is not working please help.

**Comment by Grimler91** [comment] 2019-02-27 14:56
@AadiRajUthup As xeffyr said, you also need to reinstall/recompile all gems that metasploit depend on

**Comment by AadiRajUthup** [comment] 2019-02-27 15:22
I did but not working.

**Comment by xeffyr** [comment] 2019-02-27 17:16
@AadiRajUthup According to your comment https://github.com/termux/termux-packages/issues/715#issuecomment-467937529, you did **nothing**. You have to REINSTALL ALL DEPENDENCIES from scratch for ruby 2.6.1.

**Comment by AadiRajUthup** [comment] 2019-02-27 17:19
How do I do that?

**Comment by xeffyr** [comment] 2019-02-27 17:21
* Remove old gems for ruby 2.6.0.
* Remove metasploit installation.
* Reinstall metasploit dependencies. I.e. make sure that gems installed for ruby 2.6.1 and **not** for 2.6.0.
* Reinstall metasploit.

If you can't do this for whatever reason, reinstall Termux then.

**Comment by AadiRajUthup** [comment] 2019-02-27 17:22
So I should do the command 'gem update'?
