### ISSUE TITLE
Can't see text while typing

### ISSUE THREAD

**Issue by ProMaster2013** [termux/termux-app#1485] opened 2020-03-10 16:13 UTC
Basically, when I'm typing I can't see any text untill I click either Enter or Space.
And it's only on Termux (I've installed other terminal emulater to test it out, and it works fine, just like in all other apps)

Device: Samsung Galaxy J7 (SM-J730F)
OS: (rooted) Android 9.0 - latest update

**Comment by xeffyr** [comment] 2020-03-10 17:28
Duplicate of https://github.com/termux/termux-app/issues/686.

> And it's only on Termux

Because Termux implements only character-based input (so called "generic"), but Samsung keyboard does not properly handle it.

**Closed by xeffyr** 2020-03-10 17:28 UTC

**Comment by trygveaa** [comment] 2020-03-10 17:37
> Because Termux implements only character-based input

Doesn't ConnectBot also do this? If the issue isn't present there, what do they do? Or is the issue present there as well?

**Comment by xeffyr** [comment] 2020-03-10 17:47
@trygveaa Here is what ConnectBot uses:
``` .java
outAttrs.imeOptions |=
	EditorInfo.IME_FLAG_NO_EXTRACT_UI |
	EditorInfo.IME_FLAG_NO_ENTER_ACTION |
	EditorInfo.IME_ACTION_NONE;
outAttrs.inputType = EditorInfo.TYPE_NULL;
```

**Comment by ProMaster2013** [comment] 2020-03-10 19:00
> Duplicate of #686.
> 
> > And it's only on Termux
> 
> Because Termux implements only character-based input (so called "generic"), but Samsung keyboard does not properly handle it.

Oh, I'm sorry, I looked for some similar posts, but I didn't went that far, thanks.

**Comment by Luid-web** [comment] 2020-08-07 00:45
Please o can't see my text on termux it's like tying into blank space and it won't show and am using tecnoLA7 version 8.1.0
