### ISSUE TITLE
gdb waring: `~ be not at unexpected address`, and can't see my source code.

### ISSUE THREAD

**Issue by ChoiChoongHo94** [termux/termux-app#1418] opened 2020-01-10 05:47 UTC
**Problem description**
I registered this issue to the `termux-packages` project first.
please refer to the site below:
https://github.com/termux/termux-packages/issues/4768

**Comment by Grimler91** [comment] 2020-01-10 06:01
Closing as duplicate of https://github.com/termux/termux-packages/issues/4768

**Closed by Grimler91** 2020-01-10 06:01 UTC
