### ISSUE TITLE
apt-key update segmentation fault

### ISSUE THREAD

**Issue by xxKeith20xx** [termux/termux-app#758] opened 2018-07-03 02:04 UTC
I'm getting this error on pkg update on 0.64:

All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://termux.net stable InRelease: Unknown error executing apt-key
W: Failed to fetch https://termux.net/dists/stable/InRelease  Unknown error executing apt-key
W: Some index files failed to download. They have been ignored, or old ones used instead.

% apt-key update
Segmentation fault (core dumped)
Segmentation fault (core dumped)

All packages up to date
System information:
Linux localhost 3.18.0-17554-g9194949d4df2 #1 SMP PREEMPT Fri Jun 22 17:21:44 PDT 2018 i686 Android
Termux-packages arch:
i686
Android version:
7.1.1
Device manufacturer:
google
Device model:
Samsung Chromebook Pro

**Comment by Grimler91** [comment] 2018-07-03 04:38
Duplicate of https://github.com/termux/termux-packages/issues/2603.

**Closed by Grimler91** 2018-07-03 04:38 UTC
