### ISSUE TITLE
Add better support for root.

### ISSUE THREAD

**Issue by InsideBall** [termux/termux-app#61] opened 2016-03-12 02:12 UTC
Otherwise great, apps like tcpdump do not work at all because they need root access. using su from root does not preserve the enviroment, so it cannot find the binaries, and if you find them manually it cannot find the libs.

this would be really awesome.

**Comment by cswl** [comment] 2016-03-26 05:13
I had written a not so sudo script, which preserves environement and provides the user default shell... 
https://gist.github.com/cswl/cd13971e644dc5ced7b2

Let me know what you think about it..

**Comment by fornwall** [comment] 2016-03-28 21:54
@cswl Looks interesting! Will look closer when I have more time.

Perhaps the su command can be likewise wrapped to make using it from Termux more seamless.

**Comment by fornwall** [comment] 2016-05-18 23:53
[Tabe Kooistra has given this su alias](https://plus.google.com/111490826162202184536/posts/HfJ7Cfc9KXA):

    alias su='/system/xbin/su --preserve-environment -c LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib exec /data/data/com.termux/files/usr/bin/bash --login'
﻿

**Comment by tinydynamite00** [comment] 2016-05-19 01:42
<p>@fornwall I was excited about Tabe Kooistra's aliasing but after adding it to my .bashrc file, <code>su</code> is invoked  (as evidenced by the resultant toast from <code>su</code>) and breaks root at once by returning a <code>$</code> prompt rather than a root shell prompt.</p><br /> 
<p>To query <code>printenv</code> and <code>set</code> while staying the alias, I had to escape <code>su</code> first to get a shell and found the environment isn't preserved at all. I'm fairly certain this is due to the comment I posted here after the issue was closed <a href="https://github.com/termux/termux-app/issues/93#event-665009540">CANNOT LINK EXECUTABLE DEPENDENCIES: library "libgnustl_shared.so" not found #93</a><br />
<p>Again, my apologies. I <em>segfaulted</em> (= </p>

**Comment by deed02392** [comment] 2016-05-19 07:41
Not sure how libraries works in Android, could we just link the termux lib path to the system libs? Then termux bins would work everywhere I imagine? More like an optware for Android than a terminal oasis :)

**Comment by cswl** [comment] 2016-05-23 13:26
I threw in a su wrapper, which automatically uses user defined shell, and also allows to specify alternative shell.. 
If you guys wanna check it out..   https://github.com/cswl/tsu

It's my first time writing README.md .. so formatting is kinda screwed up right now...
I will be busy for a while, so will fix stuffs later.

**Comment by fornwall** [comment] 2016-05-23 21:34
@cswl Awesome!

It would be great if some people could try it up in different rooted devices/environments and report if it's working!

 If it seems ok I guess we could add this as `$PREFIX/bin/su` in the default install (so running `su` will pick up this)? Or do you think it should be `tsu`?

It would be nice (if this wrapper script works well) to have it as the default `su`, so it works more "out of the box", and hopefully it wouldn't confuse/annoy people that Termux wraps the real `su` like this.

**Comment by cswl** [comment] 2016-05-26 11:26
@fornwall 

Well,  `tsu` was intended to be a script to launch root shells (bash, zsh) available in Termux as root. I should really fix the README.  

I'm not sure about the over-riding the `su` like that.
There are these options in the `su` binary from SuperSU. ( Cyanogenmod ships with it's own su implementation, but I can't test.)

```
 -cn, --context CONTEXT       switch to SELinux CONTEXT before invoking
 -mm, --mount-master          connect to a shell that can manipulate the
                               master mount namespace
  -mns, --mount-namespace PID  enter mount namespace used by PID
```

And `su` can also switch user, `su 1000` will switch to that user id.

I can see how people would just want to type like `sudo bash` and expect it to work like in normal unixes, but then again Termux is not. 
If your concern is about people asking the same thing again and again, maybe we could put it up in help section like "Termux and Root".  

About testing, I will try posting it on Google+, so people can give feedback.

**Comment by st42** [comment] 2016-09-22 04:11
I started using Termux a couple weeks ago that I downloaded from F-Droid. I have been using it ever since. I noticed that root use was a problem so I searched online and came across this issues here and decided to solve the problem.

Check out my Github:

https://github.com/st42/termux-sudo.git

Here is the README.md

# termux-sudo
A bash script that provides sudo for Termux  
Termux is a terminal emulator and Linux environment for Android

**Requirements**

Rooted phone with su binary  
SUDO WILL NOT WORK WITHOUT SU

**Installing sudo**

1. Download sudo to phone and extract
2. Open Termux and change to extraction directory
3. Execute the following commands to place sudo into the correct directory with the proper permissions and ownership

```
cat sudo > /data/data/com.termux/files/usr/bin/sudo
chmod 700 /data/data/com.termux/files/usr/bin/sudo
```

**Features**

- Sets up its environment automatically on first run, no need to do anything but use it
- Creates a root folder ```.suroot``` in the Termux home folder with proper root permissions and ownership
- Creates ```.bashrc``` file in root folder with proper PATH and LD_LIBRARY_PATH variables set so all binaries function correctly
- Bash prompt PS1 variable is also set so you don't have ```bash-4.4#``` as prompt just ```#```
- Automatically creates ```.bash_history``` in root folder when you drop to a root shell so root shell history is preserved
- Can be used like ordinary sudo (but only as root, no other user)
- Can drop to root shell ```sudo su [-]```
- Runs built in Termux binaries and exteral binaries with optional arguments as root in current directory
- Generates output in shell currently using
- Can be used in other bash scripts

```
Usage:

sudo su [-]  
  Drop to root shell

sudo <command> [<args>]  
  Run command as root with optional arguments
```

**This was inspired by the following:**

https://github.com/cswl/tsu  
https://gist.github.com/cswl/cd13971e644dc5ced7b2

**Comment by kennethho** [comment] 2016-10-02 16:27
Hi @st42 ,

I failed to get your script to work in my environment when special characters are involved, e.g. file names containing space.

A simple test case:

```
touch 'this is a file' && sudo ls 'this is a file'
```

Here is a script I've been using for a little while that quotes arguments (against word splitting) FYR: https://gist.github.com/kennethho/bc7502dcf6c0b4a53ef85758f797fc8b

It is based on a random version of `su` script from termux-tools. Other than quoting (i.e. word splitting), I never really paid attention to other detail. It's just something FYR.

**Comment by st42** [comment] 2016-10-02 18:12
Hi @kennethho,
The problem has been fixed in the latest commit. Thanks for noticing this.

**Comment by roelfrenkema** [comment] 2016-10-30 07:01
@st42 Is there a way to get this working to elevate permissions to the adb user shell on a unrooted phone? On android 6. All I really need is a workink logcat and till now I only seem to be able to get that through ADB in a termux terminal is will stop with 

`open '/dev/hwlog_switch' fail -1, 13. Permission denied`  

One my CM MM rooted phone and tablet this is working like a charm btw. Just saying. The other one I don't want to root for the SafetyNet stuff.I HATE GOOGLE.

**Comment by st42** [comment] 2016-10-30 13:55
@roelfrenkema As stated in the README.md termux-sudo requires a rooted phone. As far as accessing /dev/hwlog_switch it is owned by root and it's permissions aren't allowing you to access it from within the phone unless you have root access.

**Comment by bdantas** [comment] 2016-11-25 13:00
@st42 Thank you for termux-sudo. It is working great on my rooted nexus5 with cyanogenmod13.

The only issue I have is with two commands that I use in some of my scripts: svc (to turn wifi on and off) and input (to simulate button presses):

[code]
$ sudo /system/bin/svc wifi off
Aborted

$ sudo /system/bin/input keyevent 26
Aborted
[/code]

Given that the termux is telling me nothing about the problem except "Aborted", I'm not sure how to begin troubleshooting. Any ideas?

**Comment by bdantas** [comment] 2016-11-25 13:33
I figured it out! These work in Termux as expected:

<code>$ PATH=/system/bin su -c 'svc wifi disable'</code>
<code>$ PATH=/system/bin su -c 'input keyevent 26'</code>

Now with Termux itself, termux-sudo, and the above all my little scripts will be humming. Beautiful :)

**Comment by jaduncan** [comment] 2016-12-11 05:46
@st42 I've added a su check to your script to support Magisk v9, sent you a pull request.

**Comment by bdantas** [comment] 2016-12-13 16:50
@st42 As I mentioned above, svc and input were not working with termux-sudo. In addition, a benign but perplexing "sh: cd: directory not found" shows up in the terminal when calling sudo and working directory is somewhere in my device's simulated sd card (e.g., /storage/emulated/0/foo). 

Changing this:
[code]CMDLINE="PATH=$PATH:$SYSXBIN:$SYSBIN;$LDLP;HOME=$ROOT_HOME;cd $PWD"[/code]
to this:
[code]CMDLINE="PATH=$PATH:$SYSXBIN:$SYSBIN;$LDLP;HOME=$ROOT_HOME"[/code]
in /data/data/com.termux/files/usr/bin/sudo fixes all of the issues that I mentioned above.

**Comment by st42** [comment] 2016-12-13 17:21
@bdantas I cannot replicate any of the errors you speak of.
`sudo svc wifi disable`
`sudo input keyevent 26`
Both work on my device

Calling sudo from simulated sdcard also works.

My device is running CyanogenMod 12.1 which is Android 5.1.1.

**Comment by st42** [comment] 2016-12-13 17:58
@bdantas 
Check out https://termux.com/storage.html
This may help with your simulated sdcard issues

**Comment by bdantas** [comment] 2016-12-14 14:16
I found a hack that allows me to use the same path to a file for both regular user and sudo:

1. Install this free software (apache license 2.0) application: https://github.com/Androguide/Universal-init.d
2. Run the app and turn switch to "on" to enable init.d scripts
3. Create /system/etc/init.d/20shellfolderperms with this inside:
<code>#!/system/bin/sh
mount -o rw,remount /
chmod 777 /mnt/shell
mount -o ro,remount /
</code>
4. Make the above script executable and reboot

Now I can use a path such as /mnt/shell/emulated/0/foo in bash scripts and, with or without sudo, the path will be valid. Note that steps 1 and 2 above are only necessary if you are running an OS without init.d support (such as me, running CyanogenMod12.1)

**Comment by bdantas** [comment] 2016-12-14 15:05
The above fixes the problem by making /mnt/shell/emulated/0 usable to a regular user, so that both regular user and root can use the same path to a file/directory.
Another approach is to always use /storage/emulated/0 but change it on-the-fly to /mnt/shell/emulated/0 whenever it is passed to sudo.  Just add this line below the ARGS line in the sudo script:

```
ARGS="$(sed 's|/storage|/mnt/shell|g' <<< "$ARGS")"
```
I hope someone other than me finds this helpful. Happy hacking!

**Comment by jaduncan** [comment] 2016-12-27 12:30
Solution 1 is far superior as (amongst other things) it will work on phones where root is available but /system cannot be altered without making an verified boot path fail. There's a few really nasty boot implementations out there.

**Comment by calmosowl** [comment] 2017-01-30 08:44
`su 0 svc wifi enable  # works fine`

**Comment by vlad3ciobanu** [comment] 2017-03-01 23:29
Some useful info: in LineageOS (and I think in CM13 also) the su binary does not preserve the environment (-m -p --preserve-environment). The code is not present in su and the related help text is commented out. Source [here](https://github.com/LineageOS/android_system_su/blob/master/su.c).

**Comment by fornwall** [comment] 2017-03-01 23:43
@vlad3-3-3 Interesting, thanks for sharing!

**Comment by muhammadsayuti** [comment] 2017-03-30 10:15
Got error when using termux-sudo by @st42  with node 
'env: can't execute 'node': Permission denied'
is there any workaround ?

**Comment by bdantas** [comment] 2017-04-01 07:21
Muhammad,

I do not use node, but on any *nix (including termux/android) sudo only elevates privileges of the first command it encounters. For example, in

sudo foo | bar

Foo gets run as root but not bar. Something like this would have the expected effect:

sudo bash -c "foo | bar"

If you share your actual command that's giving the permission error I might be able to help you write the command in a way that will work.

**Comment by muhammadsayuti** [comment] 2017-04-05 06:29
i only try to install using bower and npm and i think this issue is related to #240

**Comment by sun2rise** [comment] 2017-06-06 06:59
I'm sorry, any news on this? i was trying to `npm install berkeleydb` but i got
```
../dist/configure: not found
make: *** [Makefile:12: config] Error 127
```

Any known solution?
Thanks

**Comment by yeahnope** [comment] 2018-03-24 18:11
Has anyone figured out a way to get a clean root shell on lineageos 15.1? I have tried both the su from 14.1 and the su for 15.1 from [this thread](https://forum.xda-developers.com/mi-5/development/rom-lineageos-15-0-xiaomi-mi-5-t3669247). Both give me root permissions, but both mess up the shells:

- Ctrl+c always closes the su process and all of its children (even if they are shells)
- Any command is echoed in the shell before showing the output of the command
- The TERM variable is changed and even if this is fixed manually, I can't find a way to make cursor keys work or ncurses applications run as intended.

Is there any way to start a fresh shell that is decoupled from the su process but still outputs to my current terminal, once I can start a process as root?

**Comment by cswl** [comment] 2018-03-30 13:09
@yeahnope  Did you try with `tsu` it's available on termux repos.. so you can just
```
pkge install tsu
```

**Comment by Grimler91** [comment] 2018-03-30 15:37
Maybe we can close this issue by now, tsu works for all my root needs at least.

**Closed by Grimler91** 2018-03-30 15:37 UTC
Labels: Feedback needed, enhancement

**Comment by bhavesh96** [comment] 2019-06-15 10:44
Not work sudo it's show 

"su executable not found
sudo requires su "

What do i ?

**Comment by xeffyr** [comment] 2019-06-15 11:49
> What do i ?

root your device.

**Comment by bhavesh96** [comment] 2019-06-15 11:54
I install sudo for wifi-hacker but it is show

"su executable not found
sudo requires su"

**Comment by xeffyr** [comment] 2019-06-15 11:59
> I install sudo for wifi-hacker but it is show

**root your device** and su/sudo will work !
