### ISSUE TITLE
[Bug]: Linux Desktop being killed.

### ISSUE THREAD

**Issue by MattTheTekie** [termux/termux-app#3380] opened 2023-05-06 12:01 UTC
### Problem description

I have a friend which is a fluent developer, like I am to a extent. The issue were having is with his termux Linux proot desktop being killed after a few seconds of being opened. His device is a really powerful device, but he's running evolution x, and this never happened on MIUI. The wakelock functionality doesn't work.

### Steps to reproduce the behavior.

Open termux, and start the proot desktop
Connect via X client
Wait a minute for it to crash.

### What is the expected behavior?

The app shouldnt crash.

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: Xiaomi Pad 5 Pro 5G

**Comment by agnostic-apollo** [comment] 2023-05-06 13:39
Duplicate of #2366

**Closed by agnostic-apollo** 2023-05-06 13:39 UTC
Labels: bug report

**Comment by MattTheTekie** [comment] 2023-05-06 15:57
It works now, thank you for the reference.

**Comment by agnostic-apollo** [comment] 2023-05-06 17:27
Welcome.

**Comment by Austcool-Walker** [comment] 2023-05-07 01:07
@agnostic-apollo @MattTheTekie So for me and what me and the Matt guy found out is running this one liner command in a full root access shell fixes this problem. Please star and bookmark this thread for reference.
```
# tsu for a root level prompt. (su would probably work I didn't test it tho)
tsu
settings put global settings_enable_monitor_phantom_procs false
```
then run the apps/programs you want to run without a memory killer.
Then when you're done or just simply want to limit battery drain or preformance drag run.
```
settings put global settings_enable_monitor_phantom_procs true
```
And that should be enough to correct the problem. ✅

**Comment by MattTheTekie** [comment] 2023-05-07 01:09
> @agnostic-apollo @MattTheTekie So for me and what me and the Matt guy found out is running this one liner command in a full root access shell fixes this problem. Please star and bookmark this thread for reference.
> ```
> # tsu for a root level prompt. (su would probably work I didn't test it tho)
> tsu
> settings put global settings_enable_monitor_phantom_procs false
> ```
> then run the apps/programs you want to run without a memory killer.
> Then when you're done or just simply want to limit battery drain or preformance drag run.
> ```
> # tsu for a root level prompt. (su would probably work I didn't test it tho)
> settings put global settings_enable_monitor_phantom_procs true
> ```
> And that should be enough to correct the problem. ✅

Both issues should be referenced as both are really informative.

**Comment by MattTheTekie** [comment] 2023-05-07 01:10
I think that calls a end to this issue. Thank you @agnostic-apollo @Austcool-Walker for everything!
