### ISSUE TITLE
Scrolling upwards inside tools has problems

### ISSUE THREAD

**Issue by vicarian** [termux/termux-app#218] opened 2016-12-26 21:02 UTC
Hello,

I would like to report an issue with scrolling inside Termux.

* Using a bt hw keyboard:
While scrolling up (both per page and per line) inside tools such as "man" pages or "less", the scrolling is pretty much delayed, slow and otherwise very jerky/laggy. Scrolling down works like a charm, as it should.

* Using the touchscreen (sliding it with fingers):
Same effect can be observed while using the touch screen to scroll up inside programs/tools. Scrolling up lags, scrolling down works perfectly. However, while remaining on the main shell window/screen (i.e. not using "man" or "less", etc.), both upwards and downwards scrolling works properly.

termux: v0.44
sw: android 6.0.1
hw: samsung galaxy tab s2 (w/ proper samsung bt hw keyboard)

Great work with Termux! I really like this app and appreciate the development.

**Comment by kanmeiban** [comment] 2017-06-20 16:02
Scrolling up lags between 2 and 10-20 seconds for me. Most of the time it is so slow that a system dialog pops up **Termux is not responding. Do you want to close it?**. It is the same no matter input: touchscreen, mouse, software or hardware blutooth keyboard.

termux: v0.52
os: android 5.0.1
hardware: Lenovo Yoga 2 tablet (with Apple bluetooh hardware keyboard, Microsoft 3600 bluetooth mouse).

**Comment by gordol** [comment] 2017-10-20 09:38
I've started noticing a pattern with this...

Scrolling (and output) are pretty slow if I have termux open full screen, but when the output is colored, it becomes unbearably slow, to the point of taking many seconds to render or update, and sometimes when it does update there are many rendering bugs. 

If it's just plain text, it's super quick and responsive in comparison, but it's still slow IMO.

I can hear the fan on my laptop spin up pretty loud... and CPU usage spikes so much that the watchdog wants to kill the app because it's "unresponsive". If i just wait it out about 10 seconds, usually it catches up finally.

I'm on a Chromebook Pixel LS, so it should have plenty of CPU and memory.

**Comment by rtmf** [comment] 2017-10-20 23:47
I have only had this issue in a pronounced manner relatively recently (however, downgrading as far as 0.51 has not shown any significant improvement.  Unfortunately, this test is not clean as I have also switched to yet another device recently, though given the reports there is reason to suspect the issue affects more than just low-end devices like mine (1gb ram, quad-core armv7r3, MT8127 chipset, android 6.0, nothing too special)

**Comment by kanmeiban** [comment] 2017-10-21 07:59
Scrolling on a phone with significantly smaller screen than tablet happens
in the same slow speed, but as much less text is rendered it is not so
noticeable. I can confirm that colored text gets garbled sometimes - I use
colored prompt and from time to time it leaves long diagonal lines behind
when it scrolls up.

**Comment by xeffyr** [comment] 2019-09-06 12:51
Should be already fixed (or at least reduce lags) with https://github.com/termux/termux-app/pull/628. If not, ask to re-open issue.

**Closed by xeffyr** 2019-09-06 12:51 UTC
Labels: bug report
