### ISSUE TITLE
[Feature]: Tabs

### ISSUE THREAD

**Issue by ballo** [termux/termux-app#4134] opened 2024-09-02 00:10 UTC
### Feature description

Multiple sessions has never worked for me. The key bindings don't work, and no gesture works, either. Why not just use tabs like every browser does? Konsole does this (as well as split screen) and it works great

### Additional information

Maybe the entire interface needs a rethink

**Comment by agnostic-apollo** [comment] 2024-09-02 18:26
Duplicate of #3798

Shortcuts work too.

https://wiki.termux.com/wiki/Terminal_Settings#Handling_terminal_sessions

**Closed by agnostic-apollo** 2024-09-02 18:26 UTC

**Comment by ballo** [comment] 2024-09-03 19:24
The tag you linked to doesn't mention tabs

**Comment by Biswa96** [comment] 2024-09-03 19:36
Does not this look like tab after opening multiple session in termux app?

![image](https://github.com/user-attachments/assets/b2ae1baf-5a11-4e40-8e19-73d464feab45)

**Comment by ballo** [comment] 2024-09-07 21:03
> Does not this look like tab after opening multiple session in termux app?
> 
> ![image](https://private-user-images.githubusercontent.com/31443074/364118217-b2ae1baf-5a11-4e40-8e19-73d464feab45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDMxMjUsIm5iZiI6MTcyNTc0MjgyNSwicGF0aCI6Ii8zMTQ0MzA3NC8zNjQxMTgyMTctYjJhZTFiYWYtNWExMS00ZTQwLThlMTktNzNkNDY0ZmVhYjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIxMDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlOTlhZDk3YjM3OTU1MzM2NmFkNmM2M2RhYTUyN2Y5YTIyNDk5ZDhlZjI1OGVkZmI2OTQ2YmMzZDkyMTMyNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9ALTp0I4DZIfPULq04wG1aUp3wiXQ8lfkkw6qKmQoc8)

I don't know what I'm looking at, here. Never seen it in termux. The only time I've ever seen a cog is when press holding Termux on the home screen, and there are never multiple sessions displayed. When the app opens it signifies the 2nd session with no obvious (using this term literally) way to switch

**Comment by agnostic-apollo** [comment] 2024-09-07 21:14
Open the terminal, then swipe right from left edge of screen. Or add `DRAWER` extra key if gestures don't work on your phone. You are not alone, many people spend years without knowing it exists.

https://wiki.termux.com/wiki/User_Interface

**Comment by ballo** [comment] 2024-09-11 03:30
Android 14 uses that gesture to go back. How old is your phone?

**Comment by Biswa96** [comment] 2024-09-11 03:33
> Android 14 uses that gesture to go back.

That's probably not default in Android 14. I am using LineageOS 21 which is Android 14.

**Comment by twaik** [comment] 2024-09-11 08:47
> Android 14 uses that gesture to go back. How old is your phone?

https://github.com/termux/termux-app/issues/3798#issuecomment-1906401542

**Comment by ballo** [comment] 2024-09-14 01:51
> > Android 14 uses that gesture to go back. How old is your phone?
> 
> This doesn't really matter.
> 
> With gestures enabled one need to hold for about one second the left screen side before swiping. Works on all my devices with Android 14.

You want me to hold and wait for a full second just to switch sessions?
Why not just have tabs like any browser?

**Comment by agnostic-apollo** [comment] 2024-09-14 01:55
Or maybe just add the `DRAWER` key to extra keys as told many times, just like browsers have a button. Locking since nothing useful more to be discussed about it.
