### ISSUE TITLE
hashdeep exits with error

### ISSUE THREAD

**Issue by Wolfram-Wolf** [termux/termux-app#518] opened 2017-12-28 11:13 UTC
$ hashdeep --help
/home/fornwall/.termux-build/hashdeep/src/src/main.cpp:1250: int main(int, char **): assertion "sizeof(off_t)==8" failed
Aborted

**Comment by Wolfram-Wolf** [comment] 2017-12-28 11:20
md5deep and the sha variants of hashdeep exit with the same error.

**Comment by Grimler91** [comment] 2017-12-28 11:27
Which arch are you on (`uname -a`)? Seems to work fine on aarch64.

**Comment by Wolfram-Wolf** [comment] 2017-12-28 14:59
I guess it is some problem related to the repackaging of hashdeep for termux. 
uname -a gives Linux localhost 3.4.113-ge4809c6 #1 SMP PREEMPT Tue Oct 10 10:14:07 CEST 2017 armv7l Android. Are you on some variant of Arch Linux? There maybe different packages for it.

**Comment by Grimler91** [comment] 2017-12-28 16:36
@Wolfram-Wolf yeah, arch linux packages are different, and out of our scope. 

I tried it in normal termux though, without problems. I can try it on arm later. 
Make sure that all of your packages are up to date.

**Comment by Grimler91** [comment] 2017-12-28 20:27
I am able to reproduce the error on my arm device.

**Comment by Grimler91** [comment] 2017-12-28 20:52
This seems to be a duplicate of this issue: https://github.com/termux/termux-packages/issues/1733. Closing in favour of that one.

**Closed by Grimler91** 2017-12-28 20:52 UTC

**Comment by fornwall** [comment] 2017-12-29 00:04
This should now be fixed in the latest 4.4-1 version of the hashdeep package - install with `pkg up`.

Unfortunately this updates requires Android 7.0 or later for 32-bit arches (arm and i686) to work correctly.
