### ISSUE TITLE
Keyboard layout on Chromebook

### ISSUE THREAD

**Issue by olivierauverlot** [termux/termux-app#427] opened 2017-09-17 16:40 UTC
I just tried Termux on my Chromebook that supports Google Play. That's works fine but it's a french computer with an AZERTY keyboard. Termux uses an QWERTY layout. How to change the keyboard layout ?

**Comment by Grimler91** [comment] 2017-09-17 16:57
Sounds like this is a duplicate of https://github.com/termux/termux-app/issues/250.

**Closed** 2017-09-17 21:20 UTC
