### ISSUE TITLE
[Bug]: pkg update fails with syntax error

### ISSUE THREAD

**Issue by emmandyar** [termux/termux-app#2787] opened 2022-05-22 17:56 UTC
### Problem description

Doing pkg update, right after mirror testing ends, pjg fails with a syntax error:
```
Welcome to Termux!

Communities: https://termux.org/community
Gitter chat: https://gitter.im/termux/termux
IRC channel: #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.org/issues

~ $ pkg update
Testing the available mirrors:
[*] https://mirror.mwt.me/termux/main: ok
[*] https://termux.sahilister.in/apt/termux-main: ok
[*] https://plug-mirror.rcac.purdue.edu/termux/termux-main: ok
[*] https://termux.mentality.rip/termux-main: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://termux.librehat.com/apt/termux-main: ok
[*] https://termux.astra.in.ua/apt/termux-main: ok
[*] https://packages-cf.termux.org/apt/termux-main: ok
[*] https://dl.kcubeterm.com/termux-main: ok
/data/data/com.termux/files/usr/bin/pkg: line 142: 7
8
9
10
11
12
13
14
16: syntax error in expression (error token is "8
9
10
11
12
13
14
16")
~ $
```

### Steps to reproduce the behavior.

Start termux, run `pkg update`

### What is the expected behavior?

Ut uodate repositories info and informs you if there are new updates

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: Motorola One Hyper

**Comment by agnostic-apollo** [comment] 2022-05-22 19:19
Duplicate of termux/termux-packages#10778

**Closed by agnostic-apollo** 2022-05-22 19:19 UTC
Labels: bug report
