### ISSUE TITLE
Custom extra-keys layout can be funny (in a bad way)

### ISSUE THREAD

**Issue by gulhe** [termux/termux-app#1064] opened 2019-03-14 08:42 UTC
**Problem description**
The `extra-keys` array of arrays in `~/.termux/termux.properties` is a very nice thing which I gladly adopt :)
However, since I did, all the keys I requested dispatched in 3 rows appear but the "textual keys" like `CTRL`, `PGUP` and such appear weirdly, only the two first letters of each appear atop each other.
All the buttons are crammed to the left of the screen except the last on of the last row which is in the middle ...
![Weird](https://user-images.githubusercontent.com/985787/54110105-cb0ef080-43e0-11e9-99db-9a352b7036db.jpeg)

**Steps to reproduce**
My config is :
extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN'],['~', '|','`','(',')','[',']','{','}','<','>']]
in ~/.termux/termux.properties

**Expected behavior**
when you reload your config with `termux-reload-settings` it will look odd ...

**Comment by gulhe** [comment] 2019-03-14 08:47
Btw I, since, found a workaround ...
If each extra-keys row holds the same amount of keys you might be fine ...
I was like [7,7,11], I redispatched to [9,9,9] and now it looks fine and dandy, all keys are evenly spaced :)

**Comment by xeffyr** [comment] 2019-03-14 11:36
Buttons size is determined by size of the smallest one, i.e. extra keys row has a table structure. If one of the rows will have a different length, then of course it will be shifted.

**Comment by xeffyr** [comment] 2019-09-06 13:24
Closing as generally not a bug but extra keys misconfiguration.

**Closed by xeffyr** 2019-09-06 13:24 UTC
