### ISSUE TITLE
[Bug]: Cannot switch keyboards normally

### ISSUE THREAD

**Issue by luckrule** [termux/termux-app#2743] opened 2022-04-28 05:22 UTC
### Problem description

https://user-images.githubusercontent.com/64148888/165681782-bec77fe7-5495-4a53-887e-7ce45ea182cd.mp4

### Steps to reproduce the behavior.

Just update to the latest version

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: xiaomi k40

**Comment by luckrule** [comment] 2022-04-28 05:25
![IMG_20220428_132417](https://user-images.githubusercontent.com/64148888/165682132-30455a65-9521-4a3d-bf95-c99b76da738c.jpg)
termux.properties

**Comment by agnostic-apollo** [comment] 2022-04-28 06:03
Duplicate of #2503

**Closed by agnostic-apollo** 2022-04-28 06:03 UTC
Labels: bug report
