### ISSUE TITLE
Touch-scrolling up sometimes puts out junk output to the command-line rather than showing the previous terminal output

### ISSUE THREAD

**Issue by joakim-noah** [termux/termux-app#702] opened 2018-06-03 10:30 UTC
I've run into this a couple times lately on different devices, when trying to scroll up to see off-screen terminal output. I don't know if it's trying to scroll up the command-line log of previous commands instead or what. 
 However, I cannot reproduce it consistently, so I'm opening an issue for when someone can do so.

**Comment by l-jonas** [comment] 2018-06-10 13:00
@joakim-noah Can you give any details? (phone model, app version, app source (google play, f-droid), android version). How can it be reproduced (how much output must be there to make this occur, which commands do you use to trigger it)?

**Comment by easyaspi314** [comment] 2018-06-10 15:47
Assuming you have nano installed, does this cause that behavior?
```
{ sleep 0.5; killall -KILL nano } & nano
```

If so, that is normal. Just hit Ctrl-C, then run `reset`.

**Comment by joakim-noah** [comment] 2018-06-11 06:22
I saw this on an HTC phone running Android 8.0 and a Samsung tablet running 6.0, both with the latest Termux release 0.60 from the Play store. As I said initially, it randomly happened so I'm not sure how to trigger it again, but the fact that I was seeing it on two devices suggested it was worth mentioning.

As for the nano command above, I tried it with `vim` and couldn't reproduce.

**Comment by easyaspi314** [comment] 2018-06-11 11:56
So you don't see something like
```
64;61;27M
```
(numbers may vary) spammed to the console?

If it ever happens again, could you send a screenshot?

**Comment by joakim-noah** [comment] 2018-06-11 12:09
That is exactly the kind of junk chars I saw before with this bug, just not with the command you gave, with `vim` in place of `nano`.

**Comment by easyaspi314** [comment] 2018-06-11 12:39
So basically, what happened is that your terminal got stuck in alternate screen mode, which does that ugly thing. It was designed for `ncurses` applications like `nano` and `vim` to allow them to decode mouse events.

All `ncurses` programs are expected to call `endwin()` which will put the terminal back into a normal state. However, an `ncurses` program can't do that if it is abruptly stopped (from an unhandled segfault, a kill signal like the one I manually fired to cause this, or something similar). Because of this, the terminal will get stuck in this state. 

To fix this, use this better command than the previous one:
```
tput rmcup;stty sane;reset
```

This isn't a bug, it is entirely expected behavior. To show this, here it is in a few other terminals:
<details><summary>Click to show</summary>

### Termux
![screenshot_termux_20180611-082512](https://user-images.githubusercontent.com/6258309/41231478-2b3f37ce-6d51-11e8-9dce-44289f89d56f.png)
### iTerm2
![screen shot 2018-06-11 at 8 17 40 am](https://user-images.githubusercontent.com/6258309/41231487-311f166e-6d51-11e8-8feb-269b5aaa2b6a.png)
### Jack Palevich's Terminal Emulator for Android
![screenshot_terminal_emulator_20180611-083218](https://user-images.githubusercontent.com/6258309/41231746-1e400598-6d52-11e8-89e9-17f59d4baf3d.png)
### Hyper
![screen shot 2018-06-11 at 8 36 01 am](https://user-images.githubusercontent.com/6258309/41231887-970bca7a-6d52-11e8-8aed-35fb57c5d341.png)
### Terminal.app
![screen shot 2018-06-11 at 8 37 42 am](https://user-images.githubusercontent.com/6258309/41231932-bc4ae80c-6d52-11e8-8b54-1af34f9cecc3.png)

</details>

**Comment by Neo-Oli** [comment] 2018-06-11 12:53
> However, an `ncurses` program can't do that if it is abruptly stopped (from an unhandled segfault, a kill signal like the one I manually fired to cause this, or something similar). 

By far the most common cause of this is an ssh connection breaking up while you run any kind of ncurses application (tmux, screen, vim etc.) on the remote machine.

**Comment by easyaspi314** [comment] 2018-06-11 12:58
That too. I forgot about that because I rarely ever use ssh.

**Comment by l-jonas** [comment] 2018-06-11 13:36
Eventually it is possible to detect if the Terminal is in an unwanted state and reset it then automatically after every command, e.g. with https://github.com/Bash-it/bash-it/blob/master/lib/preexec.bash and settings a precmd function which does that.

**Comment by Neo-Oli** [comment] 2018-06-11 13:41
Closing this, because it is normal Unix behaviour and not Termux specific.

**Comment by Neo-Oli** [comment] 2018-06-11 13:42
@l-jonas Setting something like that in a preexec would be bad, because calling `reset` will also hide whatever error caused the terminal to get into an unwanted state.

**Closed by Neo-Oli** 2018-06-11 13:41 UTC

**Comment by easyaspi314** [comment] 2018-06-11 14:37
By the way, @joakim-noah, I don't mean to be harsh, but I just want to let you know that some people, especially in larger projects, can get really mad at you when you don't follow their steps exactly.

I was only mildly annoyed.

While most of the time, such as in this case, the specific steps include unnecessary or overly specific rituals like `make clean` or not using keyboard shortcuts, if this was, for example, bug #678, you wouldn't be able to reproduce it in `vim` because it handles pasting differently.

I learned this lesson the hard way when I complained about a (completely pointless) `make clean` on a large project, and the feedback I got ruined my whole day.

Again, please don't take this personally. I just don't want anyone else to get the same treatment I did, because some people will get a lot harsher than this.

I completely understand if you prefer using a different text editor.

**Comment by joakim-noah** [comment] 2018-06-11 16:41
No problem, I figured the editor didn't matter and just used my normal editor to test. Since this bug was hitting me from using `vim` remotely anyway, that makes sense anyway.
