### ISSUE TITLE
Unable to install bootstrap error[Bug]: 

### ISSUE THREAD

**Issue by f-o-r-t** [termux/termux-app#3973] opened 2024-05-30 05:56 UTC
### Problem description

Shows: Termux can only be run as the primary user. Bootstrap binaries compiled for Termux have hardcoded $PREFIX path and cannot be installed under any path other than '/data/data/com.termux/files/usr'

### Steps to reproduce the behavior.

I dont know I am a beginner

### System information

* Termux application version:0.118.0
* Android OS version:13
* Device model:redmi note 11 pro+

**Comment by twaik** [comment] 2024-05-30 05:58
Duplicate of #2291

**Comment by twaik** [comment] 2024-05-30 05:59
Duplicate of #2765

**Closed by twaik** 2024-05-30 05:58 UTC
Labels: bug report

**Comment by kqp7526-cmd** [comment] 2025-08-10 06:56
Termux Bootstrap Error

Termux can only be run as the primary user.

Bootstrap binaries compiled for Termux have hardcoded $PREFIX path and cannot be installed under any path other than:

`/data/data/com.termux/files/usr`.

agree

PGUP

**Comment by kqp7526-cmd** [comment] 2025-08-10 06:57
Termux Bootstrap Error

Termux can only be run as the primary user.

Bootstrap binaries compiled for Termux have hardcoded $PREFIX path and cannot be installed under any path other than:

`/data/data/com.termux/files/usr`.

agree

PGUP
``
