### ISSUE TITLE
Enhancement: share url to termux without opening the app

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-app#1719] opened 2020-08-19 08:33 UTC
whenever i am browsing i need to share url directly to termux and that url is to be copied  to a file in background without letting termux run in foreground. How can i achive this? Please help

What i have tried till now is using termux url opener and in it in have 

Option1 : ```echo '$1' >> file```
Option2:```echo '$1' >> file &```
Option3:```echo '$1' >> file && exit```

But option1 opens termux and i need to switch back to browser. 
Option2 and 3 opens temux does the work and exit.

But i need it to be done without opening termux as it causes delay in my work
Needed help for below:
But i want to share lot of urls fastly so if it can be done in background just click share and termux and in background it will take url and echo and redirect to file.

Please help someone

**Comment by Grimler91** [comment] 2020-08-19 08:57
Probably cannot be done with the current termux-app so I'll convert this to an enhancement request.

**Comment by kcubeterm** [comment] 2020-08-19 08:58
You can use ```termux-clipboard-get``` , once you copy url , you can retrieve your copied url with this command ,

**Comment by Grimler91** [comment] 2020-08-19 08:59
Duplicate of https://github.com/termux/termux-app/issues/254

**Closed by Grimler91** 2020-08-19 08:59 UTC
Labels: enhancement
