### ISSUE TITLE
Add Python 3.10.0b2

### ISSUE THREAD

**Issue by anton2007** [termux/termux-app#2101] opened 2021-05-31 17:57 UTC
**Feature description**
Add Python 3.10.0b2 on unstable repos

**Reference implementation**
Compile Python 3.10.0b2 via CLANG (Android NDK) on your PC for ARMv7l, AArch64, i686, X86_64

Does another app/terminal emulator have this feature?
No
Provide links to more background information.
https://github.com/python/cpython/releases/tag/v3.10.0b2

**Comment by Grimler91** [comment] 2021-05-31 18:48
Duplicate of https://github.com/termux/termux-app/issues/2101

**Closed by Grimler91** 2021-05-31 18:48 UTC
