### ISSUE TITLE
Feature: Samsung float apps

### ISSUE THREAD

**Issue by fornwall** [termux/termux-app#183] opened 2016-10-31 00:24 UTC
_From @MariuszPL55 on October 29, 2016 22:36_

Hey,
Can you add support for Samsung feature of float apps? It would be great for me, please.

_Copied from original issue: termux/termux-packages#528_

**Comment by Neo-Oli** [comment] 2016-11-07 07:11
Are float apps the same as multi-window? 
Possible duplicate of https://github.com/termux/termux-app/issues/29

**Closed** 2016-11-24 22:45 UTC
Labels: enhancement
