### ISSUE TITLE
how could this happen 

### ISSUE THREAD

**Issue by amarullah** [termux/termux-app#1063] opened 2019-03-13 07:01 UTC
CANNOT LINK EXECUTABLE DEPENDENCIES: library "libreadline.so.8" not found

**Comment by xeffyr** [comment] 2019-03-13 09:23
```
pkg upgrade
```

**Comment by xeffyr** [comment] 2019-03-13 09:24
Duplicate of https://github.com/termux/termux-packages/issues/3507

**Closed by xeffyr** 2019-03-13 09:23 UTC
