### ISSUE TITLE
[Bug]: Unable to setup storage when using the command 'termux-setup-storage'

### ISSUE THREAD

**Issue by kanodecat** [termux/termux-app#3740] opened 2023-12-16 21:04 UTC
### Problem description

This issue first started when I was trying to use Termux with an add-on 'Acodex - Terminal' with the text editor 'Acode'. I sent an issue to their repo about the problem seen here https://github.com/bajrangCoder/acode-plugin-acodex/issues/42 . But was able to solve it by reinstalling Termux and then reinstalling the 'acodeX-server' via Termux by doing 'apt upgrade && apt update' then entering the command 'curl -sL https://raw.githubusercontent.com/bajrangCoder/acode-plugin-acodex/main/installServer.sh | bash' seen here: https://github.com/bajrangCoder/acode-plugin-acodex. I'll close the issue once this issue is fixed since they're related in someway.

### Steps to reproduce the behavior.

Installing Termux and then reinstalling the 'acodeX-server' via Termux by doing 'apt upgrade && apt update' then entering the command 'curl -sL https://raw.githubusercontent.com/bajrangCoder/acode-plugin-acodex/main/installServer.sh | bash' seen here: https://github.com/bajrangCoder/acode-plugin-acodex. After I reinstalled Termux I didn't setup the storage when installing the node packages, and then realized afterwards and quickly reinstalled Termux again. Unfortunately after reinstalling Termux and running the command 'termux-setup-storage' no directory appears called storage after running command 'ls', and running the ls command with the -a argument shows the current directory, parent directory, and hidden directory '.termux'. Here's a screenshot: 
![Screenshot_20231214-190359](https://github.com/termux/termux-app/assets/56785252/43f561c8-86d1-4791-8f1b-83dd38a72e42)

### What is the expected behavior?

After typing the command 'termux-setup-storage' and 'ls' a directory should appear called 'storage' which contains a fake/real directory of the phone's home directory.

### System information

* Termux application version: 0.118.0 fdriod
* Android OS version: 14. Custom rom GraphneneOS if that matters
* Device model: Pixel 6

**Comment by twaik** [comment] 2023-12-16 21:20
You are talking about 3rd-party app that we offer zero support for.
In other words: Use at your own risk and we take zero responsibility for what that app does to Termux or your device.
Also pay attention that running any commands like `curl ... | bash` is **very** dangerous unless you know exactly what you do.

**Comment by agnostic-apollo** [comment] 2023-12-17 04:46
Partially duplicate of #3647

**Closed by agnostic-apollo** 2023-12-17 04:46 UTC
Labels: bug report

**Comment by kanodecat** [comment] 2023-12-22 02:20
The third-party app served as background information to my current situation. As highlighted by agnostic-apollo, my experience parallels the issue outlined in #3647. I attempted to use Termux on a family phone and discovered that the problem lies in Termux not functioning properly on Android 14, and through a long matrix conversation a few days ago with Ted and agnostic-apollo. I wont be replying anymore to this page as this is connected to issue #3647, my intention here was to clarify some miscommunication.

**Comment by agnostic-apollo** [comment] 2023-12-23 22:45
Check https://github.com/termux/termux-api/issues/638#issuecomment-1868383070
