### ISSUE TITLE
Npm doesn't work

### ISSUE THREAD

**Issue by F0RIS** [termux/termux-app#466] opened 2017-11-03 09:20 UTC
https://github.com/npm/npm/issues/19050

#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?
Instal termux app on android, install nodejs 8.9.0 (latest in termux repo) and try install any package with npm.
On previous versions it worked fine.

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: 8.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

![screenshot_20171103-110701](https://user-images.githubusercontent.com/10178982/32366848-99038e20-c088-11e7-92c6-6dcce310e409.png)

**Comment by Neo-Oli** [comment] 2017-11-03 09:35
Duplicate of https://github.com/termux/termux-packages/issues/1192, which previously only applied to `nodejs-current` but now also applies to `nodejs`. I believe there is a fix ready here: https://github.com/termux/termux-packages/pull/1701

**Closed by Neo-Oli** 2017-11-03 09:35 UTC
Labels: duplicate
