### ISSUE TITLE
Directional extra keys don't look like directional keys

### ISSUE THREAD

**Issue by HiDe-Techno-Tips** [termux/termux-app#2095] opened 2021-05-31 02:36 UTC
**Problem description**

# Directional extra keys don't look like directional keys

I successfully configued extra keys but look at the extra keys in this screenshot below.
The `ij` you see is UP key, the `'` below it is DOWN, `IJ` is LEFT and `'n` is RIGHT. Why is this happening? How do I make them look like Directional Keys?

**EDIT:** All the extra keys including the directional keys are working properly, only the directional keys are displayed wrong.

![Screenshot_20210531-074947](https://user-images.githubusercontent.com/61367380/120130894-dc708d00-c1e4-11eb-80ef-02b7089ff3cd.png)

**Steps to reproduce**

* Run `nano ~/.termux/termux.properties`.
* Paste the following in the end of the file:
  ```
  extra-keys =[   ['ESC', '~',    'TAB',  'UP',   '|',            '/',            'QUOTE'], \
  ['CTRL','ALT',  'LEFT', 'DOWN', 'RIGHT',        'BACKSLASH',    'APOSTROPHE']   ]
  ```
* Save the file and exit from nano.
* Run `termux-reload-settings`.

**Expected behavior**

In the above screenshot, the `ij` should be `↑`, the `'` below it should be `↓`, `IJ` should be `←` and `'n` should be `→`.

**Additional information**

* Termux application version: 0.113
* Android OS version: 10(Q)
* Device model: Tecno KE6j (Spark 6 Air)

**Comment by agnostic-apollo** [comment] 2021-05-31 03:02
Duplicate of #1410.

Add `extra-keys-style=none` to `termux.properties`.

Real reason should be figured out too.

**Closed by agnostic-apollo** 2021-05-31 03:02 UTC

**Comment by agnostic-apollo** [comment] 2021-05-31 10:52
Can you send the output for

- `printf '\u2190'`
-  `printf '\u25C0'`
- `cat /system/etc/fonts.xml`

Make sure to use a markdown code block. Thanks.
