### ISSUE TITLE
Offer option to skip [Process completed - press Enter] message

### ISSUE THREAD

**Issue by alxpettit** [termux/termux-app#988] opened 2019-01-21 22:25 UTC
I'm not quite sure where to put this request, but since I believe this behavior is built into the core app, I'll put it here. Whenever I use the widgets plugin to launch what is supposed to be a backup process, I always end up with a _[Process completed - press Enter]_ message popping up immediately after. This window doesn't offer any new information unless the process failed and is printing error text. Therefore, it goes against the general Unix principle of minimal information output and user interaction.

Example use cases: A lot of my widget shortcut scripts are meant to run very quickly, spawn whatever forking processes they need, and then exit with no STDOUT. For example, I have one called `start-sshd` that consists simply of:

```
termux-wake-lock
sshd
```

The window popup serves absolutely no function in this case or in any of my other daemon management scripts (which are meant to handle things like sshd and nginx).

At the same time, of course, it is very useful to have the option to display text output, e.g. for using `termux-battery-status` as a one-click battery status checking utility.

So, the way I see it, there are several ways to engineer a relatively simple solution while keeping the best of both worlds:

1. Have a user-configurable option to skip the popup on a special case basis. (Con: adds configuration complexity.)
2. Have the popup skipped if the program doesn't output anything. (Con: does not alert user to exit code, but I don't believe the current system does either.)
3. Have the popup skipped based on if the exit code is zero. (Con: does not allow scripts like `termux-battery-status` that are meant to display stuff to work, without a wrapper that adds a spurious `exit 1` or somesuch to the end as a workaround)

In general, I think the window popup should be replaced with a small fading message to alert the user that it exited successfully -- so no matter which option we use, the user knows their script ran. This fading message could even specify the exit code, which would be a nice hint as to what's going on without being obtrusive.

I'm curious to know which solution people think is best, and if anyone has any better ideas! Also, sorry if I put this in the wrong place. I'm really not sure where to put it, but it seems to go beyond the widget utility and into core app functionality.

**Comment by trygveaa** [comment] 2019-01-21 22:40
There was a large discussion surrounding this in #56. That was closed because the message now only appears for the last terminal session, but as several people pointed out there, that doesn't really solve the issue.

The only real reason I've seen for keeping it is that you need some way to open a fallback session if you break the shell. This could be solved with adding a shortcut for opening a fallback session (at least for Android >= 7.1 where shortcuts were introduced).

Having the terminal stay open to read some info, like your example of `termux-battery-status` can easily be done by ending the script with the `read` command, and doesn't need this message from Termux.

So my opinion is to just remove the message for Android >= 7.1, but that seems to be a controversial move. Alternatively, add an option for disabling it, or only disable it for widgets (or both).

**Comment by xeffyr** [comment] 2019-01-21 22:45
Duplicate of https://github.com/termux/termux-app/issues/56.

For the current design of Termux application thats **not possible**.

Termux offers user-manageable environment, therefore no way to predict all kinds of errors that may occur. To prevent user lock-out of his files in $HOME, we have to prevent session *auto-closing*.

Regarding widgets, you can spawn **background sessions** which are not visible. On wiki page there information how to make scripts spawn background sessions: https://wiki.termux.com/wiki/Termux:Widget.

Also, the line "[Process completed - press Enter]" will be shown only for last session. This means that you will have to press enter only when application closes.

**Comment by trygveaa** [comment] 2019-01-21 22:47
@xeffyr: This is not only an issue for background widgets. I for example have a widget for launching ssh to my irc client. After I disconnect, I would like Termux to dissapear, without having to press enter.

**Comment by xeffyr** [comment] 2019-01-21 22:50
Okay, leaving this "opened". But I'm not sure that something will change in near future.

**Comment by Deumiankio** [comment] 2019-02-08 06:50
Trygveaa's suggestion to disable it for all widgets (not just for tasks) seems to be a good compromise.
A user that has broken his shell can then still start Termux to fix the problem via the default app shortcut, while sessions started by widgets can be used for everything else.

**Comment by xeffyr** [comment] 2019-02-11 18:22
https://github.com/termux/termux-app/pull/1028

**Comment by xeffyr** [comment] 2019-04-07 19:02
So now https://github.com/termux/termux-app/pull/1028 was merged which makes sessions auto-closeable when exit core is **0** or **130**.

Those who executes scripts with Termux:Widgets can put `exit 0` to the script end to avoid need to press enter in case if something produces unwanted exit codes.

**Closed by xeffyr** 2019-04-07 19:02 UTC
Labels: duplicate, enhancement

**Comment by AsciiWolf** [comment] 2019-04-27 11:12
Please, consider implementing a different way to run the failsafe mode than the separate launcher icon. There is no way to hide the second icon on stock Android and it is really annoying to have it there. For example, stock Android and most non-stock launchers nowadays support [app shortcuts](https://developer.android.com/guide/topics/ui/shortcuts.html). Termux could move the failsafe option here.

**Comment by xeffyr** [comment] 2019-04-27 11:17
> most non-stock launchers nowadays support app shortcuts.

Even on Android 5/6 ? Perhaps not - just checked.

**Comment by xeffyr** [comment] 2019-04-27 11:19
> it is really annoying to have it there

Having a separate app for failsafe session will be okay ?

**Comment by AsciiWolf** [comment] 2019-04-27 11:48
> Having a separate app for failsafe session will be okay ?
> So icon will not be available until failsafe needed.

That sounds like a good solution to me.

**Comment by trygveaa** [comment] 2019-04-27 13:05
If it can be implemented as a separate app, I think a shortcut, plus a separate app for those not able to use shortcuts would be best.

**Comment by ChristophHeilmann** [comment] 2019-08-07 18:25
Another possibility:
decompile widget with apktool and change const-string "tasks" to const-string ".shortcuts" in TermuxWidgetProvider.smali and TermuxLaunchShortcutActivity.smali

**Comment by ChristophHeilmann** [comment] 2019-08-07 19:16
This change will skip the message [blah-blah] for scripts in the .shortcuts directory

**Comment by xeffyr** [comment] 2019-08-07 19:17
@ChristophHeilmann Issue was **already fixed** !
