### ISSUE TITLE
Coredump on running termux-open/termux-open-url from within emacs

### ISSUE THREAD

**Issue by lingnand** [termux/termux-app#315] opened 2017-05-14 11:08 UTC
I'm having this strange problem with calling `termux-open` or `termux-open-url` from within emacs.

It keeps giving the same error: `Segmentation fault (core dumped)`.

I tried to debug the core with gdb, but gdb doesn't seem to like it when I pass `termux-open` as the debug binary to it:

~~~
$ gdb $(which termux-open-url) core                     
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-android".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
"/data/data/com.termux/files/usr/bin/termux-open-url": not in executable format: File format not recognized
[New LWP 10131]
Core was generated by `app_process /system/bin com.android.commands.am.Am start --user 0 -a android.in'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000605529e5c8 in ?? ()
~~~

**Comment by lynnard** [comment] 2017-05-17 00:40
After pointing `gdb` to `/system/bin/app_process` I had some more success at seeing where it crashed:

~~~
Core was generated by `app_process /system/bin com.android.commands.am.Am --help'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000005b344ba5c8 in art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool) () from /system/lib64/libart.so
~~~

Still no idea why `libart` would crash though.

**Comment by vishalbiswas** [comment] 2017-05-17 02:11
How exactly are you running it within emacs? It shouldn't be debugging `termux-open` with follow-exec turned on.

**Comment by lynnard** [comment] 2017-05-17 08:39
I tried two ways to run it, both resulted in core dumps:

1. emacs `shell-command`: which takes a command string from the minibuffer and execute it
2. `eshell` (emac's builtin 'terminal')

**Comment by lynnard** [comment] 2017-05-17 09:02
Tried a few additional methods - all failed

1. running asynchronous command by appending `&` at end
2. use `start-process`

**Comment by Grimler91** [comment] 2017-05-17 09:35
@lynnard so for example `M-x shell-command termux-open-url https://www.termux.net` fails for you?
(It works on my arm device).

**Comment by lynnard** [comment] 2017-05-17 09:37
Yes - exactly. What's interesting is that running that command natively in termux doesn't give any hiccup.

**Comment by vishalbiswas** [comment] 2017-05-17 15:21
emacs is running termux-open through gdb. Why is that?

**Comment by lynnard** [comment] 2017-05-17 15:33
No - this is me debugging the core outside the emacs after the command finished. From emacs point of view it either silently doesn't say anything or gives me a error message along the line of 'Killed by signal ..  Segmentation fault'.

**Comment by vishalbiswas** [comment] 2017-05-17 15:44
Works for me, too. Android version and arch?

**Comment by lynnard** [comment] 2017-05-17 15:52
Android 7.1.1; arm64-v8a

**Comment by lynnard** [comment] 2017-05-19 02:13
This is reproducible on my Pixel C as well.

**Comment by vishalbiswas** [comment] 2017-05-19 02:22
Perhaps, you have tweaked emacs to behave differently? Or does it crash even without any configuration?

**Comment by lynnard** [comment] 2017-05-19 02:40
It crashes even without any configuration. I suspect it might be a Nougat issue.

**Comment by mardukbp** [comment] 2017-05-22 14:57
I have the same issue with Android 7.0 running on a Galaxy Tab S2

**Comment by lynnard** [comment] 2017-05-22 15:06
I also observed some stdin / stdout redirection 'wierdness' while running commands within emacs.

What I did is something along the line of:

```
<in an eshell>
$ cat ....  | some-program
```

The same command worked completely fine outside emacs, but for some reason when run inside emacs some lines output from `cat` are cut off at certain length.

**Comment by xeffyr** [comment] 2019-09-06 13:29
Closing. A lot things were changed since time when the issue was opened. That includes custom `/bin/am` and few more Android-specific env variables which may fixed utilities like `termux-open`.

Ask for re-open in case if not fixed in recent Termux & packages versions.

**Closed by xeffyr** 2019-09-06 13:29 UTC
Labels: bug report, help wanted
