### ISSUE TITLE
[Bug]: Android 12 When I click on the notification the app crashes

### ISSUE THREAD

**Issue by MatteoBax** [termux/termux-app#3334] opened 2023-04-08 16:35 UTC
### Problem description

When I click on the notification the app crashes
[termux-crash_report.log](https://github.com/termux/termux-app/files/11183683/termux-crash_report.log)

### Steps to reproduce the behavior.

Click on the notification

### System information

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: Oppo A53S (CPH2135)

**Comment by Paguiar735** [comment] 2023-04-18 03:28
What do you mean by "the notification"? Do you mean the Termux notification? If so, does the app just close with no error messages or does it show some error message?

In either case, does the following the steps to reproduce the behavior in your device?

01 - Open Termux app
02 - Go to Home Screen
03 - Click the Termux notification

**Comment by MatteoBax** [comment] 2023-04-18 12:45
Yes, I mean the Termux notification. I've attached the crash log in the first message and the steps to reproduce the crash are what you said.
The crash is rare.

**Comment by agnostic-apollo** [comment] 2023-04-27 00:53
You should report this to Oppo since they have modified AOSP code. AOSP would not throw that exception. I don't know if this can be fixed in termux side or what component is triggering it. Other apps on your device would be affected too.

```java
    protected void destroyHardwareResources() {
        super.destroyHardwareResources();
        int count = getChildCount();
        for (int i = 0; i < count; i++) {
            getChildAt(i).destroyHardwareResources();
        }
    }
```

https://cs.android.com/android/platform/superproject/+/android-12.0.0_r1:frameworks/base/core/java/android/view/ViewGroup.java;l=5185

```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at android.view.ViewGroup.getChildAt(ViewGroup.java:7003)
	at android.view.ViewGroup.destroyHardwareResources(ViewGroup.java:5267)
	at android.view.ViewGroup.destroyHardwareResources(ViewGroup.java:5269)
	at android.view.ViewGroup.destroyHardwareResources(ViewGroup.java:5269)
	at android.view.ViewGroup.destroyHardwareResources(ViewGroup.java:5269)
	at android.view.ViewGroup.destroyHardwareResources(ViewGroup.java:5269)
	at android.view.ViewGroup.destroyHardwareResources(ViewGroup.java:5269)
	at android.view.ThreadedRenderer.destroyResources(ThreadedRenderer.java:421)
	at android.view.ThreadedRenderer.destroyHardwareResources(ThreadedRenderer.java:416)
	at android.view.ViewRootImpl.destroyHardwareResources(ViewRootImpl.java:1401)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2821)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2305)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9133)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
	at android.view.Choreographer.doFrame(Choreographer.java:934)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Closed by agnostic-apollo** 2023-04-27 00:53 UTC
Labels: bug report
