### ISSUE TITLE
termux doesn't support samsung dex resolution resize

### ISSUE THREAD

**Issue by ceacar** [termux/termux-app#454] opened 2017-10-17 21:39 UTC
it's a fixed size window in samsung dex.

**Comment by sdrausty** [comment] 2017-10-17 22:39
Screenshot would be great.

**Comment by vzaliva** [comment] 2017-10-18 00:15
This is a duplicate of #309 which includes the screenshot and additional info.

**Comment by fornwall** [comment] 2017-11-02 20:40
Closing this in favour of #309.

**Closed by fornwall** 2017-11-02 20:40 UTC
