### ISSUE TITLE
Characters are not echoed on Samsung keyboard

### ISSUE THREAD

**Issue by Toontje** [termux/termux-app#686] opened 2018-05-17 12:56 UTC
I am using Termux on a Samsung Note8 and what annoys me is that I cannot see what I type because Termux doesn't echo the characters. Only when I type a space, a dash or similar Termux echoes what I have typed so far.
Is this a big or a wrong setting?

**Comment by Grimler91** [comment] 2018-05-17 13:25
It's likely a setting in your phone, can't remember the name of this feature though.

**Comment by Toontje** [comment] 2018-05-17 20:58
That helps! 😂

**Comment by Grimler91** [comment] 2018-05-18 17:21
Sounds like "predictive text", see this issue https://github.com/termux/termux-app/issues/126. 
I would probably turn it off in android's settings.

**Comment by pulketo** [comment] 2018-09-24 17:28
Do not use default keyboard, please download "Hacker's keyboard" from playstore

**Comment by systemsgo** [comment] 2020-01-02 02:05
This doesn't seem directly caused by predictive text.  When using most apps with predictive text, character input still appears one character at a time.  The predictive aspect only allows for autocompletion or correction.  Termux also works this way with predictive in some cases,  it only stopped working recently.  Switching keyboards doesn't do anything to address the underlying issue.

**Comment by xeffyr** [comment] 2020-01-02 10:59
> This doesn't seem directly caused by predictive text.

Not directly but still **related**. Termux can't handle word-based input. It recognizes only char-by-char input.

> The predictive aspect only allows for autocompletion or correction.

TerminalView is not a text field and keyboard knows nothing what is being typed. That causes issues with word-based input.

> Termux also works this way with predictive in some cases

We use [TYPE_NULL](https://developer.android.com/reference/android/text/InputType.html#TYPE_NULL) input type. According to SDK documents, a generic input type should be chosen in that case. Samsung keyboards behave weirdly and choose the last used input type instead.

> Switching keyboards doesn't do anything to address the underlying issue.

If keyboard assumes that [TYPE_NULL](https://developer.android.com/reference/android/text/InputType.html#TYPE_NULL) is actually last used one, that's a keyboard's bug. Not ours.

We can use
```
InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS
```
to make it work well with Samsung keyboards but that will cause some issues with others, especially ones that do special handling for passwords.

**Comment by DougLohre** [comment] 2020-01-23 02:06
> I am using Termux on a Samsung Note8 and what annoys me is that I cannot see what I type because Termux doesn't echo the characters. Only when I type a space, a dash or similar Termux echoes what I have typed so far.
> Is this a big or a wrong setting?

I'm having that problem too!  ugh!!

**Comment by quazZzar** [comment] 2020-02-11 20:26
Same problem here.
Started after I updated to the newest Android 10 and UI 2.0 ... Samsung S9+

**Comment by x2k13** [comment] 2020-02-14 18:26
Same for Samsung Galaxy Tab A 10.5 after todays Februar Update. Yesterday it worked, now it's borked

**Comment by DougLohre** [comment] 2020-02-14 20:29
I sent message about that problem to Termux personnel and I think to makers
of my phone roughly 5-6 weeks ago.  Then around 3 weeks ago I tried it
again and was relieved to see it was working fine!  Maybe they fixed the
problem in response to my and others' messages.  But it USED to always work
fine on my phone.  Now I can't even remember at what point I first noticed
that problem on this phone.  A few updates were automatically sent to my
phone over past few weeks.  Maybe one or more of them corrected the
problem.   Try sending a message describing the problem to Termux and the
makers of your phone.

**Comment by DougLohre** [comment] 2020-02-14 20:37
OOPS - In my last reply I indicated the problem was on my phone!  I forgot
the problem was on my Samsung Tab A!  So as for the message I indicated I
sent in my last reply - I sent it to Termux and Samsung. - not to makers of
my phone.

**Comment by kk-007** [comment] 2020-02-21 12:21
Same issue here in smasung galexy s9

**Comment by kk-007** [comment] 2020-02-21 12:22
> Same problem here.
> Started after I updated to the newest Android 10 and UI 2.0 ... Samsung S9+

i have also updated in s9 but issue is there it's not solved.

**Comment by mandresc** [comment] 2020-03-09 20:40
Hi,
I was having the same issue and after disabling the Predictive Text, then I exit the program and open it again and now is working fine

**Comment by drosinos** [comment] 2020-04-05 15:37
Same issue on Note 10+ (Android 10), the app is practically unusable.

**Comment by wasade** [comment] 2020-04-08 20:08
Observing this on a Samsung s10e

**Comment by ggdaynight** [comment] 2020-04-09 22:14
In JuiceSSH with the same keyboard app the issue doesn't occur, just in Termux. Sorry, but that's all I've got. I don't know what to look for to get more information about this issue.
I hope this could help go forward to fix it.

**Comment by haa-zee** [comment] 2020-04-21 18:50
I have the same issue with a Galaxy A70, since the latest update for Android 9. Before that update it worked for me with no problems even if the prediction was enabled. Currently I'm using Android 10 and this issue is active on it too.
As workaround I'm using gboard, but... I'd like to get back Samsung keyboard

**Comment by plattyfish** [comment] 2020-05-07 19:49
I had this problem on Samsung A40 , Just done an upgrade and now characters are being echoed.

**Comment by x2k13** [comment] 2020-05-07 19:57
> I had this problem on Samsung A40 , Just done an upgrade and now characters are being echoed.

So, what did you update? The keyboard app or the system firrmware?

**Comment by plattyfish** [comment] 2020-05-11 21:29
It just so happened that a prompt showed up for a phone firmware upgrade. After that was finished Termux was back to normal. Seems pretty random. The keyboard is still the default Samsung one.

**Comment by x2k13** [comment] 2020-05-27 10:26
> It just so happened that a prompt showed up for a phone firmware upgrade. After that was finished Termux was back to normal. Seems pretty random. The keyboard is still the default Samsung one.

What Android version is that firmware update? And which device?

**Comment by tathastu871** [comment] 2020-06-18 15:59
generally after installing heavy programs like texlive same keyboard problem occurs in my samsung galaxy a7 but after
if i do a fresh reinstall of termux problem got solved

so either too many programs installed might be slowing keyboard input

**Comment by xeffyr** [comment] 2020-06-18 16:08
> if i do a fresh reinstall of termux problem got solved

Enabling and then disabling [Text Input View](https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View) fixes it as well. No need to reinstall app.

> so either too many programs installed might be slowing keyboard input

Nothing to do with many installed programs (packages). They are just files. That would be a nonsense if amount of files can affect behaviour of application.

This is a bug of Samsung keyboard which doesn't respect InputType.TYPE_NULL behaviour defined by Android SDK. Instead of using generic input, Samsung keyboard enables input type that was previously used, typically with auto suggestions, auto completion & other rich input features. Termux doesn't supports them as expects char-by-char input only.

https://developer.android.com/reference/android/text/InputType#TYPE_NULL

**Comment by tathastu871** [comment] 2020-06-18 16:19
> > if i do a fresh reinstall of termux problem got solved
> 
> Enabling and then disabling [Text Input View](https://wiki.termux.com/wiki/Touch_Keyboard#Text_Input_View) fixes it as well. No need to reinstall app.
> 
> > so either too many programs installed might be slowing keyboard input
> 
> Nothing to do with many installed programs (packages). They are just files. That would be a nonsense if amount of files can affect behaviour of application.
> 
> This is a bug of Samsung keyboard which doesn't respect InputType.TYPE_NULL behaviour defined by Android SDK. Instead of using generic input, Samsung keyboard enables input type that was previously used, typically with auto suggestions, auto completion & other rich input features. Termux doesn't supports them as expects char-by-char input only.
> 
> https://developer.android.com/reference/android/text/InputType#TYPE_NULL

Complained to samsung developers hope they will repair it in future upgrades

**Comment by inmanturbo** [comment] 2020-06-23 13:09
the only thing that worked for me was disabling all predictive and auto type and auto punctuate features including auto caps after punctation. luckily they are easy to turn on and off again, however sometimes a restart after disabling is needed to get turmux working again. My life may be easier without the auto-replace! However I am going to file a bug with Samsung. They should respect the TYPE_NULL var as defined in the android sdk.

**Comment by Cr3atable** [comment] 2020-06-24 00:36
Can reproduce on S20

**Comment by jclxx** [comment] 2020-07-10 10:10
**Confirmed** on brand new **Samsung Tab A**, Android 9, with Samsung Keyboard 3.3.31.83.
Still fails after disabling Smart Typing > Predictive Text, Auto spell check, Auto capitalise, Auto punctuate.

**Successful workaround** by installing "Hacker's Keyboard" version "1.40.7 official" from Klaus Weidner, from play store.

**Termux** version 0.95.

While accepting it isn't a termux bug, it's a miserable first experience.

**Comment by zoulja** [comment] 2020-08-12 14:46
The same problem here, Honor 10, Android 10, Yandex keyboard

**Comment by batman000001** [comment] 2020-08-16 01:07
try gboard guys. it's working great on termux.

**Comment by LordMrcS** [comment] 2020-08-25 04:59
As stated by ggdaynight, JuiceSSH[](https://play.google.com/store/apps/details?id=com.sonelli.juicessh)  is working perfectly with either local android terminal and remote ssh one.

**Comment by bchristie** [comment] 2020-08-25 21:49
FWIW, Note 20 Ultra... same issue. Appears to really dislike the Samsung keyboard.

**Comment by SDRausty** [comment] 2020-08-26 13:20
https://buildapks.github.io/buildAPKs.developers.tools/ has an Android keyboard published at GitHub that builds and works in native Termux with one tap.  It does not exhibit any of the missing characters and not echoing characters as far as I can tell.  Does it work as well on Samsung?

**Comment by SDRausty** [comment] 2020-08-26 15:32
I really do not understand the moderators here at Termux!  **Do the rest of you here in this discussion thread know that you can build a functioning keyboard in Termux in one tap?  Is it relevant information to this this thread?** Why would you delete my comments like the one above in  other issues, yet only Mark the one above the spam?

**Comment by SDRausty** [comment] 2020-08-26 15:42
I really do not understand the moderators here at Termux!  Do the rest of you here in this discussion thread know that you can **build a functioning keyboard in Termux in one tap**?  Is it relevant information to this this thread? Why would you **delete my comments** like the one above in other issues here at GitHub, at Reddit and at Gitter, yet only mark the one above as spam?

**Comment by x2k13** [comment] 2020-08-26 15:44
> try gboard guys. it's working great on termux.

It does, that's true. But there are people who use features that are available on Samsung keyboard only. So using GBoard is not a real option, just a workaround - no fix for this issue.

**Comment by SDRausty** [comment] 2020-08-26 15:53
@x2k13 I had used Gboard for quite a while. Some of the features are amazing.  Others, I really did not like. It took me many many months of hard work searching and checking to see if these apps would really really build in Termux.  


As far as I  can tell many Android keyboards do build easily.  The open source keyboard that I mentioned in the comment above that is now marked as spam  in this thread builds much easier than others!   **Do you agree that  this keyboard builds easily in  a smartphone?**

**Comment by xeffyr** [comment] 2020-08-26 16:11
@SDRausty Please note that this thread is not about compiling keyboard app in Termux. If you want to suggest a keyboard to try - provide a link to Google Play or F-Droid so users can try it. But links to irrelevant repositories and web pages are *spam*. Stop advertising your repos on Termux bug tracker and I won't mark your comments as such.

Now regarding this issue: I already mentioned that possible solution will be reverting back to previous input method used by Termux:
```
InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS
```
This will explicitly reset keyboard to input method acceptable by application. @fornwall however doesn't consider this as acceptable solution.

**Comment by xeffyr** [comment] 2020-08-26 16:13
As issue exists for more than 2 years and no one submitted a proper pull request addressing this, I can make a `termux.properties` option through which you should be enable workaround by using older "visible password" input type.

**Comment by SDRausty** [comment] 2020-08-26 16:16
@xeffyr thank you for replying. The major difference between using the Play Store, and BuildAPKs to build a keyboard is, that it is easier to build this keyboard in native Termux with one tap than to use the Play Store in my opinion.  Do you agree?

**Comment by SDRausty** [comment] 2020-08-26 16:18
> Stop advertising your repos on Termux bug tracker and I won't mark your comments as such.

What is Termux bug tracker?  Can you provide a link please?

**Comment by x2k13** [comment] 2020-08-26 16:23
> As issue exists for more than 2 years and no one submitted a proper pull request addressing this, I can make a [termux.properties](https://wiki.termux.com/wiki/Terminal_Settings) option through which you should be enable workaround by using older "visible password" input type.

I had no idea this could be achieved with termux.properties, that would be great (with a bit of documentation of course). Cheers!

**Comment by xeffyr** [comment] 2020-08-26 16:28
> I had no idea this could be achieved with termux.properties, that would be great (with a bit of documentation of course).

Right now it is not available, so not documented. I guess can make a toggable workaround release it as part of Termux v0.99 either today or tomorrow.

**Comment by LordMrcS** [comment] 2020-08-26 17:44
@xeffyr tested your fix and it's working perfectly now. Thanks ! 👍

**Comment by xeffyr** [comment] 2020-08-26 18:00
Part of v0.99 release.

**Closed by xeffyr** 2020-08-26 18:00 UTC

**Comment by x2k13** [comment] 2020-08-26 20:03
> Part of v0.99 release.
> 
> APKs publishing is on @fornwall 's (Google Play) and F-Droid's responsibility.

Thank you very much, you rock!

**Comment by SDRausty** [comment] 2021-03-20 13:04
> using Termux on a Samsung Note8 and what annoys me is that I cannot see what I type because

I just got a free SAMSUNG Galaxy Android smartphone with a month long an Unlimited Internet service purchase.  I am ejnoying Termux on this smartphone greatly, with  exceptions, including the SAMSUNG keyboard.  

As I have known about this issue for years, I took the time to create and publish my latest resolution to this resolved issue at https://buildapks.github.io/buildAPKs.keyboards/ Thank you to all who have made this project come true;  Please enjoy the piano!

**Comment by topongo** [comment] 2021-07-17 10:49
> @xeffyr tested your fix and it's working perfectly now. Thanks ! 👍 
> 
> ```
>  cd ~
>  mkdir .termux
>  echo "enforce-char-based-input=true" > .termux/termux.properties
>  termux-reload-settings
> ```

I'm having the same behavior described initially with the Gboard keyboard, but even modifying `~/.termux/termux.properties` enabling and disabling `enforce-char-based-input` I don't get any result. Either cases gboard is still in text input type and not password input type.

**Comment by agnostic-apollo** [comment] 2021-07-17 18:18
> I don't get any result.

Restart Termux after enabling it for changes to take effect.
