### ISSUE TITLE
Cursor color defaults

### ISSUE THREAD

**Issue by mklein994** [termux/termux-app#219] opened 2016-12-26 22:19 UTC
Could there be an option so that if `~/.termux/colors.properties` doesn't specify a cursor color, it could use the reverse of whatever text color and background color it's on instead? As of now it defaults to hex color a9aaa9. (I believe it was introduced in commit 9fe0e494734cf30484c2af14df012c128515f030).

**Comment by BohrShaw** [comment] 2017-01-11 12:22
The cursor foreground color is now the foreground color of the text under cursor, which makes the text under cursor indistinguishable. It's really a bug I consider.

**Comment by BohrShaw** [comment] 2017-01-13 13:45
@mklein994 How to change the cursor color? I failed to find the relevant info about `~/.termux/colors.properties`.

**Comment by mklein994** [comment] 2017-01-13 15:30
@BohrShaw a good example is the Wild Cherry theme as of Termux:Styling version 0.15. (e4166fadbe9fa089b6b08dde5a6f4bc7bf111a3c)

**Comment by BohrShaw** [comment] 2017-01-14 05:18
Thanks.
Is there a way to set cursor foreground color?

**Comment by dessalines** [comment] 2022-03-08 02:14
The cursor color also seems to follow the system theme, which is incorrect, it should follow the color.properties. The cursor isn't readable when the system is in dark mode, while using a dark theme for example.

**Comment by sunkrop** [comment] 2022-11-15 22:29
No updates on the issue? Is it possible to set cursor color in config?

**Comment by TomJo2000** [comment] 2022-11-15 22:37
You can set it in `~/.termux/colors.properties` manually.

**Comment by agnostic-apollo** [comment] 2022-11-15 23:01
Was closed by 26ff978b, will be available in next release. Use github action builds if  you want it now.

**Closed by agnostic-apollo** 2022-11-15 23:01 UTC
Labels: enhancement

**Comment by sunkrop** [comment] 2022-11-15 23:06
@TomJo2000 I do not have `~/.termux/colors.properties` in `termux-app`. `termux-styling` should be installed? This build - https://github.com/termux/termux-styling/actions/runs/3406907267 - can be used?

@agnostic-apollo Thanks

**Comment by agnostic-apollo** [comment] 2022-11-15 23:10
The `termux-styling` app just writes to `color.properties` file, which is read by `termux-app`. You can manually modify the file without `termux-styling` being installed.

No, you need build of `termux-app`, commit was done in it. And if you installed apps from F-Droid, you would need to reinstall all apps.

https://github.com/termux/termux-app#installation

Welcome.

**Comment by sunkrop** [comment] 2022-11-15 23:17
I understand. What template I can use for manual creation `color.properties` file in my current installation? I tried to find this files in `termux-app` and `termux-styling` repositories but have not succeeded.

**Comment by agnostic-apollo** [comment] 2022-11-15 23:18
https://github.com/termux/termux-styling/tree/master/app/src/main/assets/colors

**Comment by TomJo2000** [comment] 2022-11-15 23:52
You'll need to reload the settings with
`termux-reload-settings`
for the changes to apply.

**Comment by sunkrop** [comment] 2022-11-16 00:02
@TomJo2000 Checked with `cursor=#090300` (black color), `termux-reload-settings`, and Termux restart. Nothing is changed.
May be `color.properties` file name/path should be set somewhere in another Termux config?

**Comment by agnostic-apollo** [comment] 2022-11-16 00:08
Did you set it in `~/.termux/colors.properties`?

**Comment by agnostic-apollo** [comment] 2022-11-16 00:13
As for issues reported by @dessalines about dark mode, possibly https://github.com/termux/termux-app/issues/3036#issuecomment-1273430688 may be the issue, xiaomi rom messes with colors and toggles in  `Settings > Display > Color scheme > More Dark Mode options` should be disabled.

**Comment by sunkrop** [comment] 2022-11-16 00:14
As @dessalines wrote:

> The cursor color also seems to follow the system theme, which is incorrect, it should follow the color.properties. The cursor isn't readable when the system is in dark mode, while using a dark theme for example.

So it seems the work around is not working. Someone tested this issue on the fresh Termux build? Cursor is visible on the dark system theme? Is it worth trying to upgrade?

**Comment by agnostic-apollo** [comment] 2022-11-16 01:08
The 26ff978 workaround isn't related to dark mode issues, only for cases where cursor prop is missing and text isn't visible due to cursor defaulting to white even with light background.

Termux does not use system colors for cursor, whether in light or dark mode, only cursor prop value. Issue for cursor color not working in dark mode was not reproducible by me and was discussed in #2653 and apparently got fixed by reinstall, but likely related to xiaomi os messing colors. You may want to force stop termux app after changing system settings.

Welcome.
