### ISSUE TITLE
Critical bug!

### ISSUE THREAD

**Issue by aristarh2704** [termux/termux-app#679] opened 2018-05-06 20:35 UTC
When I compiled musl libc and copyed libc.so to (termux-root)/usr/lib, all executables don't work. And I cann't run termux shell. It's bad, that executables search libraries first in self root, not in system root

**Comment by xeffyr** [comment] 2018-05-06 20:55
> When I compiled musl libc and copyed libc.so to (termux-root)/usr/lib, all executables don't work. And I cann't run termux shell. It's bad, that executables search libraries first in self root, not in system root

**This is not a bug.**
Bionic and musl libc have different ABI and this is causes errors.
If you want to use a musl libc, you have to recompile all programs in termux-root with linking against musl libc. Not sure, but you may need to adjust path to linker if you use shared libraries.

**Comment by aristarh2704** [comment] 2018-05-06 21:34
But I can brick termux by simple command: "touch ~/../usr/lib/libc.so"
It's need add "/system/lib" to LD_LIBRARY_PATH by default

**Comment by Grimler91** [comment] 2018-05-07 06:10
I don't see why you expect it to work. (Re)placing a libc on a normal linux system surely causes problems as well unless done correctly.

If you want to use musl libc for compiling some project then place it in some other folder and change the build environment to make your project aware of it.

Closing this as it isn't really a bug as @xeffyr put it.

(Real problem here is perhaps that $PREFIX/lib is writeable for normal user)

**Closed by Grimler91** 2018-05-07 06:10 UTC
