### ISSUE TITLE
[Bug]: DELETE key issue with Fleksy keyboard

### ISSUE THREAD

**Issue by RExtafa** [termux/termux-app#2313] opened 2021-10-03 12:32 UTC
### Problem description

I got an old issue with `Fleksy` keyboard, from Termux Google play 0.101 up until 0.117. not sure if it's worthy to be a bug.
My request is simple question is this termux issue or keyboard issue. 

shortly, i have a keyboard named "Fleksy" and one named Samsung, the Samsung one doesn't move cursor when swiping on spacebar(known) but Fleksy one does, the Fleksy one is not broken like Samsung one And does Not need to enable workaround of `termux.properties`, But has a delete issue, 
please see the the video fully I'll attach to get the issue faster,
is this a bug, or is it not?
Thanks for the great app and hard work

VIDEO:
https://user-images.githubusercontent.com/60977925/135753589-9fa73093-c8cc-46d3-8814-da0f669d9973.mp4

### Steps to reproduce the behavior.

Not much to reproduce, just get the keyboard, Type, swipe the keyboard to left and try to delete what you typed.
(in video i swipe the field and it breaks the `delete` key, but even `arrow up` breaks it after some tries.)

### What is the expected behavior?

delete the input.

### System information

* **Termux application version**: `0.101` - `0.117`
* **Android OS version**: `10`
* **MANUFACTURER**: `samsung`  
* **BRAND**: `samsung`  
* **MODEL**: `SM-J600F`  
* **PRODUCT**: `j6ltecis`  
* **BOARD**: `exynos7870`  
* **HARDWARE**: `samsungexynos7870`  
* **DEVICE**: `j6lte`  
* **SUPPORTED_ABIS**: `armeabi-v7a, armeabi`

**Comment by xeffyr** [comment] 2021-10-03 12:39
Is `delete` working when you have workaround in termux.properties enabled? Seems more like keyboard input type issue. Reminding that Termux doesn't support rich features that require a word-based input (prediction, correction, word selection, etc).

**Comment by agnostic-apollo** [comment] 2021-10-03 13:24
1. Exit the termux app and start it up again.
2. Go to termux settings and enable `Terminal View Key Logging`.
3. Run `logcat` command and then keep pressing `delete` key and see if `KEYCODE_DEL` is being logged and is equal to the number of times you press the `delete` key. If its not for `Fleksy`, then its most likely the keyboard issue since its not sending the event. If it is, then set log level to `Verbose` in termux settings and reproduce the issue while typing some text and deleting it until it fails and then run `logcat -d > ~/log` command and send the file.

**Comment by RExtafa** [comment] 2021-10-03 19:20
@xeffyr 
> Is delete working when you have workaround in termux.properties enabled?

yes in both ways it doesn't work. but i guess we reached a conclusion

@agnostic-apollo 

>equal to the number of times you press the `delete` key.

i did so and used logcat | grep keyCode=KEYCODE_DEL 

and with Fleksy gets stuck at random count for example i hit delete 1-12 times in a row all good on 13th No more logs, then when i hit enter key and then Delete it starts to log again but up to 4 registers. when i try with normal text i can delete 12+ chars normally(unless i pull the field of writing it gets stuck as if has seen Medusa)

i guess by your words this confirms that it somehow is keyboard is drunk and has issues, should i close this issue if i understood you right

--
also as a side question when i use vtshowkeys the stdin  can see the text why isn't it registering it as Key Del, and doing so with Samsung keyboard.

I'll leave it like this, as a workaround what is the `BACKSPACE` or `DELETE` value for `properties` file if there is any, I'll use those everytime it gets stuck.
Thanks for your time

**Comment by agnostic-apollo** [comment] 2021-10-03 20:17
>i guess by your words this confirms that it somehow is keyboard is drunk and has issues

Yeah, seems to be a keyboard issue. The terminal view and text input view [switch between](https://github.com/termux/termux-app/blob/dcedf394343f97284359f33a52e264089a335751/terminal-view/src/main/java/com/termux/view/TerminalView.java#L269) `InputType.TYPE_NULL` and `InputType.TYPE_CLASS_TEXT`, maybe that causes the issue somehow.

>also as a side question when i use vtshowkeys the stdin can see the text why isn't it registering it as Key Del,

It should show for <= 12. Events are first received by termux and then sent to terminal/vtshowkeys.

>as a workaround

You should use [`BACKSPACE`](https://github.com/termux/termux-app/blob/e7d06aebb59948730f32a2a251eb61f6a36281ad/termux-shared/src/main/java/com/termux/shared/terminal/io/extrakeys/ExtraKeysConstants.java#L28) for `KEYCODE_DEL`. `DEL` sends `KEYCODE_FORWARD_DEL` instead.

Closing for now. Can be opened again if proof is shown that this is being caused by termux.

**Closed by agnostic-apollo** 2021-10-03 20:17 UTC
Labels: bug report
