### ISSUE TITLE
[Bug]: Pillow fails to install on latest python 3.10

### ISSUE THREAD

**Issue by mishailovic** [termux/termux-app#2396] opened 2021-11-18 13:32 UTC
### Problem description

When I am trying to install Pillow package from pypi, it fails with these errors: https://pastebin.com/raw/TYzpV7A7

### Steps to reproduce the behavior.

Download and install latest termux .apk from f-droid, and paste the following command in it: pkg install libjpeg-turbo python && LDFLAGS="-L/system/lib/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install Pillow

### What is the expected behavior?

Successful installation of Pillow package

### System information

* Termux application version: 0.117 (117)
* Android OS version: 11 
* Device model: POCO X3 Pro

**Comment by Grimler91** [comment] 2021-11-19 13:15
Duplicate of https://github.com/termux/termux-packages/issues/7861, or maybe due to outdated packages

**Closed by Grimler91** 2021-11-19 13:15 UTC
Labels: bug report
