### ISSUE TITLE
Segmentation Fault on kotlinc [Bug]: 

### ISSUE THREAD

**Issue by animeshxd** [termux/termux-app#2841] opened 2022-06-16 18:21 UTC
### Problem description

```
.../usr/tmp $ kotlinc test.kt
/data/data/com.termux/files/usr/bin/kotlinc: line 98: 11807 Segmentation fault      "${JAVACMD:=java}" $JAVA_OPTS "${java_args[@]}" -cp "${kotlin_app[@]}" "${kotlin_args[@]}"
```

I have tried to compile a simple hello world program just to test kotlin on termux

```kt
fun main(args: Array<String>) {
    println("Hello, World!")
}
```
`Kotlin version 1.7.0-release-281 (JRE 17-internal+0-adhoc..src)`

### Steps to reproduce the behavior.

1. try to compile a simple program with kotlinc
2. It will show error

### What is the expected behavior?

compiled kotlin program successfully 

### System information

* Termux application version: 0.118.0
* Android OS version: 12 
* Device model: RMX2193
* Kotlin version: Kotlin version 1.7.0-release-281 (JRE 17-internal+0-adhoc..src)

**Comment by Grimler91** [comment] 2022-06-16 19:54
Duplicate of https://github.com/termux/termux-packages/issues/10851

**Closed by Grimler91** 2022-06-16 19:54 UTC
Labels: bug report

**Comment by tempaccforissue** [comment] 2022-06-24 06:50
> I have tried to compile a simple hello world program just to test kotlin on termux

do you also have the maven package installed in Termux? if so, and now if you do not it maven, try after removing maven..

**Comment by animeshxd** [comment] 2022-06-24 07:13
Yes, maven is installed, 
After removing maven and deleting ~/. m2 
it shows 
```
.../files/x $ kotlinc test.kt  
/data/data/com.termux/files/usr/bin/kotlinc: line 98: 24253 Segmentation fault      "${JAVACMD:=java}" $JAVA_OPTS "${java_args[@]}" -cp "${kotlin_app[@]}" "${kotlin_args[@]}"

```

after removing dependent libjansi It worked :)

but maven is more important to me :(
