### ISSUE TITLE
[Bug]: Uhh.. What is dzsh?

### ISSUE THREAD

**Issue by turbomaster95** [termux/termux-app#2599] opened 2022-02-17 06:42 UTC
### Problem description

I was just using Termux and I typed a wrong command (I was using zsh and ohmyzsh)
And the command not found said dzsh: command not found

### Steps to reproduce the behavior.

I don't know

### What is the expected behavior?

This is expected
![Screenshot_2022-02-17-12-06-38-483](https://user-images.githubusercontent.com/86113389/154419846-f38abbb7-e7d7-46a6-bbca-d5150642d425.jpeg)

### System information

* Termux application version: Play Store Version
* Android OS version: 10
* Device model: Lenovo TB-8705X

**Comment by wmcbtech30** [comment] 2022-02-17 07:24
Could you explain what's this `dzsh`? there's no such command and what are you trying to achieve?

**Comment by SDRausty** [comment] 2022-02-17 07:59
> Uhh.. What is dzsh?

```
~ $ dzsh
No command dzsh found, did you mean:
 Command dash in package dash
 Command zsh in package zsh
```

**Comment by turbomaster95** [comment] 2022-02-17 08:02
Well I can not reproduce the issue

**Comment by SDRausty** [comment] 2022-02-17 08:05
@wmcbtech30 would close issue

admin issues request please

**Comment by wmcbtech30** [comment] 2022-02-17 08:15
i'm not sure what the user wants or trying to achieve

**Comment by UnknownErrror** [comment] 2022-02-17 08:24
He is accidently typed `d` after `Enter` while cursor was on the start of line
So when `zsh: command not found: ...` was printed, there was `d` on the line and result is `dzsh: command not found: ...`

**Comment by wmcbtech30** [comment] 2022-02-17 08:25
i wasn't able to reproduce this exactly but maybe a video would be helpful

**Comment by SDRausty** [comment] 2022-02-17 08:35
> video would be helpful

published from @github plz

**Comment by UnknownErrror** [comment] 2022-02-17 08:39
```
$ irirkdkd
dirirkdkd: command not found
$ d
```
https://user-images.githubusercontent.com/30185766/154436895-4e618139-c49f-49fd-a71b-71fa307f4bfb.mp4

**Comment by SDRausty** [comment] 2022-02-17 08:42
>So when `zsh: command not found`

try `pkg i zsh`

then rerun your command

**Comment by wmcbtech30** [comment] 2022-02-17 08:43
> ```
> $ irirkdkd
> dirirkdkd: command not found
> $ d
> ```
> 
>  VID_20220217113316.mp4

On the video it shows a d keypress as soon Enter key invoked, i'll reopen this issue as needs more verification of this problem

**Comment by agnostic-apollo** [comment] 2022-02-17 08:53
Try setting `enforce-char-based-input=true` in `~/.termux/termux.properties`

**Comment by UnknownErrror** [comment] 2022-02-17 09:35
This is intended behaviour.
Run `sleep 10 && echo Hi.` and type something, after 10 seconds `Hi.` will be appended to what you typed

This works like that on all terminals, not only Termux

**Comment by Nerd00F** [comment] 2022-02-20 13:20
You tried deleting and installing it again?

**Comment by Nerd00F** [comment] 2022-03-30 20:14
So this "bug" is expected behavior, what do you think about closing this issue @agnostic-apollo ?

**Comment by agnostic-apollo** [comment] 2022-03-30 20:18
Yeah, OP is non responsive too.

**Closed by agnostic-apollo** 2022-03-30 20:18 UTC
