### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by alwzfolwd** [termux/termux-app#2580] opened 2022-02-10 02:56 UTC
### Problem description

termux-setup-storage does nothing, storage is still unavailable.

### Steps to reproduce the behavior.

termux-setup-storage

### What is the expected behavior?

Mobile device home folder and others available.

### System information

* Termux application version:0.95
* Android OS version:11
* Device model:galaxy tab a7 sm-t500

**Comment by agnostic-apollo** [comment] 2022-02-10 04:32
Firstly, we don't provide support for such an old version of termux. Update to latest or at least recent version and then test.

https://github.com/termux/termux-app#installation

Secondly, you have posted no transcript for commands you ran and no info about how you are validating that directories don't exist. Post transcript, with both output of `termux-setup-storage` and `ls ~/storage` output.

You should also check https://wiki.termux.com/wiki/Termux-setup-storage.

I would also advise you to grant draw over apps permission to termux, some devices have issues with termux app receiving intents, so that may be an issue. But that permission wasn't requested by termux app in such an old version, so you will need to update to be able to grant it.

Closing since no title, using old version, provided no info or proof that issue is with termux, specially considering others would reported too. I have also confirmed that its working on android 11. Issue can be reopened if proof is provided.

**Closed by agnostic-apollo** 2022-02-10 04:32 UTC
Labels: bug report

**Comment by wmcbtech30** [comment] 2022-02-10 05:17
> ### Problem description
> termux-setup-storage does nothing, storage is still unavailable.
> 
> ### Steps to reproduce the behavior.
> termux-setup-storage
> 
> ### What is the expected behavior?
> Mobile device home folder and others available.
> 
> ### System information
> * Termux application version:0.95
> * Android OS version:11
> * Device model:galaxy tab a7 sm-t500

Revoke storage permission in app settings and grant it again

**Comment by agnostic-apollo** [comment] 2022-02-10 12:27
>storage is still unavailable.
>Mobile device home folder and others available.

@wmcbtech30 above implies that storage symlinks are not available and not a permission denied issue.
