### ISSUE TITLE
[Feature]: Respect XDG Base Directory Specification

### ISSUE THREAD

**Issue by avidseeker** [termux/termux-app#3434] opened 2023-06-02 23:08 UTC
### Feature description

[XDG specifies](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) the location a program should use for storing config, data, and cache files.

### Additional information

Move `~/.termux` to `$XDG_CONFIG_HOME/termux`.

**Comment by 2096779623** [comment] 2023-06-02 23:12
Duplicate of https://github.com/termux/termux-app/issues/2826 .

**Closed by 2096779623** 2023-06-02 23:12 UTC
