### ISSUE TITLE
Wine

### ISSUE THREAD

**Issue by vc5K** [termux/termux-app#1024] opened 2019-02-10 12:29 UTC
```bash
 -  wine-stable SPRViewer.exe
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
0009:err:process:create_process L"Z:\\root\\SPRViewer.exe" not supported on this installation (x86 binary)
wine: Bad EXE format for Z:\root\SPRViewer.exe. 
```
If I install wine32 can I running the program ?
And how to install it

**Comment by xeffyr** [comment] 2019-02-10 12:37
**Wine is not supported for now.**
*Duplicate of https://github.com/termux/termux-packages/issues/1423.*

***

> If I install wine32 can I running the program ?

Wine can run only programs compiled for same architecture that wine. So, for example if your wine installation is AArch64, then you can run only AArch64 EXEs - forget about pc/x86 in this case.

That's why you get:
```
0009:err:process:create_process L"Z:\\root\\SPRViewer.exe" not supported on this installation (x86 binary)
wine: Bad EXE format for Z:\root\SPRViewer.exe.
```

Wine is not emulator but only compatibility layer.

Closing as **offtopic** since wine is not supported in Termux.

**Closed by xeffyr** 2019-02-10 12:37 UTC
