### ISSUE TITLE
The keyboard automatically exits

### ISSUE THREAD

**Issue by GitHubNeko** [termux/termux-app#2110] opened 2021-06-05 10:55 UTC
Termux Version：0.103
But when I swipe to the left, the keyboard automatically exits. How can I disable it so that the keyboard is always displayed?
![Screenshot_20210605_185148_com termux](https://user-images.githubusercontent.com/83487691/120889420-890c9d80-c62f-11eb-85b9-162b7cb18624.jpg)

**Comment by agnostic-apollo** [comment] 2021-06-05 11:24
Duplicate of #2077. Will be fixed in next release.

**Closed by agnostic-apollo** 2021-06-05 11:24 UTC
