### ISSUE TITLE
[Bug]: CRITICAL - Termux random SHELL exit while in use

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-app#2524] opened 2022-01-13 00:54 UTC
### Problem description

Termux updated to 0.118 and API updated to 0.50.1 this AM (EST)

Installed latest version of my dextop project after some changes and rebasing.

Noticed that while running apt under proot (Ubuntu 21.10 arm64) and doing some heavy package operations (i.e.: installing build essentials or reinstalling papirus-icon-theme) the process would hang and never finish...

When going back to the Termux window, the Shell has aborted and shows the logout/exit message 
ˋˋˋ
[Process completed (signal 9) - press Enter]
ˋˋˋ

Checking 'ps aux' after reopening shows that all processes are still active and running (vnc, proot, and even the apt/dpkg processes that were hanging in the proot container...)

### Steps to reproduce the behavior.

create a fresh termux install/session
create proot-distro using ubuntu 21.10 image (direct download or termux tar)
install xfce4 (complete: yes | apt-get install xfce4* tigervnc*)
start vnc server for proot container and run an apt/dpkg intensive operation... ( [sudo] apt-get install --reinstall papirus-icon-theme )

### What is the expected behavior?

Previous builds, although buggy, never exhibited any such behavior. Processes should continue normally and termux should remain open and not force contained processes to hang or abort.

### System information

* Termux application version:
* Android OS version:
* Device model:
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24 stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.19.113-23222000 #1 SMP PREEMPT Tue Dec 21 22:00:06 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T970

**Comment by nathaneltitane** [comment] 2022-01-13 00:56
![Screenshot_20220112-195053_Termux](https://user-images.githubusercontent.com/5674757/149246709-820e188b-5dfe-40d5-b68a-7329dbb7a8be.png)

**Comment by agnostic-apollo** [comment] 2022-01-13 02:11
Duplicate of #2366

**Closed by agnostic-apollo** 2022-01-13 02:11 UTC
Labels: bug report

**Comment by nathaneltitane** [comment] 2022-01-13 03:11
thanks @agnostic-apollo , sorry for joining late on the bandwagon.

Another relative issue that ought to be of interest: Termux 0.118 does not seem to be available to add to 'never sleeping apps'

Although, when going into the app's battery usage details, I am able to set it to unrestricted I.e.: telling Android to use all the battery, all the time... having read your issue manifest, that also seems to be a way to avoid termux being kicked, correct?

**Comment by krisdowis** [comment] 2022-08-06 09:36
> thanks @agnostic-apollo , sorry for joining late on the bandwagon.
> 
> Another relative issue that ought to be of interest: Termux 0.118 does not seem to be available to add to 'never sleeping apps'
> 
> Although, when going into the app's battery usage details, I am able to set it to unrestricted I.e.: telling Android to use all the battery, all the time... having read your issue manifest, that also seems to be a way to avoid termux being kicked, correct?

yes, correct
