### ISSUE TITLE
Can't pkg update && pkg upgrade

### ISSUE THREAD

**Issue by lexus55** [termux/termux-app#1060] opened 2019-03-12 02:47 UTC
Help me...
I can't do pkg update && pkg upgrade
This is the result

$ pkg update && pkg upgrade
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
$

**Comment by xeffyr** [comment] 2019-03-12 08:02
Duplicate of https://github.com/termux/termux-packages/issues/3502 ? Okay, closing...

**Closed by xeffyr** 2019-03-12 08:02 UTC
