### ISSUE TITLE
No keep  current screen 

### ISSUE THREAD

**Issue by cDQK** [termux/termux-app#1245] opened 2019-09-11 12:47 UTC
Like ffmpeg running output, sliding the screen and always beating to the latest output, I hope it shows the old output display

**Comment by RlZkhere** [comment] 2019-09-26 05:47
If you dont' have set DISPLAY:=* option , it's normale that you find this errore , set DISPLAY and relaunch

**Comment by RlZkhere** [comment] 2019-09-26 05:47
If you dont' have set DISPLAY:=* option , it's normale that you find this errore , set DISPLAY and relaunch

**Comment by fornwall** [comment] 2019-11-03 22:29
Closing as duplicate of #1242.

**Closed by fornwall** 2019-11-03 22:29 UTC
