### ISSUE TITLE
alignment for hebrew letters

### ISSUE THREAD

**Issue by giuliolunati** [termux/termux-app#1256] opened 2019-09-20 23:03 UTC
**Problem description**
`echo ב`
produce a ב letter right aligned
same for ק and ע
while other letters are left aligned
`echo בא`
produce an א  at the left, a large gap, then a ב at the right

**Expected behavior**
All the letters left aligned

**Additional information**
Updatable packages:
apt/stable 1.4.9-15 aarch64 [upgradable from: 1.4.9-11]
aterm/x11 1.0.1-13 aarch64 [upgradable from: 1.0.1-11]
bash/stable 5.0.11 aarch64 [upgradable from: 5.0.7-2]
busybox/stable 1.30.1-9 aarch64 [upgradable from: 1.30.1-2]
ca-certificates/stable 20190828 all [upgradable from: 20190515]
cmus/stable 2.8.0-4 aarch64 [upgradable from: 2.8.0-3]
command-not-found/stable 1.39 aarch64 [upgradable from: 1.38]
curl/stable 7.66.0 aarch64 [upgradable from: 7.65.3]
dash/stable 0.5.10.2-2 aarch64 [upgradable from: 0.5.10.2-1]
diffutils/stable 3.7-2 aarch64 [upgradable from: 3.7-1]
dpkg/stable 1.19.7-9 aarch64 [upgradable from: 1.19.7]
ecj/stable 4.12-2 all [upgradable from: 4.7.2-3]
ffmpeg/stable 4.2.1 aarch64 [upgradable from: 4.1.4-1]
file/stable 5.37-1 aarch64 [upgradable from: 5.37]
findutils/stable 4.7.0 aarch64 [upgradable from: 4.6.0-3]
fontconfig/stable 2.13.1-4 aarch64 [upgradable from: 2.13.1-3]
fontconfig-utils/stable 2.13.1-4 aarch64 [upgradable from: 2.13.1-3]
freetype/stable 2.10.1-1 aarch64 [upgradable from: 2.10.1]
fribidi/stable 1.0.5-1 aarch64 [upgradable from: 1.0.5]
gawk/stable 5.0.1-4 aarch64 [upgradable from: 5.0.1]
git/stable 2.23.0 aarch64 [upgradable from: 2.22.0]
glib/stable 2.60.7 aarch64 [upgradable from: 2.60.5]
grep/stable 3.3-2 aarch64 [upgradable from: 3.3-1]
harfbuzz/stable 2.6.1 aarch64 [upgradable from: 2.5.3]
harfbuzz-icu/stable 2.6.1 aarch64 [upgradable from: 2.5.3]
krb5/stable 1.17-1 aarch64 [upgradable from: 1.16.3-1]
ldns/stable 1.7.1-1 aarch64 [upgradable from: 1.7.0-5]
less/stable 551-1 aarch64 [upgradable from: 551]
libandroid-glob/stable 0.6 aarch64 [upgradable from: 0.4]
libandroid-support/stable 25-2 aarch64 [upgradable from: 25]
libarchive/stable 3.4.0-1 aarch64 [upgradable from: 3.4.0]
libass/stable 0.14.0-1 aarch64 [upgradable from: 0.14.0]
libassuan/stable 2.5.3-1 aarch64 [upgradable from: 2.5.3]
libbz2/stable 1.0.8-5 aarch64 [upgradable from: 1.0.8]
libcaca/stable 0.99.beta19-6 aarch64 [upgradable from: 0.99.beta19-5]
libcairo/stable 1.16.0-2 aarch64 [upgradable from: 1.16.0-1]
libcrypt/stable 0.2-2 aarch64 [upgradable from: 0.2-1]
libcurl/stable 7.66.0 aarch64 [upgradable from: 7.65.3]
libdb/stable 18.1.32-3 aarch64 [upgradable from: 18.1.32-1]
libedit/stable 20190324-3.1-1 aarch64 [upgradable from: 20190324-3.1-0]
libevent/stable 2.1.11-1 aarch64 [upgradable from: 2.1.10]
libexpat/stable 2.2.8 aarch64 [upgradable from: 2.2.7]
libffi/stable 3.2.1-4 aarch64 [upgradable from: 3.2.1-3]
libflac/stable 1.3.3 aarch64 [upgradable from: 1.3.2-9]
libfontenc/x11 1.1.4-3 aarch64 [upgradable from: 1.1.4-1]
libgcrypt/stable 1.8.5 aarch64 [upgradable from: 1.8.4]
libgd/stable 2.2.5-6 aarch64 [upgradable from: 2.2.5-4]
libgmp/stable 6.1.2-4 aarch64 [upgradable from: 6.1.2-2]
libgnutls/stable 3.6.9-1 aarch64 [upgradable from: 3.6.8-1]
libgpg-error/stable 1.36-1 aarch64 [upgradable from: 1.36]
libgraphite/stable 1.3.13-3 aarch64 [upgradable from: 1.3.13-2]
libice/x11 1.0.10-2 aarch64 [upgradable from: 1.0.10]
libiconv/stable 1.16-3 aarch64 [upgradable from: 1.16-1]
libicu/stable 64.2-3 aarch64 [upgradable from: 64.2-2]
libid3tag/stable 0.15.1b-3 aarch64 [upgradable from: 0.15.1b-2]
libidn2/stable 2.2.0-1 aarch64 [upgradable from: 2.2.0]
libjpeg-turbo/stable 2.0.3 aarch64 [upgradable from: 2.0.2-4]
libksba/stable 1.3.5-2 aarch64 [upgradable from: 1.3.5-1]
libltdl/stable 2.4.6-7 aarch64 [upgradable from: 2.4.6-6]
liblua/stable 5.3.5-4 aarch64 [upgradable from: 5.3.5-3]
liblua52/stable 5.2.4-4 aarch64 [upgradable from: 5.2.4-3]
liblzma/stable 5.2.4-7 aarch64 [upgradable from: 5.2.4-2]
libmad/stable 0.15.1b-2 aarch64 [upgradable from: 0.15.1b-1]
libmp3lame/stable 3.100-2 aarch64 [upgradable from: 3.100]
libmpfr/stable 4.0.2-2 aarch64 [upgradable from: 4.0.2-1]
libnettle/stable 3.5.1-2 aarch64 [upgradable from: 3.5.1-1]
libnghttp2/stable 1.39.2 aarch64 [upgradable from: 1.39.1]
libnpth/stable 1.6-1 aarch64 [upgradable from: 1.6]
libogg/stable 1.3.4 aarch64 [upgradable from: 1.3.3]
libopus/stable 1.3.1-3 aarch64 [upgradable from: 1.3.1-1]
libpcap/stable 1.9.0-1 aarch64 [upgradable from: 1.9.0]
libpixman/stable 0.38.4-2 aarch64 [upgradable from: 0.38.4-1]
libpng/stable 1.6.37-2 aarch64 [upgradable from: 1.6.37-1]
libpopt/stable 1.16-3 aarch64 [upgradable from: 1.16-2]
libpulseaudio/stable 12.2-21 aarch64 [upgradable from: 12.2-19]
libsm/x11 1.2.3-6 aarch64 [upgradable from: 1.2.3-4]
libsndfile/stable 1.0.29~pre1-3 aarch64 [upgradable from: 1.0.29~pre1-2]
libsoxr/stable 0.1.3-2 aarch64 [upgradable from: 0.1.3-1]
libsqlite/stable 3.29.0-1 aarch64 [upgradable from: 3.29.0]
libssh2/stable 1.9.0-1 aarch64 [upgradable from: 1.9.0]
libtiff/stable 4.0.10-10 aarch64 [upgradable from: 4.0.10-7]
libtool/stable 2.4.6-7 aarch64 [upgradable from: 2.4.6-6]
libunistring/stable 0.9.10-3 aarch64 [upgradable from: 0.9.10-2]
libuuid/stable 1.0.3-3 aarch64 [upgradable from: 1.0.3-2]
libvorbis/stable 1.3.6-2 aarch64 [upgradable from: 1.3.6-1]
libvpx/stable 1.8.1-1 aarch64 [upgradable from: 1.8.0-2]
libwebp/stable 1.0.3-1 aarch64 [upgradable from: 1.0.3]
libx11/x11 1.6.8-3 aarch64 [upgradable from: 1.6.8]
libx264/stable 20190215-1 aarch64 [upgradable from: 20190215]
libx265/stable 3.1.2 aarch64 [upgradable from: 3.1.1]
libxau/x11 1.0.9-4 aarch64 [upgradable from: 1.0.9-2]
libxcb/x11 1.13.1-5 aarch64 [upgradable from: 1.13.1-3]
libxdmcp/x11 1.1.3-4 aarch64 [upgradable from: 1.1.3-2]
libxext/x11 1.3.4-3 aarch64 [upgradable from: 1.3.4-1]
libxml2/stable 2.9.9-6 aarch64 [upgradable from: 2.9.9-5]
libxmu/x11 1.1.3-4 aarch64 [upgradable from: 1.1.3-2]
libxt/x11 1.2.0-3 aarch64 [upgradable from: 1.2.0-1]
libzopfli/stable 1.0.2-5 aarch64 [upgradable from: 1.0.2-4]
littlecms/stable 2.9-2 aarch64 [upgradable from: 2.9-1]
m4/stable 1.4.18-2 aarch64 [upgradable from: 1.4.18-1]
mpv/stable 0.29.1-9 aarch64 [upgradable from: 0.29.1-7]
ncurses/stable 6.1.20190511-7 aarch64 [upgradable from: 6.1.20190511-3]
netcat/stable 7.80 aarch64 [upgradable from: 7.70-6]
nmap/stable 7.80 aarch64 [upgradable from: 7.70-6]
openal-soft/stable 1.19.1-1 aarch64 [upgradable from: 1.18.2-2]
openjpeg/stable 2.3.1-2 aarch64 [upgradable from: 2.3.1-1]
openssh/stable 8.0p1-5 aarch64 [upgradable from: 8.0p1-1]
openssl/stable 1.1.1d aarch64 [upgradable from: 1.1.1c-1]
opusfile/stable 0.11-2 aarch64 [upgradable from: 0.11-1]
pcre/stable 8.43-5 aarch64 [upgradable from: 8.43-3]
pcre2/stable 10.33-1 aarch64 [upgradable from: 10.33]
perl/stable 5.30.0-1 aarch64 [upgradable from: 5.30.0]
poppler/stable 0.79.0-2 aarch64 [upgradable from: 0.76.1-2]
pulseaudio/stable 12.2-21 aarch64 [upgradable from: 12.2-19]
readline/stable 8.0.1 aarch64 [upgradable from: 8.0-2]
sed/stable 4.7-1 aarch64 [upgradable from: 4.7]
sox/stable 14.4.2-13 aarch64 [upgradable from: 14.4.2-12]
speexdsp/stable 1.2.0-1 aarch64 [upgradable from: 1.2.0]
teckit/stable 2.5.9-3 aarch64 [upgradable from: 2.5.9-2]
termux-am/stable 0.3 all [upgradable from: 0.2]
termux-auth/stable 1.1-1 aarch64 [upgradable from: 1.1]
termux-exec/stable 0.4-1 aarch64 [upgradable from: 0.4]
termux-tools/stable 0.71 all [upgradable from: 0.68]
texlive-bin/stable 20190410-6 aarch64 [upgradable from: 20190410-4]
texlive-tlmgr/stable 20190410-2 all [upgradable from: 20190410]
tmux/stable 2.9a-4 aarch64 [upgradable from: 2.9a-1]
vim/stable 8.1.2050 aarch64 [upgradable from: 8.1.1700]
vim-runtime/stable 8.1.2050 all [upgradable from: 8.1.1700]
xorg-font-util/x11 1.3.2 aarch64 [upgradable from: 1.3.1-6]
xorg-fonts-75dpi/x11 1.0.3-7 all [upgradable from: 1.0.3-5]
xorg-fonts-alias/x11 1.0.3-5 all [upgradable from: 1.0.3-3]
xorg-fonts-encodings/x11 1.0.5-2 all [upgradable from: 1.0.5]
xorg-mkfontscale/x11 1.2.1-5 aarch64 [upgradable from: 1.2.1-3]
xorg-xauth/x11 1.1-2 aarch64 [upgradable from: 1.1]
xterm/x11 9999-2 all [upgradable from: 9999]
xvidcore/stable 1.3.5-1 aarch64 [upgradable from: 1.3.5]
xz-utils/stable 5.2.4-7 aarch64 [upgradable from: 5.2.4-2]
zlib/stable 1.2.11-4 aarch64 [upgradable from: 1.2.11-3]
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.10.61-11738507 #1 SMP PREEMPT Mon May 14 20:52:00 KST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.0
Device manufacturer:
samsung
Device model:
SM-G920V

**Comment by nhed** [comment] 2019-10-09 14:27
also narrow characters like yod or vav are bloated
![image](https://user-images.githubusercontent.com/513759/66490548-550a5f00-ea7f-11e9-8dc1-0ded3d1306c6.png)

**Comment by MatanZ** [comment] 2022-09-19 08:22
I posted a PR that should fix this (original) issue. The second issue, reported by @nhed is caused by termux scaling characters to the correct width. It can easily be fixed by using a monospace font that includes Hebrew characters.

**Comment by iTzVoko** [comment] 2023-02-18 12:03
> I posted a PR that should fix this (original) issue. The second issue, reported by @nhed is caused by termux scaling characters to the correct width. It can easily be fixed by using a monospace font that includes Hebrew characters.

Does this PR fix Arabic language also (which is RTL language also)?

**Comment by MatanZ** [comment] 2023-02-25 15:41
> Does this PR fix Arabic language also (which is RTL language also)?

I think it should, but I am not certain, and did not test many scenarios. Please try and tell me.

**Closed** 2024-09-27 09:27 UTC
Labels: bug report, help wanted
