### ISSUE TITLE
Feature Request: Allow custom keystrokes mapped to horizontal swipes

### ISSUE THREAD

**Issue by goodevilgenius** [termux/termux-app#1691] opened 2020-08-05 21:49 UTC
**Feature description**
It would be useful if a horizontal swipe could be mapped to custom keystrokes.

For example, JuiceSSH allows horizontal swipes to mapped to one of several preset keystrokes, such as irssi next (Ctrl-N)/prev (Ctrl-P), tmux next (Ctrl-B n)/prev (Ctrl-B p), or screen next (Ctrl-A n)/prev (Ctrl-A p).

The problem with this implementation is that it only allows for one of these three default sets of keystrokes. Since people often customize their keybindings in any of these applications, that's less useful.

**Reference implementation**

Does another app/terminal emulator have this feature?
JuiceSSH

**Comment by xeffyr** [comment] 2020-08-05 22:06
@goodevilgenius Extra keys row already allows to create key shortcuts. Copying here example from https://wiki.termux.com/wiki/Touch_Keyboard#Advanced_extra_keys_configuration:
```
extra-keys = [[ \
  {key: ESC, popup: {macro: "CTRL f d", display: "tmux exit"}}, \
  {key: CTRL, popup: {macro: "CTRL f BKSP", display: "tmux ←"}}, \
  {key: ALT, popup: {macro: "CTRL f TAB", display: "tmux →"}}, \
  {key: TAB, popup: {macro: "ALT a", display: A-a}}, \
  {key: LEFT, popup: HOME}, \
  {key: DOWN, popup: PGDN}, \
  {key: UP, popup: PGUP}, \
  {key: RIGHT, popup: END}, \
  {macro: "ALT j", display: A-j, popup: {macro: "ALT g", display: A-g}}, \
  {key: KEYBOARD, popup: {macro: "CTRL d", display: exit}} \
]]
```

**Comment by twaik** [comment] 2023-12-23 13:52
Duplicate of #720

**Closed by twaik** 2023-12-23 13:52 UTC
