### ISSUE TITLE
Slowdown of Termux when accessing shared internal storage

### ISSUE THREAD

**Issue by arocoun** [termux/termux-app#1967] opened 2021-03-16 11:52 UTC
**Problem description**
An image processing and uploading program I use, mapillary_tools, has started running much slower on Termux -- at less than 1/10 normal speed. 

I suspect it has something to with the update to Android 11, and how Android allocates resources to Termux. Termux actually SPEEDS UP DRAMATICALLY for a second while my phone is adjusting to being rotated! 

Video of this odd behavior: https://youtu.be/O5wTd0V7610

I've tried resetting my phone, reinstalling Termux, reinstalling mapillary_tools, and making sure battery optimization is off for Termux. After taking WAY too long searching, I haven't found that anyone else has had this problem.

**Steps to reproduce**
Not sure what lead to this.

**Expected behavior**
Termux and any programs on it run at normal speeds.

**Additional information**

* Termux application version: 0.101 from Play Store
* Android OS version: 11
* Device model: Galaxy A51 5G

**Comment by arocoun** [comment] 2021-03-16 12:15
I tested Termux's speed at copying files (using cp command) while on verbose. Its copy speed is ludicrously slow -- but once again speeds up when I rotate my phone.

**Comment by agnostic-apollo** [comment] 2021-03-16 12:17
Well, all these can be easily solved by using a servo motor and mounting your phone on it and keep rotating it while running termux commands.

**Comment by agnostic-apollo** [comment] 2021-03-16 12:18
But can be looked into. Does it still happen if you acquire a wakelock, even though it's to prevent sleep.

**Comment by arocoun** [comment] 2021-03-16 12:27
Ooh! Big discovery! Termux ONLY slows down when dealing with files from outside it's own directory -- that is, files that can only be accessed after the termux-setup-storage command.

**Comment by agnostic-apollo** [comment] 2021-03-16 12:35
Well, external shared storage is emulated with sdcardfs, so performance would definitely be slower. But weird that rotation has an effect on it.

**Comment by arocoun** [comment] 2021-03-16 12:37
Hmm. After looking it up, it seems that many programs access storage more slowly since Android 11. Probably something to do with beefed up security for every interaction with storage.

So this is likely more of an Android problem than a Termux problem. Still, I'll still happily accept advice, haha!

**Comment by agnostic-apollo** [comment] 2021-03-16 13:34
Scoped storage is currently not being applied to termux, however, android would still be doing extra processing internally to handle scoped storage itself, so performance impact could/would likely be there.

Moving would depend on what you are actually doing. If you are repeatedly accessing the same file at different times or are in place editing, then the one move operation would be worth it for faster operations later. However, if there is only a one time read operation for processing a file, then moving it first would make that two operations so would be twice as slow.

And you are right, slow external storage issues are not a termux issue, and can't likely be solved by it. Your rotation issue is weird currently, that can be looked into.

**Comment by xeffyr** [comment] 2021-03-16 13:34
Does touching the screen (scrolling a terminal or notification list) have similar effect as rotating screen?

This seems like either misconfigured bus or cpu frequency scaling. This also can be done intentionally by manufacturer, so device reaching its full performance only in certain cases for battery power saving when user doesn't interact with the device.

**Comment by agnostic-apollo** [comment] 2021-03-16 13:45
Actually, you may be right, it might be a boost in CPU speed instead of storage speed. The interactive CPU governor for the kernel has settings like the [input_boost](https://android.googlesource.com/kernel/common/+/a7827a2a60218b25f222b54f77ed38f57aebe08b/Documentation/cpu-freq/governors.txt#241) for boosting CPU freq for a few milliseconds when touchscreen is touched. Not sure what android 11 (or his device) is using as the default governor these days but other governors have similar settings and this could be related. Rotating requires redrawing of activities, so a boost at that time would make sense, that's likely what's happening.

**Comment by xeffyr** [comment] 2021-03-16 14:57
Stock Samsung kernel uses `interactive`. That's on Galaxy S7, not sure what is used on other devices.

**Comment by agnostic-apollo** [comment] 2021-03-16 15:21
Yeah, can't really guess without checking. There are also [ARM big.LITTLE](https://en.wikipedia.org/wiki/ARM_big.LITTLE) CPU cluster specific governors. On my LG G5, the big cores (0 and 1) are set to `interactive`, while the little cores (2 and 3) are set to `performance` governor. Although, I'm using a custom kernel, so not sure what the default was. OP can check [CPU-Z](https://play.google.com/store/apps/details?id=com.cpuid.cpu_z&hl=en) for detecting CPU scaling.

**Comment by RalfWerner** [comment] 2021-03-17 15:35
@arocoun My Galaxy device was also updated on Android 11 yesterday. Your `mapillary_tools` example is _**poor to reproduce.**_ If it is I/O problems on `/sdcard`, you could _please create a **simple** repeatable bash_ example with which **you and I** can repeat that?

**Comment by arocoun** [comment] 2021-03-18 07:26
> @arocoun My Galaxy device was also updated on Android 11 yesterday. Your `mapillary_tools` example is _**poor to reproduce.**_ If it is I/O problems on `/sdcard`, you could _please create a **simple** repeatable bash_ example with which **you and I** can repeat that?

My problem has nothing to do with an SD card, but rather the phone's internal storage (ie when you first open Termux, the directory you go to with "cd storage"). 

I have no idea how to form an easily-reproduced situation where Termux interacts with internal storage thousands of times, then interacts with files in it's own directory thousands of times to compare the speed. 

I use Termux / Linux command line for one thing, mapillary_tools. My experience beyond that is limited. Perhaps someone with more experience could come up with something.

**Comment by RalfWerner** [comment] 2021-03-18 09:20
> but rather the phone's internal storage

`ls -l /sdcard /storage/self/primary` are the _symlinks_ for the same storage as the _symlinks_ in the `ls -l ~/storage`. Everything _internal storage_, if no external card is in the device. So we mean the same!
I am **not** sure if your problem is related to I/O on `/sdcard`. It occurs at `Configure*` Events (rotation) and performs a complex process with pictures/videos that may also have to do with network activity, cache etc. This is **not* visible in your YouTube Reference.

I do not wont to manage an account for _mapillary_. That's why the request a simple _bash_ script like:
`typeset -i n=0; while true; do n+=1; f=$(find /sdcard/DCIM -type f); cp $f storage; echo $n; done`

Here all camera recordings of your device are copied in Termux `~/storage` until you stop the process. (Ctrl+c) e.g. at 1000. The rotation of my device has _no influence_ on the performance (expected) - **yours?**
But simple packages as `fluxbox feh` also not.

**Comment by arocoun** [comment] 2021-03-18 10:29
Oh, thanks for clarifying what you meant by /sdcard! Like I said, I don't have much experience in Termux.

That video is *not* of files being copied. Rather, it is one stage of image processing, where the images are analyzed. Thousands of tiny descriptive files are created, and they are written to or read from hundreds of thousands of times.

When these files are somewhere in shared storage, this process takes over 30 minutes. When these files are in Termux's directory, the process takes less than 2 minutes.

Regarding your copying experiment: I'm thinking that if the slowdown for each file interaction is, say, 10 milliseconds, you wouldn't notice a slowdown copying 1000 image files.

When I did the copying mentioned in my second post, I was copying almost 10,000 *tiny* files created by the aforementioned process -- so the per-interaction delay played a bigger role. When I copy 1000 image files now, I see almost no slowdown.

**Comment by xeffyr** [comment] 2021-03-18 10:46
> When these files are somewhere in shared storage, this process takes over 30 minutes. When these files are in Termux's directory, the process takes less than 2 minutes.

Even though that shared storage (/sdcard, /storage/emulated/0) and Termux home directory are stored on same partition, there still some differences. As shared storage is mounted through overlay, certain performance penalty is expected, especially in random-access mode.

**Comment by arocoun** [comment] 2021-03-18 10:51
> > When these files are somewhere in shared storage, this process takes over 30 minutes. When these files are in Termux's directory, the process takes less than 2 minutes.
> 
> Even though that shared storage (/sdcard, /storage/emulated/0) and Termux home directory are stored on same partition, there still some differences. As shared storage is mounted through overlay, certain performance penalty is expected, especially in random-access mode.

Probably true there'll be some slow down in any case! But before Android 11, the slowdown wasn't noticeable.

I now find myself wondering if mapillary_tools is uncommon in the number of file interactions it does, and if this problem is not likely to affect other folks.

**Comment by xeffyr** [comment] 2021-03-18 10:57
> But before Android 11, the slowdown wasn't noticeable.

Probably because Android 11 implemented changes to the overlay filesystem (sdcardfs or how it is called) to meet the requirements of the further scoped storage enhancements.

**Comment by RalfWerner** [comment] 2021-03-18 12:06
> there still some differences. As shared storage is mounted through overlay

@xeffyr I can reproduce that! When I use in the example above `cp $(find storage -type f) ../usr/tmp` (termux only - repeat 100 times) I need 11 sec instead of 16 from `/sdcard` and exactly the same relation, when I repeat it 200 times (60% more). When I repeat this on an Android 8 device, the relation is revers. So you are right - Android 11 reduced the `/sdcard` performance significant! But this **don't** explain the `Configure*` **Event** behavior of @arocoun
> I use Termux / **Linux** command line for one thing, mapillary-tools

@arocoun is this the **first* time, that you use _mapillary_ on a _rotatable device? `fluxbox` e.g. reconfigure the graphic screen, when you _rotate_ (on a servo motor:) or resize it in Pop-View (possible in Android 11).

**Comment by annihat** [comment] 2021-03-22 21:05
Hi, another interested but unskilled user here, @arocoun have you tried using \<sdcard\>/Android/data/\<package name\> ? For some time it's been the only directory on the sdcard usable by an app without specific permissions so might not be slowed by the system. (on Android 2.3.5 it's \<sdcard\>/.android/data/\<package\> I don't know when it changed)

On my device it's /storage/emulated/0/Android/data/com.termux but Termux doesn't have permission to create the directory, you have to do it with a file manager (I was very surprised the setup routine hadn't created it). It's created with Owner: \<package\> & Group: sdcard_rw & permissions: rwxrwx--x so other apps can access it.

**Comment by agnostic-apollo** [comment] 2021-03-22 21:12
The `/sdcard` is a "symlink" to `/storage/emulated/0` as the default on android, which is emulated by `sdcardfs`. So `/sdcard/Android/data/<package_name>` would have the same performance degradation as any other path under `/sdcard`.

You can create the directory from termux by running `termux-setup-storage`.

**Comment by annihat** [comment] 2021-03-22 22:22
> 
> You can create the directory from termux by running `termux-setup-storage`.

Termux, like Android, is a steep learning curve. 

What does this command do, exactly? What would happen if I ran it now that I've created the directory manually? Would it do anything extra?

**Comment by xeffyr** [comment] 2021-03-22 22:29
@annihat It will create that directory again. `termux-setup-storage` sends an intent to Termux application which by itself will wipe that directory (if exists) and rebuild symlink set from scratch.

**Comment by annihat** [comment] 2021-03-22 23:52
@xeffyr , @agnostic-apollo , thanks for that, it produces a useful-looking group of directories (including the root of the sdcard) & asks for permission to use them. It doesn't do anything with the one already-writable directory though.

**Comment by agnostic-apollo** [comment] 2021-03-23 00:05
Welcome.

The termux `setupStorageSymlinks()` function only deletes the `~/storage` directory. It won't delete `Android/data` directory. The call to `externalFilesDirs()` automatically creates the directory if missing.

https://wiki.termux.com/wiki/Termux-setup-storage

**Comment by annihat** [comment] 2021-03-23 08:58
@agnostic-apollo , I like _termux-setup-storage_, I really do, but it's an additional feature & correctly so. 

My opinion is that the installer from the appstore should create _\<sdcard\>/Android/data/com.termux_ & provide a link to it in $HOME because no permissions are needed & it can still be used if the user chooses not to grant them (special-use installations like the one in this thread wouldn't seem to need general permission when a specific permission is already available)

**Comment by SDRausty** [comment] 2021-03-23 09:17
> the installer from the appstore should create <sdcard>/Android/data/com.termux & provide a link to it in $HOME because no permissions are needed & it 

@annihat I just tested your solution; Thanks for sharing. It works!

**Comment by RalfWerner** [comment] 2021-03-23 09:26
The authorization can be granted with the Android Setup **as well** as`termux-setup-storage`.
@annihat If you have an Android 11 device (which deals with this issue) and/or _additionally external_ card there are special features (duplex). The path`a=Android/data/com.termux`is also special (is disposed of with the current app with targetSDK<30).

**Comment by agnostic-apollo** [comment] 2021-03-23 11:37
> My opinion is that the installer from the appstore should create _<sdcard>/Android/data/com.termux_ & provide a link to it in $HOME because no permissions are needed & it can still be used if the user chooses not to grant them (special-use installations like the one in this thread wouldn't seem to need general permission when a specific permission is already available)
> (I also think a _readme.txt_ should be placed in there explaining that this directory is on the sdcard & accessible to other apps so can be used for file transfers without needing the user to grant permissions)

Accessing `Android/data` directory of other apps has been revoked in android 11 unless apps use hacks, check [here](https://github.com/termux/termux-app/issues/1952#issuecomment-786620827).

And everybody doesn't need symlinks in their `$HOME` directory, it's a user choice. For some absolute paths are preferred, if termux scripts of users (that may be shared with others) are relying on the symlinks, then it needs to be ensured that `termux-setup-storage` has been run after termux installation or after/during script installation on a different device and that symlinks exist and refer to correct paths. This is specifically important for removable external sd cards. With absolute paths such checks aren't required, user just needs to grant storage permission on installation and nothing more. It's better for background scripts too for which a prompt can't be shown to users.

Automatically creating the `Android/data` directories could be considered although that is an additional IO process to all **slow** storages on every termux startup, but automatically creating only their symlinks likely isn't the best way. The `termux-setup-storage` checks if the `~/storage` directory already exists before asking user if it should be wiped to recreate the symlinks. So if we start creating only the `Android/data` symlinks without the others, then the `~/storage` directory would be created and it may be incorrectly assumed by `termux-setup-storage` and current user scripts that ALL symlinks exist if only the check for `~/storage` directory existence is done. At the very least it would require more checks for it to be doable, there are probably other issues too.

**Comment by RalfWerner** [comment] 2021-03-23 13:29
Back to _this_ Issue - with my _**29+**_ [check process](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-780625381) I've got:
```
lrwxrwxrwx 1 u0_a170 u0_a170     34 Feb 15 15:35 fd -> /storage/1A55-0F06
lrwxrwxrwx 1 u0_a170 u0_a170     34 Feb 26 09:51 fda -> fd/Android/data/com.termux/files
lrwxrwxrwx 1 u0_a170 u0_a170     34 Feb 15 15:34 sd -> /storage/emulated/0
lrwxrwxrwx 1 u0_a170 u0_a170     34 Feb 26 09:52 sda -> sd/Android/data/com.termux/files
drwx------ 2 u0_a170 u0_a170   4096 Feb 26 10:20 storage
```
So I find (duplex) with`ls fd/D* sd/D*` 6 paths `(sd,fd)x(DCIM,Documents,Download)` but only 2 paths with `ls storage/d*` (miss `documents`). I had already documented the performance loss (60%) [above](https://github.com/termux/termux-app/issues/1967#issuecomment-801873944) but for the `??a` path be does not yet _checked._
This I have done _now_ with the same process on an _Android **11 Pixel** emulation._ Here I could **not** detect losses, but rather a _performance **improvement**_ of 30-50% on the`??a` paths.

**Comment by agnostic-apollo** [comment] 2021-05-17 21:04
Closing since likely an Android 11 OS issue. Users should use termux private app data directory for multi-access processing of files instead of shared storage.

**Closed by agnostic-apollo** 2021-05-17 21:04 UTC

**Comment by RalfWerner** [comment] 2021-05-18 07:43
> Users should use termux private app data directory for multi-access processing of files instead of shared storage

This requires enough memory. My _normale_ Termux usage would then fail to 2 of my 3 devices. With _Target **28**_, however, it is never a real problem to save everything except `u/` into `fd` (above). But with Android 11 `*setup-storage` is _sometimes_ not sufficient and _**manual** Deny->Allow_ toggle (workaround) is required.
Maybe [here](https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/TermuxActivity.java#L648) it could be changed. Also at [29+](https://github.com/termux/termux-app/blob/android-10/app/src/main/java/com/termux/app/TermuxActivity.java#L194) I have not found any real restrictions.

**Comment by agnostic-apollo** [comment] 2021-05-18 09:16
>This requires enough memory. 

Then go complain to android OS devs, although unlikely to be solved since its part of design now or use root to access `/data/media/0` directly without `sdcardfs`.

>Maybe here it could be changed

It's possible to detect the condition from within termux about storage permission being granted but still permission denied errors, but I don't know how to reproduce that situation to test it. Also don't know if that happens when targeting sdk 29+. If someone does, let me know.

**Comment by RalfWerner** [comment] 2021-05-18 14:18
> ... or use _root_ to access `/data/media/0` directly without `sdcardfs`.
Also don't know if that happens when targeting sdk **29+**. If someone does, let me know.

_root_ would be nice to the check, but is not a solution for the [IP Obj on Android](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-780625381) (Checks with _**29+** Artifakt_). In AVD I use _one_ virtual sdcard (`ldcard`) on different PCs and with various emulators/SDK-versions. They are all different. Please tell me _which emulator **you** used_ to test, so that I can generate test cases?
As with real devices, only _one_ emulator+`ldcard` can be used at the same time and change the data to `ldcard` should always lead to restart on other emulators.
With my real devices I currently have a maximum of 64G, which I have also exchanged (with needle). In all cases, since my [Success Message](https://gitter.im/termux/dev?at=60277759a7fc4b573bcffaca), I was able to use the sdcard - with patience and workaround. So we do not need to strive to the Android developers.

The [updated-flavor](https://gitter.im/termux/dev?at=60a0ecc52ee2b13d95b06526) Branch by @fornwall generates two `*.apk`, but not the right for _**29+**_ as `Android-10`.
But  `app-current-debug.apk` is identical with your last v113 artifact.
