### ISSUE TITLE
wget cannot get https file

### ISSUE THREAD

**Issue by l1t1** [termux/termux-app#1168] opened 2019-06-28 14:23 UTC
**Problem description**
wget cannot get https url file

**Steps to reproduce**
wget https://zero.sjeng.org
wget: not an http or ftp url: https://zero.sjeng.org
**Expected behavior**
get the file

**Additional information**
Post output of command `termux-info`.
Updatable packages:
apt/stable 1.4.9-5 aarch64 [upgradable from: 1.4.9-3]
bash/stable 5.0.7-1 aarch64 [upgradable from: 5.0.7]
busybox/stable 1.30.1-2 aarch64 [upgradable from: 1.30.1-1]
ca-certificates/stable 20190515 all [upgradable from: 20190124]
command-not-found/stable 1.37 aarch64 [upgradable from: 1.36]
dpkg/stable 1.19.7 aarch64 [upgradable from: 1.19.4-1]
gpgv/stable 2.2.16 aarch64 [upgradable from: 2.2.15-1]
libandroid-support/stable 24-3 aarch64 [upgradable from: 24]
libbz2/stable 1.0.6-3 aarch64 [upgradable from: 1.0.6-2]
libc++/stable 20 aarch64 [upgradable from: 19b]
libcurl/stable 7.65.1 aarch64 [upgradable from: 7.64.1-1]
ncurses/stable 6.1.20190511-1 aarch64 [upgradable from: 6.1.20181117-1]
openssl/stable 1.1.1c-1 aarch64 [upgradable from: 1.1.1b-3]
readline/stable 8.0-1 aarch64 [upgradable from: 8.0]
termux-tools/stable 0.67 all [upgradable from: 0.65]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://mirrors.tuna.tsinghua.edu.cn/termux stable/main
https://mirrors.tuna.tsinghua.edu.cn/termux stable/main
System information:
Linux localhost 3.18.20-perf-ga04878d #1 SMP PREEMPT Thu Oct 13 15:18:20 CST 2016 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0.1
Device manufacturer:
ZUK
Device model:
ZUK Z2131
$
$

**Comment by Grimler91** [comment] 2019-06-28 14:32
You are using the busybox version of wget, run `pkg in wget; hash -r` to get the full version.

Duplicate of https://github.com/termux/termux-packages/issues/2423

**Closed by Grimler91** 2019-06-28 14:32 UTC
