### ISSUE TITLE
Opencv hook for python is missing

### ISSUE THREAD

**Issue by vkuehn** [termux/termux-app#892] opened 2018-10-25 11:43 UTC
Hi
with these instructions I installed opencv from sources
https://wiki.termux.com/wiki/Instructions_for_installing_python_packages#opencv

Also added pointless repository. Pip seach opencv* brings back a lot but installing any package failed

Any hint on how to properly get opencv working with python3 in termux ?

**Comment by xeffyr** [comment] 2018-10-25 11:46
Duplicate of https://github.com/termux/termux-packages/issues/1992

**Comment by vkuehn** [comment] 2018-10-25 11:55
Ups sorry didn't find it and yes I   have done all that and failed..

**Closed** 2018-10-25 11:55 UTC

**Comment by bmvaghera** [comment] 2018-10-25 11:57
I have nwe issue 
Python2 mbf .py termux
Traceback (most recent call last):
  File "MBF2.pye", line 1, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 407, in <module>
  File "<script>", line 400, in menu
  File "<script>", line 339, in idteman
NameError: global name 'id_teman' is not defined
