### ISSUE TITLE
An unknown reason for the exit. 

### ISSUE THREAD

**Issue by zhiji-0424** [termux/termux-app#2546] opened 2022-01-26 06:06 UTC
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2022-01-26 05:59:13 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2022-01-26 05:59:10 UTC`  

**Crash Message**:
```
Attempt to invoke virtual method 'boolean android.view.View.requestFocus()' on a null object reference
```

### Stacktrace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.requestFocus()' on a null object reference
	at com.termux.app.TermuxActivity.toggleTerminalToolbar(TermuxActivity.java:490)
	at com.termux.app.terminal.TermuxTerminalViewClient.onCodePoint(TermuxTerminalViewClient.java:389)
	at com.termux.view.TerminalView.inputCodePoint(TerminalView.java:652)
	at com.termux.view.TerminalView$2.sendTextToTerminal(TerminalView.java:371)
	at com.termux.view.TerminalView$2.commitText(TerminalView.java:307)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:341)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6896)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.117`  
**VERSION_CODE**: `117`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.9.77+`  
**SDK_INT**: `27`  
**RELEASE**: `8.1.0`  
**ID**: `O11019`  
**DISPLAY**: `O11019 release-keys`  
**INCREMENTAL**: `1638518199`  
**SECURITY_PATCH**: `2021-10-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `vivo`  
**BRAND**: `vivo`  
**MODEL**: `V1732A`  
**PRODUCT**: `PD1732`  
**BOARD**: `k62v1_64_bsp`  
**HARDWARE**: `mt6762`  
**DEVICE**: `PD1732`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by SDRausty** [comment] 2022-01-26 06:24
At times I have a moment and sometimes more in order to gaze at `logcat -v color` while enjoying my time glued to one of my favorite Android apps which is Termux in the hope of gleeming more usefull information.

> Crash Details

Bravo and thank you very much for the exit details that uou have provided;  I wish I knew how to resolve this issue more than simply asking a newbe question;  Which command/s was/were used to gleem these traces?

**Comment by zhiji-0424** [comment] 2022-01-26 06:41
I open up the app and do something, and then I put it in the background. When I came back, the app was killed, but I still started it from the Android background key, and then I tried to open the Ctrl keyboard with the volume keys '+' and 'Q', at which point the app quit abnormally.











ll

**Comment by SDRausty** [comment] 2022-01-26 07:44
Which command did you use to make the report?

**Comment by zhiji-0424** [comment] 2022-01-26 07:49
> Which command did you use to make the report?
> 
> > Crash Message
> > Stacktrace

ennn....It's maybe TermuxApp auto make.
I used 'ls' to see if my files exits, then I see the file named 'crash_log_backup.md'.
![Screenshot_20220126_154907.jpg](https://user-images.githubusercontent.com/96622419/151123391-ab4fd305-5fc8-4542-8b3f-5e92fb3cce84.jpg)

**Comment by SDRausty** [comment] 2022-01-26 07:55
Thank you for your timely answer;  Which command did you use just before it crashed?

**Comment by zhiji-0424** [comment] 2022-01-26 08:12
> Thank you for your timely answer;  Which command did you use just before it crashed?

I press the volume key and the Q key of the keyboard for the purpose of displaying Ternux's shortcut keyboard. ![1643184630367.jpg](https://user-images.githubusercontent.com/96622419/151126326-a70ecde2-2a5a-48ef-b93a-16b29fed4439.jpg)

**Comment by zhiji-0424** [comment] 2022-01-26 08:14
But now no longer appear that phenomenon .... https://user-images.githubusercontent.com/96622419/151126627-063f708c-c294-4670-a26c-7b65a6372cb8.mp4

**Comment by SDRausty** [comment] 2022-01-26 10:30
> press the volume key and the Q key
>  no longer appear that phenomenon

I just tried this key combination on mine many times;  Works as expected in Termux 0.118.0 F-Droid aarch64!

It took a while for the Android toasts to clear, and then I did make many of them.  Maybe your Android crashed your Termux just one time?

**Comment by agnostic-apollo** [comment] 2022-01-26 10:35
This kinda thing is usually a random crash, termux getting killed likely left it in an inconsistent state, will look into fixing it. Thanks for the report.

p.s termux automatically generates crash reports since `v0.109`

https://github.com/termux/termux-app/releases/tag/v0.109

**Comment by zhiji-0424** [comment] 2022-01-26 10:47
That may indeed be the case. Thank you for your reply.&nbsp;











ll

**Comment by SDRausty** [comment] 2022-01-26 11:27
> I open up the app and do something, and then I put it in the background. When I came back, the app was killed

Can you please check System > Battery > Adaptive Battery?  I have Adaptive Battery turned to off as the battery saver features did at times seem to interfere with my work in Termux.  This issue might be a duplicate of https://github.com/termux/termux-app/issues/1172

**Comment by zhiji-0424** [comment] 2022-01-26 12:02
Thanks for your answer !

**Comment by SDRausty** [comment] 2022-01-26 18:14
You're welcome.

**Closed** 2022-02-01 02:05 UTC
