### ISSUE TITLE
[Bug]: Bootstrap installation error

### ISSUE THREAD

**Issue by bfcns** [termux/termux-app#4299] opened 2024-12-10 22:24 UTC
### Problem description

Termux cannot install bootstrap when installed from fdroid or from github releases to OnePlus Pad 2.

Bootstrap installation error. No shell prompt. 

[termux-crash_report.log](https://github.com/user-attachments/files/18086482/termux-crash_report.log)

### Steps to reproduce the behavior.

Download 118, 118.1 or 119 beta1 from Fdroid or github releases.

Bootstrap installation error.

### What is the expected behavior?

No bootstrap installation error.

### System information

* Termux application version: 118 or 119beta
* Android OS version: 15
* Device model: Oneplus Pad 2

**Comment by agnostic-apollo** [comment] 2024-12-11 06:24
Duplicate of #4219

**Closed by agnostic-apollo** 2024-12-11 06:24 UTC
Labels: bug report
