### ISSUE TITLE
cannot start ssh

### ISSUE THREAD

**Issue by Armsinrius** [termux/termux-app#2024] opened 2021-04-30 21:25 UTC
Hi 

I have been using Termux for a while. And today I have some issue with SSH.

I have installed Openssh and Nmap in termux, and I started with

```
sshd
nmap localhost
```

then it seems all 1000 ports are closed. 

Any one might have an idea?

**Comment by xeffyr** [comment] 2021-04-30 21:42
Issue is similar to https://github.com/termux/termux-packages/issues/6710 (about sshd and posgresql servers), so I'm closing this one.

As I can't reproduce it, it is unknown why it happens and how to solve it.

**Closed by xeffyr** 2021-04-30 21:42 UTC
