### ISSUE TITLE
Sure blinking cursor works?

### ISSUE THREAD

**Issue by angelog0** [termux/termux-app#2138] opened 2021-06-19 22:29 UTC
Here I have v. 0.114 and in the `termux.properties` I added `terminal-cursor-blink-rate=600` and restarted Termux. The cursor blinks until the device goes to sleep; then it stops bilinking until the next Termux start. This happens both on device wit Android 8.1 and that with android 11...

**Comment by agnostic-apollo** [comment] 2021-06-20 00:30
Thanks, confirmed. Likely e119d34 broke this. I guess need to start it both on `onResume` and `onEmulatorSet` depending on if emulator is set.

**Comment by angelog0** [comment] 2021-06-21 22:50
It stops bilinking also doing this:

- Start Termux (now the cursor bilinks)
- Click the HOME button ans start another app, for example the browser
- Now return to Termux: the cursor stopped bilinking

**Comment by agnostic-apollo** [comment] 2021-06-21 23:01
Thanks. I can't reproduce that on android 7 device and android 10 avd, but hopefully, cases like that should be fixed with the way I'm doing it now. I have fixed locally, will push soon.

**Comment by angelog0** [comment] 2021-06-23 22:15
Just for completeness...

@agnostic-apollo wrote:

> I can't reproduce that on android 7 device [...]

That behavior happens on the device with android 11...

**Comment by Dalmater** [comment] 2021-06-24 00:53
For me on Android 9 it only stops blinking when i have more then one session open and as soon as i close a session the cursor stops blinking, but it disappears if it is the first prompt and comes back without blinking on the next prompt

**Comment by agnostic-apollo** [comment] 2021-06-24 01:03
>For me on Android 9 it only stops blinking when i have more then one session open and as soon as i close a session the cursor stops blinking, but it disappears if it is the first prompt and comes back without blinking on the next prompt

Can confirm this as well. Will look into it.

**Closed** 2021-06-30 01:18 UTC
