### ISSUE TITLE
Proot eror?

### ISSUE THREAD

**Issue by Hachimiz** [termux/termux-app#1457] opened 2020-02-03 20:06 UTC
> KaliNet

> $ ls

> nethunter-binds  nethunter-fs  nethunter.sh  

> start-nethunter.sh

> $ ./start-nethunter.sh

> proot error: execve("/usr/bin/env"): Function 

> not implemented

> proot info: possible causes:

  

> * the program is a script but its interpreter (eg. /bin/sh) was not found;

  

> * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;

>   * the program is a foreign binary but qemu was not specified;

 

>  * qemu does not work correctly (if specified);

  

> * the loader was not found or doesn't work.

> fatal error: see `proot --help`.

> proot error: can't chmod '/data/data/com.termux/files/usr/tmp/proot-10156-aRX1lg': Function not implemented

> proot error: can't chdir to '/root': Function not implemented

**Comment by xeffyr** [comment] 2020-02-03 22:08
Duplicate of https://github.com/termux/proot/issues/86.

**Closed by xeffyr** 2020-02-03 22:08 UTC
