### ISSUE TITLE
Feature Request : Have to unlock device to use notification buttons such as Wakelock and Exit

### ISSUE THREAD

**Issue by alou-S** [termux/termux-app#2133] opened 2021-06-18 15:34 UTC
Add an option to enable the requirement to unlock lock screen to Exit Termux and Release WakeLock.

I have a few daemons and servers running off Termux and it is kinda irritating when some guy just happens to press the exit button and I don't realize it until some other guy complains the server has been down for a few hours.

**Comment by agnostic-apollo** [comment] 2021-06-18 15:47
Duplicate of #584

Set lockscreen notification setting for termux app to hide all or hide sensitive only.

**Closed by agnostic-apollo** 2021-06-18 15:47 UTC
