### ISSUE TITLE
[Feature]: Screen Offset

### ISSUE THREAD

**Issue by toaranotdev** [termux/termux-app#2242] opened 2021-08-25 12:50 UTC
### Feature description

I'm not sure if there's a way to do fix this but, the texts kinda go off the screen (1080p HDMI Display), It's really annoying 

![1629895614765-1721355172](https://user-images.githubusercontent.com/85060424/130793083-98de9e75-2dbb-4d50-ad15-0cfad7942401.jpg)

The full text is ~/.../shinonome

### Additional information

Have never used any other terminal emulator except termux so I'm not sure... Oh and by the way I want larger font scale please :)  this font is kinda small (readable) but a larger font size would be nice

**Comment by agnostic-apollo** [comment] 2021-08-25 12:57
Duplicate of #2210

You can adjust font size by pinch and zoom on touch screens and with `Ctrl` + `Alt` + `+/-` with hardware keyboards.

https://wiki.termux.com/wiki/Hardware_Keyboard

**Closed by agnostic-apollo** 2021-08-25 12:57 UTC

**Comment by Aridlvory** [comment] 2021-09-02 05:34
Zooming out doesn't works for me
It will zoom out too much and I can't read anything
