### ISSUE TITLE
Termux.net Host Not Working![Bug]: 

### ISSUE THREAD

**Issue by DeFaUlT-TeChNoLoGiSt** [termux/termux-app#2699] opened 2022-04-08 20:44 UTC
### Problem description

I Need To connect to http://termux.net/dists/stable/InRelease?t=1 and not working and `apt update` same problem :

### Steps to reproduce the behavior.

`$ apt update

Get:1 https://termux.net/ stable InRelease [33.4 kB]
Err:1 https://termux.net/ stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Fetched 33.4 kB in 1s (24.2 kB/s)
Reading package lists... Done
E: Failed to fetch https://termux.net/dists/stable/InRelease Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.`

---------
host error all country
https://check-host.net/check-http?host=http://termux.net/dists/stable/InRelease?t=1

### System information

* Termux application version:0.79
* Android OS version:5.1.1
* Device model:J111f J1 Ace Lite

**Comment by agnostic-apollo** [comment] 2022-04-08 20:48
Duplicate of #2651

**Closed by agnostic-apollo** 2022-04-08 20:48 UTC
Labels: bug report
