### ISSUE TITLE
Unable to build termux

### ISSUE THREAD

**Issue by kvsjxd** [termux/termux-app#499] opened 2017-12-07 08:53 UTC
I keep seeing this after I checkout project directly from android studio.
`Error:A problem occurred configuring project ':terminal-emulator'.`
I also have installed latest build tools.

Here is the link to the IDE log, https://pastebin.com/UiWKH0wB

**Comment by fornwall** [comment] 2017-12-07 10:09
I'm unable to reproduce this on a fresh checkout of the project using Android Studio 3.0.1.

Which Android Studio version are you running?

Can you check that you have the `Use default gradle wrapper (recommended)` option selected in Preferences > Build, Executation, Deployment > Gradle?

**Comment by fornwall** [comment] 2017-12-07 10:12
I'm closing this as I (and several other I checked with) were unable to reproduce it, which indicates a local problem - check https://youtrack.jetbrains.com/issue/IDEA-163366? Let me know if I can help in any way!

**Closed by fornwall** 2017-12-07 10:12 UTC
