### ISSUE TITLE
Termux tar backup messed up. 

### ISSUE THREAD

**Issue by ShashaankHari** [termux/termux-app#2442] opened 2021-12-02 03:55 UTC
I generally have no issues restoring backups on termux using tar, I switch roms a lot. But I now have switched to Paranoid Android, I already had a weird issue at start

```
 ~ $ termux-setup-storage

Directory '~/storage' is going to be wiped. No storage contents will be touched.

Do you want to continue ? (y/n) y
WARNING: linker: Warning: "/system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
```

And due to Android 11 storage isolation, sometimes access to storage (emulated/0 or /sdcard) will be denied.
So I used app ops to grant legacy storage.
And after I restore my backup either the bootstrapping fails or I get this big error.
I'm also rooted.

```
warning: Could not set up terminal.
warning: TERM environment variable not set.
error: Your history will not be saved.
warning-path: Unable to locate data directory derived from $HOME: '/data/.local/share/fish'.
warning-path: The error was 'Permission denied'.
warning-path: Please set $HOME to a directory where you have write access.

error: Your personal settings will not be saved.
warning-path: Unable to locate config directory derived from $HOME: '/data/.config/fish'.
warning-path: The error was 'Permission denied'.
warning-path: Please set $HOME to a directory where you have write access.

~ddata/com.ter.termux/files/usr/share/fish/config.: Invalid token '-n\'
from sourcing file ~ddata/com.ter.termux/files/usr/share/fish/config.
        called during startup
source: Error while reading file '/data/data/com.termux/files/usr/share/fish/config.fish'
~ddata/com.ter.termux/files/usr/etc/fish/config. (line 16): Missing end to balance this function definition
function __fish_command_not_found_handler --on-event fish_command_not_found
^
from sourcing file ~ddata/com.ter.termux/files/usr/etc/fish/config.
        called during startup
source: Error while reading file '/data/data/com.termux/files/usr/etc/fish/config.fish'
fish: Unknown command: e\x00\x00\x00
echo -n "$USER@$hostname $PWD "'> '
^
in command substitution
```

This is my device information:
```
## Termux App Info

APP_NAME: Termux  
PACKAGE_NAME: com.termux  
VERSION_NAME: 0.117  
VERSION_CODE: 117  
TARGET_SDK: 28  
IS_DEBUG_BUILD: false  
APK_RELEASE: F-Droid  
SIGNING_CERTIFICATE_SHA256_DIGEST: 228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42  
##


## Termux:API App Info

APP_NAME: Termux:API  
PACKAGE_NAME: com.termux.api  
VERSION_NAME: 0.49  
VERSION_CODE: 49  
TARGET_SDK: 28  
IS_DEBUG_BUILD: false  
APK_RELEASE: F-Droid  
SIGNING_CERTIFICATE_SHA256_DIGEST: 228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42  
##


## Termux:Float App Info

APP_NAME: Termux:Float  
PACKAGE_NAME: com.termux.window  
VERSION_NAME: 0.14  
VERSION_CODE: 14  
TARGET_SDK: 28  
IS_DEBUG_BUILD: false  
APK_RELEASE: F-Droid  
SIGNING_CERTIFICATE_SHA256_DIGEST: 228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42  
##


## Termux:Styling App Info

APP_NAME: Termux:Styling  
PACKAGE_NAME: com.termux.styling  
VERSION_NAME: 0.29  
VERSION_CODE: 29  
TARGET_SDK: 28  
IS_DEBUG_BUILD: false  
APK_RELEASE: F-Droid  
SIGNING_CERTIFICATE_SHA256_DIGEST: 228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42  
##


## Termux:Widget App Info

APP_NAME: Termux:Widget  
PACKAGE_NAME: com.termux.widget  
VERSION_NAME: 0.13.0  
VERSION_CODE: 13  
TARGET_SDK: 28  
IS_DEBUG_BUILD: false  
APK_RELEASE: F-Droid  
SIGNING_CERTIFICATE_SHA256_DIGEST: 228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42  
##


## Device Info

### Software

OS_VERSION: 4.14.245-QuicksilveR™-v2.5/687b6860  
SDK_INT: 30  
RELEASE: 11  
ID: RKQ1.210528.001  
DISPLAY: RKQ1.210528.001 release-keys  
INCREMENTAL: eng.adithy.20210901.012847  
SECURITY_PATCH: 2021-07-05  
IS_DEBUGGABLE: 0  
IS_TREBLE_ENABLED: true  
TYPE: user  
TAGS: release-keys  

### Hardware

MANUFACTURER: Xiaomi  
BRAND: Xiaomi  
MODEL: Redmi Note 8  
PRODUCT: ginkgo  
BOARD: trinket  
HARDWARE: qcom  
DEVICE: ginkgo  
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi  
##
```

**Comment by Grimler91** [comment] 2021-12-02 06:04
Looks like same issue as in https://github.com/termux/termux-packages/issues/6639, try from bash or even /system/bin/sh

**Comment by ShashaankHari** [comment] 2021-12-02 06:38
@Grimler91 my problem is, fish is the default shell, how do I change..

**Comment by Grimler91** [comment] 2021-12-02 07:32
`chsh -s bash`, or just run bash. If you can't get to a shell then see https://wiki.termux.com/wiki/Recover_a_broken_environment for how to run a recovery/failsafe shell

If you have previously `chsh -s fish` then run `unlink ~/.termux/shell` from a failsafe session to undo that

**Comment by ShashaankHari** [comment] 2021-12-02 14:44
> `chsh -s bash`, or just run bash. If you can't get to a shell then see https://wiki.termux.com/wiki/Recover_a_broken_environment for how to run a recovery/failsafe shell
> 
> If you have previously `chsh -s fish` then run `unlink ~/.termux/shell` from a failsafe session to undo that

Thanks, changing shell from a failsafe did fix the issue. Will update fish and check for any errors..

**Comment by ShashaankHari** [comment] 2021-12-02 14:46
> Looks like same issue as in [termux/termux-packages#6639](https://github.com/termux/termux-packages/issues/6639), try from bash or even /system/bin/sh

Can I safely ignore this tho?
``` 
~ $ termux-setup-storage

WARNING: linker: Warning: "/system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
```

**Comment by xyllery-7** [comment] 2021-12-03 12:05
[Probably](https://stackoverflow.com/questions/33206409/unused-dt-entry-type-0x1d-arg/41900551#41900551)

**Comment by ShashaankHari** [comment] 2021-12-03 12:29
@xyllery-7 hopefully nothing major

**Comment by agnostic-apollo** [comment] 2021-12-03 13:00
https://wiki.termux.com/wiki/FAQ#Why_does_a_compiled_program_show_warnings

**Comment by ShashaankHari** [comment] 2021-12-03 13:23
@agnostic-apollo well I can't do do it since I'm getting this error

```
~ $ sudo termux-elf-cleaner ./system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so
open("./system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so"): No such file or directory
~ $ termux-elf-cleaner ./system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so
open("./system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so"): No such file or directory

```
And without the dot in front like not executing
```
$ termux-elf-cleaner /system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so
open("/system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so"): Read-only file system
```

**Comment by agnostic-apollo** [comment] 2021-12-03 13:33
Those entries are generated from within [`termux-setup-storage`](https://github.com/termux/termux-packages/blob/master/packages/termux-tools/termux-setup-storage) and those would need to be patched, not system libs. And no need to worry about them. And update your packages with `pkg upgrade`, you are using very old version of packages considering [almost 2 months old wipe prompt string](https://github.com/termux/termux-packages/commit/5a05be5d99741d91fc2df04fb75d70d2074bcc42) and warnings may go away if termux package maintainers have patched them.

**Comment by ShashaankHari** [comment] 2021-12-03 13:38
> Those entries are generated from within [`termux-setup-storage`](https://github.com/termux/termux-packages/blob/master/packages/termux-tools/termux-setup-storage) and those would need to be patched, not system libs. And no need to worry about them. And update your packages with `pkg upgrade`, you are using very old version of packages considering [almost 2 months old wipe prompt string](https://github.com/termux/termux-packages/commit/5a05be5d99741d91fc2df04fb75d70d2074bcc42) and warnings may go away if termux package maintainers have patched them.



Yes I have upgraded all the packages after recovering from a failsafe.

> > `chsh -s bash`, or just run bash. If you can't get to a shell then see https://wiki.termux.com/wiki/Recover_a_broken_environment for how to run a recovery/failsafe shell
> > If you have previously `chsh -s fish` then run `unlink ~/.termux/shell` from a failsafe session to undo that
> 
> Thanks, changing shell from a failsafe did fix the issue. Will update fish and check for any errors.. Edit: Fish has been updated and still getting the error, so should i just nuke fish dot files, would it fix?

What do I do about this..?

**Comment by xyllery-7** [comment] 2021-12-03 13:38
@ShashaankHari you forgot `sudo` in you second try.

**Comment by ShashaankHari** [comment] 2021-12-03 13:40
> > @agnostic-apollo well I can't do do it since I'm getting this error
> > ```
> > ~ $ sudo termux-elf-cleaner ./system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so
> > open("./system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so"): No such file or directory
> > ~ $ termux-elf-cleaner ./system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so
> > open("./system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so"): No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And without the dot in front like not executing
> > ```
> > $ termux-elf-cleaner /system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so
> > open("/system/lib64/libclang_rt.ubsan_standalone-aarch64-android.so"): Read-only file system
> > ```
> 
> @ShashaankHari you forgot `sudo` in you second try.

I tried and still got the same result

**Comment by xyllery-7** [comment] 2021-12-03 13:46
`chsh`, no?

**Comment by ShashaankHari** [comment] 2021-12-03 13:50
> `chsh`, no?

I've unlinked fish as default and using bash, but if I go into fish
```
~ $ echo "no issues in bash but what do i do to fix fish profile?"
no issues in bash but what do i do to fix fish profile?
~ $ fish
warning: Could not set up terminal.
warning: TERM environment variable not set.
error: Your history will not be saved.
warning-path: Unable to locate data directory derived from $HOME: '/data/.local/share/fish'.
warning-path: The error was 'Permission denied'.
warning-path: Please set $HOME to a directory where you have write access.

error: Your personal settings will not be saved.
warning-path: Unable to locate config directory derived from $HOME: '/data/.config/fish'.
warning-path: The error was 'Permission denied'.
warning-path: Please set $HOME to a directory where you have write access.

~ddata/com.ter.termux/files/usr/share/fish/config.: Invalid token '-n\'
from sourcing file ~ddata/com.ter.termux/files/usr/share/fish/config.
        called during startup
source: Error while reading file '/data/data/com.termux/files/usr/share/fish/config.fish'
~ddata/com.ter.termux/files/usr/etc/fish/config. (line 16): Missing end to balance this function definition
function __fish_command_not_found_handler --on-event fish_command_not_found
^
from sourcing file ~ddata/com.ter.termux/files/usr/etc/fish/config.
        called during startup
source: Error while reading file '/data/data/com.termux/files/usr/etc/fish/config.fish'
u0_a402@localhost /data/data/com.termux/files/home >
```

**Comment by agnostic-apollo** [comment] 2021-12-03 13:55
>you forgot sudo in you second try.

The `termux-elf-cleaner` is mainly for termux files under `$PREFIX` and compiled code and not for android system files. Never run it with `sudo` on termux user owned files. And system is mounted as read only partition permanently on android `10+` and you can't modify it, so `sudo` won't do any good.

About fish issue, you can track on linked termux packages issue and post `strace -f fish` log there and `cat /data/data/com.termux/files/usr/share/fish/config.fish` and `cat -A /data/data/com.termux/files/usr/share/fish/config.fish`.

FYI, if you have messed around with `root` for termux files, restore ownership and selinux contexts as per [this](https://github.com/termux/termux-app/issues/2080#issuecomment-846575028).

Closing since not a `termux-app` issue, nor a backup/restore issue itself.

**Closed by agnostic-apollo** 2021-12-03 13:55 UTC

**Comment by Grimler91** [comment] 2021-12-03 13:56
@ShashaankHari as seen in the other linked issue we cannot reproduce the issue. Best guess is that there is some issue with the rom you. Only thing I can suggest is to not use fish

**Comment by ShashaankHari** [comment] 2021-12-03 14:04
> @ShashaankHari as seen in the other linked issue we cannot reproduce the issue. Best guess is that there is some issue with the rom you are using. Only thing I can suggest is to not use fish
 @Grimler91 Fish is one of my favourite shells I'll see what I can do about that. Paranoid Android is my rom I'll also see to it.


> > you forgot sudo in you second try.
> 
> The `termux-elf-cleaner` is mainly for termux files under `$PREFIX` and compiled code and not for android system files. Never run it with `sudo` on termux user owned files. And system is mounted as read only partition permanently on android `10+` and you can't modify it, so `sudo` won't do any good.
> 
> About fish issue, you can track on linked termux packages issue and post `strace -f fish` log there and `cat /data/data/com.termux/files/usr/share/fish/config.fish` and `cat -A /data/data/com.termux/files/usr/share/fish/config.fish`.
> 
> FYI, if you have messed around with `root` for termux files, restore ownership and selinux contexts as per [this](https://github.com/termux/termux-app/issues/2080#issuecomment-846575028).
> 
> Closing since not a `termux-app` issue, nor a backup/restore issue itself.

@agnostic-apollo  Maybe once/(sometimes) I tried backing up fish from a root drop down shell like tsu and restored from tsu(usually worked on prev roms) but on other roms ive never faced this issue..

**Comment by agnostic-apollo** [comment] 2021-12-03 14:10
>I tried backing up fish from a root drop down shell like tsu and restored from tsu(usually worked on prev roms) but on other roms ive never faced this issue..

If you have even done this **once**, you must restore ownership and also selinux context with `restorecon` as per instructions.

**Comment by ShashaankHari** [comment] 2021-12-03 14:22
> > I tried backing up fish from a root drop down shell like tsu and restored from tsu(usually worked on prev roms) but on other roms ive never faced this issue..
> 
> If you have even done this **once**, you must restore ownership and also selinux context with `restorecon` as per instructions.

I just did as referenced in the other issue and it didn't fix fish.
I don't remember if the last backup was on A10/A11 but on prev a11 i didnt have this issue.

**Comment by ShashaankHari** [comment] 2021-12-03 14:31
> > > I tried backing up fish from a root drop down shell like tsu and restored from tsu(usually worked on prev roms) but on other roms ive never faced this issue..
> > 
> > 
> > If you have even done this **once**, you must restore ownership and also selinux context with `restorecon` as per instructions.
> 
> I just did as referenced in the other issue and it didn't fix fish. I don't remember if the last backup was on A10/A11 but on prev a11 i didnt have this issue and I have issues with only this time and only with fish, all my other stuff work and some a11 restrictions suck like /sdcard just straight up doesn't work on termux.

**Comment by agnostic-apollo** [comment] 2021-12-03 14:57
Then post the info as requested and someone may look into it.

For storage `permission denied` issues, disable and regrant permission.

**Comment by ShashaankHari** [comment] 2021-12-03 15:05
> Then post the info as requested and someone may look into it.
>
> For storage `permission denied` issues, disable and regrant permission.

My device info is posted at the top if you mean info as in device info..
I tried clearing app data, revoking, even uninstall and reinstall

**Comment by ShashaankHari** [comment] 2021-12-03 15:10
> > My device info is posted at the top if you mean info as in device info..
> 
> [#2442 (comment)](https://github.com/termux/termux-app/issues/2442#issuecomment-985539835)
> 
> > I tried clearing app data, revoking, even uninstall and reinstall
> 
> Then your rom has serious issues and not compliant with AOSP and so not a termux issue.
PA is aosp tho, I'll try again, and will provide details from fish.

**Comment by ieyhan09** [comment] 2021-12-03 18:54
![Uploading Screenshot_2021-12-04-01-53-33-57_84d3000e3f4017145260f7618db1d683.jpg…]()
