### ISSUE TITLE
App crashes while heavy processing on samsung phones

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-app#1706] opened 2020-08-12 08:16 UTC
**Problem description**
In all my samsung phones termux crashes while using ffmpeg for heavy video processing. Even with wakelock acquired.
However if i use ffmpeg in ubuntu or any os installed in termux, then there is no such crashing problem.
Means termux itself is crashing when processing load increases while os working with proot in termux never crashes despite any processing load

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:0.98
* Android OS version:10
* Device model:SM A750 (2018)

**Comment by Grimler91** [comment] 2020-08-12 09:03
You can probably use the `-threads` option of ffmpeg to limit CPU usage if high load is a problem. 

Termux being forced closed by os is not a bug but rather an os feature.

I am not sure why it does not crash in proot, I guess proot becomes a bottleneck limiting the cpu load?

**Closed by Grimler91** 2020-08-12 09:03 UTC
