### ISSUE TITLE
[Bug]: "sleep 1s" takes 1-11 seconds to execute

### ISSUE THREAD

**Issue by tchwpkgorg** [termux/termux-app#3243] opened 2023-02-10 20:24 UTC
### Problem description

"sleep" is a very basic command which takes amount of time to wait as an argument. Unfortunately, it doesn't behave as expected and sleeps much longer than it should.

"sleep" behaves erratically on my Google Pixel 2 XL phone, but seems to work correctly on a Google Pixel 7 pro.

### Steps to reproduce the behavior.

~ $ while true; do time sleep 1s ; done

real    0m3.246s
user    0m0.007s
sys     0m0.023s

real    0m10.615s
user    0m0.010s
sys     0m0.017s

real    0m11.289s
user    0m0.010s
sys     0m0.027s

real    0m5.289s
user    0m0.007s
sys     0m0.020s

real    0m11.093s
user    0m0.010s
sys     0m0.027s

real    0m6.049s
user    0m0.017s
sys     0m0.013s

real    0m1.032s
user    0m0.013s
sys     0m0.013s

real    0m1.032s
user    0m0.010s
sys     0m0.020s

real    0m3.159s
user    0m0.013s
sys     0m0.013s

### What is the expected behavior?

Expected result is to sleep for 1 second for every loop run.

### System information

* Termux application version: 0.118.0 from F-Droid.
* Android OS version: 11
* Device model: Pixel 2 XL

**Comment by agnostic-apollo** [comment] 2023-02-10 20:59
The cause for this issue usually is that the user is sending their phone to near a  blackhole via a  wormhole during the time the `time sleep` command is run, so make sure you are not doing that.

Otherwise, it could be time drift issue for the phone or process priority.

https://stackoverflow.com/questions/62817900/unix-sleep-is-sleeping-more-than-it-should-on-android

https://stackoverflow.com/questions/4128766/how-accurate-is-sleep-or-sleep

https://unix.stackexchange.com/questions/607217/sleep-command-delay-grossly-inaccurate-vm

https://issuetracker.google.com/issues/37065986

https://issuetracker.google.com/issues/36930949

Check android time docs for info on time synchronization.

https://source.android.com/devices/tech/connect/time

https://source.android.com/devices/tech/connect/time-source

Closing since this wouldn't be a termux issue.

**Closed by agnostic-apollo** 2023-02-10 20:59 UTC
Labels: bug report
