### ISSUE TITLE
clang doesn't work

### ISSUE THREAD

**Issue by Wikeolf** [termux/termux-app#740] opened 2018-06-26 15:51 UTC
CANNOT LINK EXECUTABLE "aarch64-linux-android-clang": cannot locate symbol "__register_frame" referenced by "/data/data/com.termux/files/usr/lib/libLLVM-6.0.so"...
Use Google Play install Termux
My phone is LG G5
Using Fulmics Rom 5.5 based on Android 7.0.

**Comment by Grimler91** [comment] 2018-06-26 23:32
Duplicate of https://github.com/termux/termux-packages/issues/2580. Should be fixed now, update all your packages.

**Closed by Grimler91** 2018-06-26 23:32 UTC
