### ISSUE TITLE
[Feature]: Compatible with Harmony OS

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-app#2331] opened 2021-10-10 12:31 UTC
### Feature description

I hope termux will be compatible with HarmonyOS and bring better experience

### Additional information

Huawei HarmonyOS, an operating system officially released by Huawei at the Huawei Developer Conference held in Dongguan on August 9, 2019, is Huawei's HarmonyOS.

HarmonyOS is a commercial version developed by Huawei based on the open source project OpenHarmony for a variety of full-scene smart devices.

Huawei HarmonyOS is a new distributed operating system for full scenarios, creating a world of super virtual terminal interconnection, organically linking people, devices, and scenarios, realizing extremely fast discovery, extremely fast connection, hardware mutual assistance, and resource sharing for multiple smart terminals that consumers come into contact with in full-scene life, and providing scenario experiences with the right devices.

On September 10, 2020, Huawei Harmony OS was upgraded to HarmonyOS version 2.0. on April 22, 2021, Huawei HarmonyOS application development online experience website was launched . on May 18, Huawei announced that Huawei HiLink will be unified with Harmony OS as Honmon SmartLink.

On the evening of June 2, 2021, Huawei officially released HarmonyOS 2 and several new products equipped with HarmonyOS 2. On July 29, the Huawei Sound X speaker was released, which is the first smart speaker equipped with HarmonyOS 2.

Translated with www.DeepL.com/Translator (free version)

**Comment by agnostic-apollo** [comment] 2021-10-10 12:34
Duplicate of #1750

**Closed by agnostic-apollo** 2021-10-10 12:34 UTC
