### ISSUE TITLE
Volume keys only control volume when some accessibility features are enabled on Android 11

### ISSUE THREAD

**Issue by townba** [termux/termux-app#1721] opened 2020-08-21 22:29 UTC
**Problem description**

When some accessibility features such as magnification or the accessibility menu are enabled on Android 11 Beta 3, using VolumeUp and VolumeDown for special keys no longer works. They only control volume. Disabling the features and switching back to Termux allows the special keys to work.

**Steps to reproduce**

0. Use a device with Android 11.
1. In system settings under **Accessibility**, enable **Magnification**.
2. In Termux, try to use VolumeDown+C (Ctrl+C). It will instead turn the volume down and type a C.
3. In system settings under **Accessibility**, disable **Magnification**.
4. In Termux, try to use VolumeDown+C (Ctrl+C). It will work as expected.
5. In system settings under **Accessibility -> Accessibility Menu**, enable **Accessibility Menu shortcut**.
6. In Termux, try to use VolumeDown+C (Ctrl+C). It will instead turn the volume down and type a C.

**Expected behavior**

Something like VolumeDown+C should always act as Ctrl+C in Termux.

**Additional information**

* Termux application version:
0.98
* Android OS version:
11 with August 5, 2020 security update (build RPB3.200720.005)
* Device model:
Pixel 2 XL (hardware version rev_10)

**Comment by jeffre** [comment] 2020-10-07 07:11
I'm also android 11 and experiencing the same problem. However the trigger for me occurs when I enable the "Torchie Quick" accessibility service which comes from the Torchie app https://play.google.com/store/apps/details?id=in.blogspot.anselmbros.torchie

**Comment by sihde** [comment] 2021-02-17 16:07
This also happens with AutoInput's accessibility service.

**Comment by agnostic-apollo** [comment] 2021-02-17 18:17
I don't think this is solvable. Accessibility services can consume key events before they reach the applications. They do this by declaring [`canRequestFilterKeyEvents`](https://developer.android.com/reference/android/accessibilityservice/AccessibilityServiceInfo.html#attr_android:canRequestFilterKeyEvents) for the accessibility service and use it if needed and handle key events by overriding the [`onKeyEvent()`](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService#onKeyEvent(android.view.KeyEvent)) function in the accessibility function. 

The `MagnificationService` is doing the same [here](https://cs.android.com/android/platform/superproject/+/android-11.0.0_r3:development/samples/ApiDemos/src/com/example/android/apis/accessibility/MagnificationService.java;l=59) and consumes both the `KEYCODE_VOLUME_UP` and `KEYCODE_VOLUME_DOWN` events, which is why termux never receives them to use them for the key shortcuts including `Ctrl`. I'm not sure exactly sure why the volume up/down actually happens in your case though, since it shouldn't be happening as mentioned in the comment.

I also checked the AutoInput's source and its obviously doing the same thing, likely only if the specific key is hocked into or suppressed, like with the AutoInput `Modes`plugin action.

**Comment by henrik-lindqvist** [comment] 2021-07-13 21:29
Likely cause: https://issuetracker.google.com/issues/163120692

**Comment by agnostic-apollo** [comment] 2021-07-14 06:03
@henrik-lindqvist thanks a lot for the link.

The comment for the likely reason is [here](https://issuetracker.google.com/issues/163120692#comment247) which suggests that fix should be available on android S. Google confirmed the fixed in the comment [here](https://issuetracker.google.com/issues/163120692#comment307) but did not provide info of the aosp commit.

The fix would likely still not fix the issue for magnifier or AutoInput service if they are consuming the volume event, but may fix it for some other cases.

Closing since this is (likely) not a `termux-app` issue.

**Closed by agnostic-apollo** 2021-07-14 06:03 UTC
Labels: bug report, help wanted

**Comment by bengalih** [comment] 2022-02-02 21:00
I ran into this issue on my Pixel 3XL running 11.
I use Volume Controls Panel (https://play.google.com/store/apps/details?id=leedroiddevelopments.volumepanel&hl=en_US&gl=US).
It needs accessibility service to show its volume GUIs.

It has a list of exclusions and having Termux on the exclusion list worked In Android 10 and allowed me to pass the volume keypress events directly to Termux.  However, last I tried on 11 instead of passing the keypresses, it only excludes Termux from working with the enhanced volume UI, instead I just get the normal system UI.

I got around this for now using a Tasker profile when entering and exiting the Termux app.
Upon launching Termux I run a command to disable the specific accessibility service causing the issue and when leaving the app I re-enable it.  The below are my command to do this for the volume app and it should be a good starting point for anyone else needing to do something similar:

Turn off a specific accessibility service:
`settings put secure enabled_accessibility_services $(settings get secure enabled_accessibility_services | sed -r 's/leedroiddevelopments.volumepanel\/leedroiddevelopments.volumepanel.services.QSAccService//g')`

Turn it back on:
`settings put secure enabled_accessibility_services $(settings get secure enabled_accessibility_services):leedroiddevelopments.volumepanel\/leedroiddevelopments.volumepanel.services.QSAccService`

For more info as to why I'm not just enabling/disabling one service and why you need to just pull/push the one you want (via the sed command), see the answer by bilabila here:

https://stackoverflow.com/questions/63066398/i-need-an-adb-command-to-enable-an-android-accesibility-option
