### ISSUE TITLE
Typed texts show up only after pressing space with SwiftKey keyboard. 

### ISSUE THREAD

**Issue by aasutossh** [termux/termux-app#1473] opened 2020-02-26 21:07 UTC
**Problem description**

As the title says. Some keyboards work though. 

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: 0.83
* Android OS version: 6.0
* Device model: Gionee F103 pro

**Comment by xeffyr** [comment] 2020-02-26 22:15
Duplicate of https://github.com/termux/termux-app/issues/686.

> Android OS version: 6.0

Android OS versions **5.x** and **6.x** are not supported since 01.01.2020.

**Closed by xeffyr** 2020-02-26 22:15 UTC

**Comment by aasutossh** [comment] 2020-02-27 14:16
Okay cool.
Thank you.
