### ISSUE TITLE
Terminal transcript

### ISSUE THREAD

**Issue by 1cmf** [termux/termux-app#3968] opened 2024-05-28 08:32 UTC
Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

~ $ pkg install clang cmake make
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://termux.mentality.rip/termux-main/: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
clang is already the newest version (18.1.6).
clang set to manually installed.
make is already the newest version (4.4.1).
make set to manually installed.
The following additional packages will be installed:
  jsoncpp libarchive libuv rhash
The following NEW packages will be installed:
  cmake jsoncpp libarchive libuv rhash
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 8367 kB of archives.
After this operation, 47.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://termux.mentality.rip/termux-main stable/main aarch64 libarchive aarch64 3.7.4 [386 kB]
Get:2 https://termux.mentality.rip/termux-main stable/main aarch64 jsoncpp aarch64 1.9.5-2 [95.0 kB]
Get:3 https://termux.mentality.rip/termux-main stable/main aarch64 libuv aarch64 1.48.0 [78.0 kB]
Get:4 https://termux.mentality.rip/termux-main stable/main aarch64 rhash aarch64 1.4.4 [154 kB]
Get:5 https://termux.mentality.rip/termux-main stable/main aarch64 cmake aarch64 3.29.3 [7655 kB]
Fetched 8367 kB in 5s (1807 kB/s)
Selecting previously unselected package libarchive.
(Reading database ... 24286 files and directories currently installed.)
Preparing to unpack .../libarchive_3.7.4_aarch64.deb ...
Unpacking libarchive (3.7.4) ...
Selecting previously unselected package jsoncpp.
Preparing to unpack .../jsoncpp_1.9.5-2_aarch64.deb ...
Unpacking jsoncpp (1.9.5-2) ...
Selecting previously unselected package libuv.
Preparing to unpack .../libuv_1.48.0_aarch64.deb ...
Unpacking libuv (1.48.0) ...
Selecting previously unselected package rhash.
Preparing to unpack .../rhash_1.4.4_aarch64.deb ...
Unpacking rhash (1.4.4) ...
Selecting previously unselected package cmake.
Preparing to unpack .../cmake_3.29.3_aarch64.deb ...
Unpacking cmake (3.29.3) ...
Setting up libuv (1.48.0) ...
Setting up rhash (1.4.4) ...
Setting up libarchive (3.7.4) ...
Setting up jsoncpp (1.9.5-2) ...
Setting up cmake (3.29.3) ...
~ $ LDFLAGS="-L/system/lib64" pip install brotli
Collecting brotli
  Using cached Brotli-1.1.0.tar.gz (7.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: brotli
  Building wheel for brotli (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for brotli (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating bin
      creating bin/lib.linux-aarch64-cpython-311
      copying python/brotli.py -> bin/lib.linux-aarch64-cpython-311
      running build_ext
      <string>:70: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
      building '_brotli' extension
      creating bin/temp.linux-aarch64-cpython-311
      creating bin/temp.linux-aarch64-cpython-311/python
      creating bin/temp.linux-aarch64-cpython-311/c
      creating bin/temp.linux-aarch64-cpython-311/c/common
      creating bin/temp.linux-aarch64-cpython-311/c/dec
      creating bin/temp.linux-aarch64-cpython-311/c/enc
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c python/_brotli.c -o bin/temp.linux-aarch64-cpython-311/python/_brotli.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/constants.c -o bin/temp.linux-aarch64-cpython-311/c/common/constants.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/context.c -o bin/temp.linux-aarch64-cpython-311/c/common/context.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/dictionary.c -o bin/temp.linux-aarch64-cpython-311/c/common/dictionary.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/platform.c -o bin/temp.linux-aarch64-cpython-311/c/common/platform.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/shared_dictionary.c -o bin/temp.linux-aarch64-cpython-311/c/common/shared_dictionary.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/common/transform.c -o bin/temp.linux-aarch64-cpython-311/c/common/transform.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/dec/bit_reader.c -o bin/temp.linux-aarch64-cpython-311/c/dec/bit_reader.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/dec/decode.c -o bin/temp.linux-aarch64-cpython-311/c/dec/decode.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/dec/huffman.c -o bin/temp.linux-aarch64-cpython-311/c/dec/huffman.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/dec/state.c -o bin/temp.linux-aarch64-cpython-311/c/dec/state.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/backward_references.c -o bin/temp.linux-aarch64-cpython-311/c/enc/backward_references.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/backward_references_hq.c -o bin/temp.linux-aarch64-cpython-311/c/enc/backward_references_hq.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/bit_cost.c -o bin/temp.linux-aarch64-cpython-311/c/enc/bit_cost.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/block_splitter.c -o bin/temp.linux-aarch64-cpython-311/c/enc/block_splitter.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/brotli_bit_stream.c -o bin/temp.linux-aarch64-cpython-311/c/enc/brotli_bit_stream.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/cluster.c -o bin/temp.linux-aarch64-cpython-311/c/enc/cluster.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/command.c -o bin/temp.linux-aarch64-cpython-311/c/enc/command.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/compound_dictionary.c -o bin/temp.linux-aarch64-cpython-311/c/enc/compound_dictionary.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/compress_fragment.c -o bin/temp.linux-aarch64-cpython-311/c/enc/compress_fragment.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/compress_fragment_two_pass.c -o bin/temp.linux-aarch64-cpython-311/c/enc/compress_fragment_two_pass.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/dictionary_hash.c -o bin/temp.linux-aarch64-cpython-311/c/enc/dictionary_hash.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/encode.c -o bin/temp.linux-aarch64-cpython-311/c/enc/encode.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/encoder_dict.c -o bin/temp.linux-aarch64-cpython-311/c/enc/encoder_dict.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/entropy_encode.c -o bin/temp.linux-aarch64-cpython-311/c/enc/entropy_encode.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/fast_log.c -o bin/temp.linux-aarch64-cpython-311/c/enc/fast_log.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/histogram.c -o bin/temp.linux-aarch64-cpython-311/c/enc/histogram.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/literal_cost.c -o bin/temp.linux-aarch64-cpython-311/c/enc/literal_cost.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/memory.c -o bin/temp.linux-aarch64-cpython-311/c/enc/memory.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/metablock.c -o bin/temp.linux-aarch64-cpython-311/c/enc/metablock.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/static_dict.c -o bin/temp.linux-aarch64-cpython-311/c/enc/static_dict.o
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -Ic/include -I/data/data/com.termux/files/usr/include/python3.11 -c c/enc/utf8_util.c -o bin/temp.linux-aarch64-cpython-311/c/enc/utf8_util.o
      aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -fno-openmp-implicit-rpath -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v3/sysroot/usr/lib -L/system/lib64 bin/temp.linux-aarch64-cpython-311/python/_brotli.o bin/temp.linux-aarch64-cpython-311/c/common/constants.o bin/temp.linux-aarch64-cpython-311/c/common/context.o bin/temp.linux-aarch64-cpython-311/c/common/dictionary.o bin/temp.linux-aarch64-cpython-311/c/common/platform.o bin/temp.linux-aarch64-cpython-311/c/common/shared_dictionary.o bin/temp.linux-aarch64-cpython-311/c/common/transform.o bin/temp.linux-aarch64-cpython-311/c/dec/bit_reader.o bin/temp.linux-aarch64-cpython-311/c/dec/decode.o bin/temp.linux-aarch64-cpython-311/c/dec/huffman.o bin/temp.linux-aarch64-cpython-311/c/dec/state.o bin/temp.linux-aarch64-cpython-311/c/enc/backward_references.o bin/temp.linux-aarch64-cpython-311/c/enc/backward_references_hq.o bin/temp.linux-aarch64-cpython-311/c/enc/bit_cost.o bin/temp.linux-aarch64-cpython-311/c/enc/block_splitter.o bin/temp.linux-aarch64-cpython-311/c/enc/brotli_bit_stream.o bin/temp.linux-aarch64-cpython-311/c/enc/cluster.o bin/temp.linux-aarch64-cpython-311/c/enc/command.o bin/temp.linux-aarch64-cpython-311/c/enc/compound_dictionary.o bin/temp.linux-aarch64-cpython-311/c/enc/compress_fragment.o bin/temp.linux-aarch64-cpython-311/c/enc/compress_fragment_two_pass.o bin/temp.linux-aarch64-cpython-311/c/enc/dictionary_hash.o bin/temp.linux-aarch64-cpython-311/c/enc/encode.o bin/temp.linux-aarch64-cpython-311/c/enc/encoder_dict.o bin/temp.linux-aarch64-cpython-311/c/enc/entropy_encode.o bin/temp.linux-aarch64-cpython-311/c/enc/fast_log.o bin/temp.linux-aarch64-cpython-311/c/enc/histogram.o bin/temp.linux-aarch64-cpython-311/c/enc/literal_cost.o bin/temp.linux-aarch64-cpython-311/c/enc/memory.o bin/temp.linux-aarch64-cpython-311/c/enc/metablock.o bin/temp.linux-aarch64-cpython-311/c/enc/static_dict.o bin/temp.linux-aarch64-cpython-311/c/enc/utf8_util.o -L/data/data/com.termux/files/usr/lib -lpython3.11 -o bin/lib.linux-aarch64-cpython-311/_brotli.cpython-311.so
      aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for brotli
Failed to build brotli
ERROR: Could not build wheels for brotli, which is required to install pyproject.toml-based projects
~ $

**Comment by twaik** [comment] 2024-05-28 08:34
Duplicate of termux-packages/issues/20039

**Comment by twaik** [comment] 2024-05-28 08:35
Duplicate of [termux-packages/issues/#20039](https://github.com/termux/termux-packages/issues/20039)

**Closed by twaik** 2024-05-28 08:34 UTC
