### ISSUE TITLE
Input Text not showing up, only when pressing space 

### ISSUE THREAD

**Issue by sebiTCR** [termux/termux-app#1726] opened 2020-08-24 13:56 UTC
**Problem description**

 I'm trying to type a command into Termux, but what I type doesn't shows up until I press space. (It's harder to use the app with this bug). I can use symbols (Like . , / \ |) but I can't see the letters until I put a symbol or space

**Steps to reproduce**

Type anything, and then press space to show the text

**Expected behavior**

Letters should appear when written

**Additional information**

* Termux application version: 0.98
* Android OS version: Android 10
* Device model: SM-G965F

**Comment by sebiTCR** [comment] 2020-08-24 13:58
Forgot to add the bug-report tag

**Comment by xeffyr** [comment] 2020-08-24 15:11
Duplicate of https://github.com/termux/termux-app/issues/686.

**Closed by xeffyr** 2020-08-24 15:11 UTC
