### ISSUE TITLE
[Bug]: apt install nodejs error

### ISSUE THREAD

**Issue by DoveBoy** [termux/termux-app#2711] opened 2022-04-13 03:26 UTC
### Problem description

apt install nodejs error, and `node` command error
![photo_2022-04-13_11-26-17](https://user-images.githubusercontent.com/19201447/163094150-33ba21a3-38d9-46ff-a01b-3ba0028eb352.jpg)

### Steps to reproduce the behavior.

`apt install nodejs`
`node`

### System information

* Termux application version:0.118
* Android OS version:12
* Device model:OPPO PEEM00

**Comment by Grimler91** [comment] 2022-04-13 04:42
Upgrade your packages, `pkg upgr`

**Comment by Grimler91** [comment] 2022-04-13 04:45
No, my bad, latest nodejs deb is missing from fosshost

**Comment by Grimler91** [comment] 2022-04-13 04:49
Duplicate of https://github.com/termux/termux-packages/issues/9996

**Closed by Grimler91** 2022-04-13 04:49 UTC
Labels: bug report
