### ISSUE TITLE
Terminal session falls when the battery is fully charged

### ISSUE THREAD

**Issue by garlapann** [termux/termux-app#1092] opened 2019-04-14 13:52 UTC
Hi! I am using Termux 0.66 on my Sony Xperia M Dual C2005. OS Android 6.0.1.

Noticed a very unpleasant bug:
The terminal session falls when the battery is fully charged. I mean, the session falls just when a notification of a full battery charge appears in the shutter. Wakelock is enabled.
Didn't check this when actively using the device at this point, but it happens almost always when the screen is off and the device is on charge.

**Comment by xeffyr** [comment] 2019-04-14 14:00
Having Termux running 24/7 with and without charger and never seen such "unpleasant bug".
Reminding that we cannot deal with ROM-specific behaviour, bugs and power managing "innovations".

Generally, this is duplicate of https://github.com/termux/termux-app/issues/122 which will be also closed if it will be confirmed that Android's `lowmemorykiller` does it's work in such way.

**Closed by xeffyr** 2019-04-14 14:00 UTC

**Comment by garlapann** [comment] 2019-04-14 14:13
Thank you for the response, a little later I will post a log from CatLog if it happens again with the running logging.
