### ISSUE TITLE
Unable to start activity...

### ISSUE THREAD

**Issue by GL513** [termux/termux-app#2763] opened 2022-05-07 12:49 UTC
### Problem description

[termux-crash_report.log](https://github.com/termux/termux-app/files/8645178/termux-crash_report.log)

Random crash after closing the foreground service.

### Steps to reproduce the behavior.

N/A

### What is the expected behavior?

Application doesnt crash...

### System information

Check the crash report file

**Comment by agnostic-apollo** [comment] 2022-05-07 13:51
Duplicate of https://github.com/termux/termux-app/issues/2552

Disable battery optimization for `termux-app`.

**Closed** 2022-05-07 13:51 UTC
Labels: bug report
