### ISSUE TITLE
vimdiff runs fail

### ISSUE THREAD

**Issue by rush3** [termux/termux-app#700] opened 2018-05-30 10:12 UTC
When run :vimdiff file1 file2,   fail with notes that E97: Cannot create diffs.

**Comment by Quasic** [comment] 2018-06-19 06:30
Duplicate of termux-packages#2528

```pkg in diffutils``` fixes it.

**Closed** 2018-06-19 07:59 UTC

**Comment by rush3** [comment] 2018-07-01 08:30
Thanks!  It works.
