### ISSUE TITLE
CANNOT LINK EXECUTABLE "libandroid-support.so" not found

### ISSUE THREAD

**Issue by dbabits** [termux/termux-app#1779] opened 2020-10-05 15:58 UTC
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: 0.101
* Android OS version:9
* Device model:

I read all similar issues, e.g. #1702 and the solution provided does not work. I'm getting ```sh: termux-upgrade-repo: not found```
Also, seems like normal utilities like ls are not available in failsafe mode, so cant really tell much: ```sh: ls: not found```
![Screenshot_20201005-115155](https://user-images.githubusercontent.com/2488222/95102504-78530300-0701-11eb-8e6b-0c2068ab5176.jpg)

**Comment by xeffyr** [comment] 2020-10-05 16:08
Support for legacy environment has been removed.

Duplicate of https://github.com/termux/termux-app/issues/1703 - see solution here.

**Closed by xeffyr** 2020-10-05 16:08 UTC

**Comment by xeffyr** [comment] 2020-10-05 16:10
https://github.com/termux/termux-app/issues/1703#issuecomment-680212634 - if you don't have termux-upgrade-repo

**Comment by xeffyr** [comment] 2020-10-05 16:11
> Also, seems like normal utilities like ls are not available in failsafe mode

Append to path, not override. Restart failsafe shell and:
```
export PATH=$PATH:/data/data/com.termux/files/usr/bin
```
