### ISSUE TITLE
[Feature]: Themed icon support

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [termux/termux-app#3329] opened 2023-04-05 16:04 UTC
### Feature description

Why not add support for the themed icon Android feature for a nice modern touch?

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

### Additional information

https://9to5google.com/2022/12/09/android-13-themed-icons/

**Comment by ctntt** [comment] 2023-04-09 22:30
Duplicate of https://github.com/termux/termux-app/issues/3271

**Closed** 2023-05-09 10:20 UTC
