### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GH05T-HUNTER5** [termux/termux-app#3010] opened 2022-09-29 14:05 UTC
### Problem description

Termux is not working well because of your new update

{
Picking mirror: https://deb.kcubeterm.me/termux-main
Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [507 B]
Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.
}

### Steps to reproduce the behavior.

Replace the new update code with the old one

Delete this {https://github.com/termux/termux-app/blob/master/termux-shared/src/main/java/com/termux/shared/settings/preferences/AppSharedPreferences.java}

### What is the expected behavior?

Proper package installation

### System information

* Termux application version:0.101
* Android OS version: 12
* Device model: RedMi9

**Comment by GH05T-HUNTER5** [comment] 2022-09-29 14:06
> ### Problem description
> Termux is not working well because of your new update
> 
> { Picking mirror: https://deb.kcubeterm.me/termux-main Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [507 B] Err:1 https://deb.kcubeterm.me/termux-main stable InRelease Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?) Reading package lists... Done E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?) E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed. N: Metadata integrity can't be verified, repository is disabled now. N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently. N: Please note that all hosting problems or other serious issues we announce on our social media pages. N: Use termux-change-repo for switching to a mirror. }
> 
> ### Steps to reproduce the behavior.
> Replace the new update code with the old one
> 
> Delete this {[https://github.com/termux/termux-app/blob/master/termux-shared/src/main/java/com/termux/shared/settings/preferences/AppSharedPreferences.java}](https://github.com/termux/termux-app/blob/master/termux-shared/src/main/java/com/termux/shared/settings/preferences/AppSharedPreferences.java%7D)
> 
> ### What is the expected behavior?
> Proper package installation
> 
> ### System information
> * Termux application version:0.101
> * Android OS version: 12
> * Device model: RedMi9

Please Fix This Error

**Comment by Grimler91** [comment] 2022-09-29 14:38
Duplicate of https://github.com/termux/termux-packages/issues/12208. See https://github.com/termux/termux-packages/issues/12208#issuecomment-1262324548.

**Closed by Grimler91** 2022-09-29 14:38 UTC
Labels: bug report
