### ISSUE TITLE
link system call - Permission denied

### ISSUE THREAD

**Issue by kisik21** [termux/termux-app#837] opened 2018-09-13 15:51 UTC
Android 8.0, Termux, Huawei Y6 Prime 2018, link() syscall, link program and everything using link gets permission denied to use the call.

Suspecting that seccomp filter blocks link(). Though an application should crash then...

Filesystem on /data is f2fs. Hardlinks on SD card don't work either, yielding the same Permission denied error.

**Comment by xeffyr** [comment] 2018-09-13 16:18
> Suspecting that seccomp filter blocks link().

@kisik21 SELinux does not allow usage of `link()` by regular applications.

The **only** solutions are:
1.  Use `proot --link2symlink {your application that use link()}` (package 'proot' needed), but this does not create hardlinks.
2. Patch your application so it will create symlinks instead of hardlinks.

**Comment by kisik21** [comment] 2018-09-13 16:33
Excerpts from Leonid Plyushch's message of September 13, 2018 7:20 pm:
>> Suspecting that seccomp filter blocks link().
> 
> @kisik21 SELinux does not allow usage of `link()` by regular applications.
> 

Is there a way to somehow make not symlinks, but copies with proot?

Or patch an app to do this? (is there a copy syscall? I can't find a 
manpage for it for some reason...)

**Comment by kisik21** [comment] 2018-09-13 18:38
Oh, apologies, I meant not a syscall, but a function in general. `sendfile()` probably might do what I meant, but I'm not diving into C code until I fail to get other methods to work.

`proot --link2symlink muchsync --init ~/Maildir sakura` fails with error: `proot info: vpid 1: terminated with signal 7`.

What might this mean? seems like this is SIGBUS, but I have no idea what this means.

**Comment by fornwall** [comment] 2018-09-23 15:01
@kisik21 Hi! I'm closing this issue as it isn't caused by the Termux app itself.

For getting help with proot, either open an issue at https://github.com/termux/proot/issues if you suspect an issue in proot, or ask for help on on the [Google+ community](https://plus.google.com/u/0/communities/101692629528551299417) or the [Gitter chat](https://gitter.im/termux/termux).

**Closed by fornwall** 2018-09-23 15:01 UTC

**Comment by jackzhp** [comment] 2020-01-23 07:23
with android 8(api 26), we have 

static Path Files.createLink(Path link, Path existing)

so the hard link should be available, isn't it?

**Comment by xeffyr** [comment] 2020-01-23 10:22
> static Path Files.createLink(Path link, Path existing)
so the hard link should be available, isn't it?

Yes, it is available but question not about availability (libc has necessary functions too).

Hard links are disallowed by SELinux as part of security hardening (yes, hardlinks provide certain file-related attack vectors). Your suggestion about `Files.createLink()` is not allowed for regular applications too, it just throws
```
java.nio.file.AccessDeniedException
```
Another thing is that Termux packages do not use Java API.
