### ISSUE TITLE
[Bug]: exec("/data/data/com.termux/files/usr/bin/login"): Permission denied  [Process completed (code 1) - press Enter]

### ISSUE THREAD

**Issue by egghuntGuuu** [termux/termux-app#3224] opened 2023-02-01 13:57 UTC
### Problem description

exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

### Steps to reproduce the behavior.

exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

### What is the expected behavior?

exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by 2096779623** [comment] 2023-02-01 14:01
Duplicate of https://github.com/termux/termux-packages/issues/7369 .

**Closed by 2096779623** 2023-02-01 14:01 UTC
Labels: bug report

**Comment by Sampleritguthub** [comment] 2023-02-01 20:59
Hello?? Sent from my Huawei phone-------- Original message --------From: Kevin Williams ***@***.***>Date: Wed, 01 Feb 2023, 16:02To: termux/termux-app ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [termux/termux-app] [Bug]: exec("/data/data/com.termux/files/usr/bin/login"): Permission denied  [Process completed (code 1) - press Enter] (Issue #3224)
Duplicate of termux/termux-packages#7369 .
