### ISSUE TITLE
[Bug]: Android 11 My Termux crashes when my device is turned off

### ISSUE THREAD

**Issue by MuhammadRestu999** [termux/termux-app#2741] opened 2022-04-26 10:51 UTC
### Problem description

My Termux crashes when my device is turned off

## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2022-04-26 10:37:21.018 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2022-04-26 10:31:39.120 UTC`  

**Crash Message**:
```
Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{35f847e u0a885 TPSL idle change:idle|cached procs:1 seq(0,0,0)}
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.termux/com.termux.app.TermuxActivity}: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{35f847e u0a885 TPSL idle change:idle|cached procs:1 seq(0,0,0)}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3730)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2323)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.termux/.app.TermuxService }: app is in background uid UidRecord{35f847e u0a885 TPSL idle change:idle|cached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1770)
	at android.app.ContextImpl.startService(ContextImpl.java:1702)
	at android.content.ContextWrapper.startService(ContextWrapper.java:730)
	at com.termux.app.TermuxActivity.onCreate(TermuxActivity.java:242)
	at android.app.Activity.performCreate(Activity.java:8151)
	at android.app.Activity.performCreate(Activity.java:8135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
	... 11 more

```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.19.127-02133-g3583f2e-dirty`  
**SDK_INT**: `30`  
**RELEASE**: `11`  
**ID**: `RP1A.200720.011`  
**DISPLAY**: `RMX2189_11_C.06`  
**INCREMENTAL**: `1621502313319`  
**SECURITY_PATCH**: `2021-08-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `realme`  
**BRAND**: `realme`  
**MODEL**: `RMX2189`  
**PRODUCT**: `RMX2189T2`  
**BOARD**: `oppo6765`  
**HARDWARE**: `mt6765`  
**DEVICE**: `RMX2189`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

### Steps to reproduce the behavior.

1. Open termux as usual
2. Turn off the device because it is not in use
3. Turn on device
4. Termux crash

### What is the expected behavior?

1. Open termux as usual
2. Turn off the device because it is not in use
3. Turn on device
4. Nothing happened

### System information

* Termux application version: 0.118.0
* Android OS version: 11
* Device model: Realme C12 RMX2189

**Comment by dontknowhy** [comment] 2022-04-28 11:44
Bad background process management for Android 
You can try ```
termux-wake-lock
``` to allow Termux runs in the background.
If it still crash.
You must check you device settings.
I don't have realme device.So i can't tell you how to change the settings.
:(

**Comment by wmcbtech30** [comment] 2022-04-28 12:16
Realme uses ColorOS so i assume you have to go to Termux app info > Battery usage > Allow both foreground and background usage

**Comment by MuhammadRestu999** [comment] 2022-05-03 03:01
i have tried using ```termux-wake-lock``` and allow foreground & background usage but nothing happens

**Comment by agnostic-apollo** [comment] 2022-05-06 08:31
Duplicate of #2552

Disable battery optimization for `termux-app`.

**Closed by agnostic-apollo** 2022-05-06 08:31 UTC
Labels: bug report
