### ISSUE TITLE
termux don't work after updated to 0.105 (Android 10)

### ISSUE THREAD

**Issue by mehdiMj-ir** [termux/termux-app#1896] opened 2021-01-21 12:59 UTC
installations running on **Huawei Nova 7i** Android 10 EMUI 10.1.0 (witch does not support Google play services)
**Problem description**
after update to 0.105 from F-Droid, application don't work and don't even show the shell!

**Steps to reproduce**
I tried to clear cache, clear data and even restart my phone 😅, but the app don't work.

**Expected behavior**

A gif explains 1000 words
![5976_1](https://user-images.githubusercontent.com/20270329/105354312-9f2c3b00-5c05-11eb-99bc-7e9181dac1d1.gif)

**Comment by Grimler91** [comment] 2021-01-21 13:12
Yeah, this is my fault. Fixed in https://github.com/termux/termux-app/commit/05bb399893994d6cd596687fa7b4fedc294ef2b4, which was released as 0.106 but which is not available yet.

**Comment by Grimler91** [comment] 2021-01-21 13:20
If you are rooted you can `touch /data/data/com.termux/files/home/.termux/termux.properties` from and adb shell, or another terminal app, as a workaround

**Comment by NoseyNick** [comment] 2021-01-21 13:36
+1, same issue, same symptoms, except Android 8.1.0.

F-Droid also won't let me downgrade, but will let me completely uninstall, then carefully reinstall 0.104. This does require losing all my data (EG SSH keys and stuff) and starting again from scratch, but luckily I have ALMOST entirely scripted that   😐 

Look forward to 0.106   👍

**Comment by bglover** [comment] 2021-01-21 14:45
> If you are rooted you can `touch /data/data/com.termux/files/home/.termux/termux.properties` from an adb shell, or another terminal app, as a workaround

I can confirm that this workaround fixed the issue for me, thanks!

**Comment by Massedil** [comment] 2021-01-21 14:58
I had to create the directory `.termux` before :

```
mkdir /data/data/com.termux/files/home/.termux
touch /data/data/com.termux/files/home/.termux/termux.properties
```

I can confirm after that termux works again. Thanks.

**Comment by Grimler91** [comment] 2021-01-21 15:07
After you all have upgraded to v0.106 it is good idea to restore the owner and permissions of the `/data/data/com.termux/files/home/.termux` folder, which can done by moving the folder to /sdcard and back, first run as root: 

```
mv /data/data/com.termux/files/home/.termux /sdcard/
```

and then as the normal termux user: 

```
mv /sdcard/.termux /data/data/com.termux/files/home/.termux
```

(`chown` + `/system/bin/restorecon` should work as well but I have had problems with that on some ROMs so I usually do this instead)

**Comment by angelog0** [comment] 2021-01-21 20:22
Same issue here after the upgrade this evening. I can confirm that trying to revert to 0.104 does not work (`App is not installed`) 

I am not rooted so it seems that for me do not exist workarounds...

Sure that waiting for 0.106 will fix it? I can just wait..

**Comment by ojz0r** [comment] 2021-01-21 21:04
Had this problem as well.

Luckily Termux Float still works so you can use it with Grimler91's fix (touch /data/data/com.termux/files/home/.termux/termux.properties) and get it to work.

**Comment by xeffyr** [comment] 2021-01-21 23:09
> Luckily Termux Float still works

Yeah, Float add-on works because uses outdated copy of `terminal-view` component of Termux.

**Comment by dacuki** [comment] 2021-01-22 05:16
Just updated recently and came here for this bug. My phone are not rooted, luckily I already mount termux "home" dir as and external storage with [Material Files](https://f-droid.org/packages/me.zhanghai.android.files) that I used to move my script from internal storage before updating termux via F-droid, then use this [fix](https://github.com/termux/termux-app/issues/1896#issuecomment-764638027).

**Comment by Grimler91** [comment] 2021-01-22 07:39
@angelog0 

> Sure that waiting for 0.106 will fix it? I can just wait..

Yeah, just installing 0.106 will give you a working app again, and all your files and everything will still be there

**Comment by angelog0** [comment] 2021-01-22 14:33
@Grimler91, maybe you have to contact F-Droid people to stop the release of this buggy version otherwise this thread will increase....

**Comment by gerazo** [comment] 2021-01-22 14:44
The shit also hit the fan on Android 7. I see that 0.105 came to f-droid yesterday while 0.105 was committed 16 days ago. How much time does it take for f-droid to deploy a new release? (Why is it so slow?)

**Comment by xeffyr** [comment] 2021-01-22 16:05
> How much time does it take for f-droid to deploy a new release? (Why is it so slow?)

APKs are built by F-Droid. Sometimes its build environment doesn't have necessary versions of dependencies and as result builds are delayed a lot.

**Comment by trenttobler** [comment] 2021-01-23 17:07
I hit this as well, while trying to migrate from play store version to f-droid version (android 9).  Maybe until fixed (new) release is available, or the buggy version removed on f-droid, it may be worth mentioning in the wiki page referenced by the play store version, noting the 0.105 version should be avoided.

**Comment by agnostic-apollo** [comment] 2021-01-23 22:21
A non-root solution would be to use [Storage Access Framework (SAF)](https://wiki.termux.com/wiki/Internal_and_external_storage) to manually create the `~/.termux` directory and the `~.termux/termux.properties` file. First install Termux `v0.106` if you already haven't and let it run its `Installing` stage, it will automatically crash afterwards. Then open your system `Files` app (or custom file manager) and use its `SAF` opener to open `Termux` provider, likely in the left sidebar. Then from options (3 dots on top right), enable show hidden files, then create the `.termux` directory with the `Add Folder` option. The system `Files` app likely won't have an option to create an empty file. So use [QuickEdit](https://play.google.com/store/apps/details?id=com.rhmsoft.edit) (or other text editor or your custom file manager app) and save a new file named `termux.properties` in `/storage/emulated/0/` and then copy it to  `.termux` directory with the `Files` app. Then open Termux.

 Since [v0.104](https://github.com/termux/termux-app/pull/1856) fixed the hidden files issue, the `~/.termux` directory should show in `SAF`.

Working on A11 avd.

**Comment by angelog0** [comment] 2021-01-23 22:29
> the 0.105 version should be avoided

Removed... Wouldn't people be discouraged from installing an app that doesn't work?

Hi @agnostic-apollo, you write about `v. 0.106`.. maybe you meant `. 0.105`... @Grimler91 wrote `v. 0.106` will fix this issue..

**Comment by agnostic-apollo** [comment] 2021-01-23 22:32
right, sorry, editing.

**Comment by ford04** [comment] 2021-01-23 22:37
@angelog0 exactly described my situation. Had already dropped the app, until I luckily discovered this issue.

**Comment by angelog0** [comment] 2021-01-23 23:12
@Grimler91, many (Android) apps on GitHub have the binary packages in `Releases` section. Why you do not add the apk package of Termux?

Is there some alternative repo from which to download the apk for `v. 0.106` (F-Droid equivalent)? 

The risk is that we have to wait some month before we came back to use Termux unless we rooted the device or follow the @agnostic-apollo suggestions (which, really, I do not understand; maybe they have to be explained with more details for people not so much familiar with Android).

**Comment by agnostic-apollo** [comment] 2021-01-23 23:24
F-Droid delays are usually a few days and not months.

What exactly don't you understand and what have you tried till now?

**Comment by xeffyr** [comment] 2021-01-24 00:00
> Why you do not add the apk package of Termux?

Would be a fourth (currently Google Play, F-Droid and Nethunter Store) installation source with *another* incompatible signature. APKs can be provided on Github as soon as @fornwall  either share his signature key used for Google Play or purge EOLed builds from it.

Otherwise there will be a mess from lots of same apks but incompatible with each other due to signature.
Otherwise

**Comment by xeffyr** [comment] 2021-01-24 00:03
Someone who really needs v0.106, can open a related [Github Actions](https://github.com/termux/termux-app/runs/1717529189) and download needed version: https://github.com/termux/termux-app/suites/1845709433/artifacts/35744160

As I wrote in comment above, signature is different. Uninstall add-ons and older app before using this.

**Comment by ailin-nemui** [comment] 2021-01-24 09:06
you may have luck downgrading from a computer with `adb install -d -r com.termux_104.apk` without root

**Comment by angelog0** [comment] 2021-01-24 09:59
@ailin-nemui, what we need to run that command. Please, describe the method step by step..

**Comment by abdullah3102** [comment] 2021-01-24 11:06
> installations running on **Huawei Nova 7i** Android 10 EMUI 10.1.0 (witch does not support Google play services)
> **Problem description**
> after update to 0.105 from F-Droid, application don't work and don't even show the shell!
> 
> **Steps to reproduce**
> I tried to clear cache, clear data and even restart my phone 😅, but the app don't work.
> 
> **Expected behavior**
> 
> A gif explains 1000 words
> ![5976_1](https://user-images.githubusercontent.com/20270329/105354312-9f2c3b00-5c05-11eb-99bc-7e9181dac1d1.gif)

Please. Reset your factory data.

**Comment by abdullah3102** [comment] 2021-01-24 11:06
Please brother. Reset factory data just now.

**Comment by WMCB-Tech** [comment] 2021-01-24 11:08
@abdullah3102 Why needing to factory reset if workarounds are posted above?

**Comment by alephalpha0** [comment] 2021-01-24 23:48
> open your system `Files` app (or custom file manager) and use its `SAF` opener to open `Termux` provider, likely in the left sidebar.
> Then from options (3 dots on top right), enable show hidden files, then create the `.termux` directory with the `Add Folder` option. Then use [QuickEdit](https://play.google.com/store/apps/details?id=com.rhmsoft.edit) (or other text editor or your custom file manager app) and save a new file named `termux.properties` 
> Then open Termux.
  
> [v0.104](https://github.com/termux/termux-app/pull/1856) fixed the hidden files issue

I'm bored so I made a gif showing the steps to add termux as a connected storage and create directories and blank files through SAF via FX and Material Files.
`FX :: flow` 
![fxSAFTermux](https://user-images.githubusercontent.com/64208788/105647597-532eff80-5e6c-11eb-8f43-c339470c64af.gif)

**Comment by lars-vom-mars-x** [comment] 2021-01-25 08:40
@alephalpha0, many thanks. I didn't know how to get to termux's $HOME. Thanks for the pictures.

**Comment by angelog0** [comment] 2021-01-27 13:16
Version `v. 0.106` has been released on F-Droid sire and it fixes the issue discussed here...

**Comment by kcubeterm** [comment] 2021-01-27 13:28
@angelog0 if not found then create it. 

Closing as latest version has released.

**Closed by kcubeterm** 2021-01-27 13:28 UTC
Labels: bug report, information

**Comment by NoseyNick** [comment] 2021-01-27 13:31
> Version v. 0.106 has been released on F-Droid site and it fixes the issue discussed here...

Confirmed. YAY! Thanks!   :man_dancing: 

> BTW, in my home I do not find a .termux directory:

Me neither... Until I heard (too late) that it might be safest to touch the config file.
I think I have to assume there are some preferences we could set?   :laughing:

**Comment by xeffyr** [comment] 2021-01-27 14:32
> I think I have to assume there are some preferences we could set?

As shown in https://wiki.termux.com/wiki/Terminal_Settings

**Comment by angelog0** [comment] 2021-01-27 14:39
>  if not found then create it

OK, but empty? Really Termux to work needs this empty folder?

For what I understand this folder should contain a file with personal preferences of the user (`termux.properties`)... And if I have not preferences but just want/accept the default?

**Comment by Grimler91** [comment] 2021-01-27 15:23
> OK, but empty? Really Termux to work needs this empty folder?

You do not need it, it is just for optional changes/fixes. If you are happy with for example the default extra-keys layout then there is no reason for creating it.

The app crashed without the termux.properties file because I messed up the check for if the file exists. Without the file default settings are used by the terminal.

**Comment by snug** [comment] 2021-02-02 01:53
@Grimler91 

Hello Henrik, have recorded a voice message for you - https://voca.ro/1fEROzpW1pLh xoxo

**Comment by tallship** [comment] 2021-02-06 03:41
Hi @Grimler91 :)

Hey I considered opening up an issue to address this question, but decided to just ping you here (at least first, to glean your opinion first) because it might open up a volley of commenting that just results in unneccessary noise, distracting you dev's from focusing on important things like, um... development of Termux and hanging out with your families ;)

Anyway, have you given much thought to this?

https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/

It could do a couple of things:

* Beta / Dev versions could be available to those who choose to help test or be early adopters instead of having to  d/l and install apks from the git repo here.
* Quick fixes could be as quickly deployed as when you discover the fixes, instead of having to wait on the limited time resources of F-Droid staff members, as well meaning as they may be.

If you'd prefer I open an issue just lemme know as I don't have a problem doing so, but this is a bit more informal I think, and not (usually) that important of an issue.

**Comment by Grimler91** [comment] 2021-02-06 06:48
@tallship Hi,

For testing purposes a custom F-droid repository would come in handy. Using it as the main distribution path would be inconvenient for users though as they then have to first install a new app (fdroid) and then manually add another repository in that app. 

If we set up a custom repository those apps also have to be signed with a different key than the apps on the main fdroid repo or on google play, meaning that users cannot simply try out the development version and then switch back, at least not without uninstalling termux fully in between (and loosing all data). We have have few issues being opened every now and then where people try to mix installation sources and become confused about the non-informative error message that is shown in this case.

All-in-all I think setting up a custom fdroid repository creates more inconveniences for users than it solves for us. Maybe others have other opinions.

**Comment by NoseyNick** [comment] 2021-02-07 03:38
> would be inconvenient for users though as they then have to first install a new app (fdroid) and then manually add another repository in that app

I thought f-droid was the **normal** way to install Termux, personally   :laughing:

**Comment by AnonymousxHacker** [comment] 2021-05-22 02:41
Hi.
Trying to transition from PlayStore Termux to Termux Fdroid Version.

And after downloading version .108 .I have tried to install the apk and it says 'App Not Installed'.Can anyone help me solve this issue.Thanks

Hardware: Android 8.0 armvl
if the hardware is compatible it may be the software my phone uses.
