### ISSUE TITLE
Numeric keyboard invoked instead of Textual Keyboard

### ISSUE THREAD

**Issue by Chidhambararajan** [termux/termux-app#1255] opened 2019-09-20 06:28 UTC
**Problem description**
When I use contacts app before termux or any app which just uses number input (like pin lock) ,the keyboard which shows up in termux is a numerical keyboard instead of a normal textual keyboard. To fix it I need to put the termux in background mode and open an app which opens textual keyboard , and then comeback to termux to use it..

It seems like termux relies on the keyboard mode choice of the previous app in the activity than it's own..  is there anyway to fix this issue??

**Steps to reproduce**
Grab  a Samsung phone with Samsung keyboard enabled, open any app which invokes numeric keyboard ,type something and close the app. Now open termux .

**Expected behavior**
Termux now invokes numeric keyboard instead of textual keyboard which is not desired

**Bug ScreenShot**
![](https://i.imgur.com/DZkfDjj.jpg)

**Termux-info output**
Updatable packages:
bash/stable 5.0.11 aarch64 [upgradable from: 5.0.7-5]
busybox/stable 1.30.1-9 aarch64 [upgradable from: 1.30.1-7]
ca-certificates/stable 20190828 all [upgradable from: 20190515]
clang/stable 8.0.1-2 aarch64 [upgradable from: 8.0.1]
cmake/stable 3.15.3 aarch64 [upgradable from: 3.15.2-1]
coreutils/stable 8.31-8 aarch64 [upgradable from: 8.31-7]
curl/stable 7.66.0 aarch64 [upgradable from: 7.65.3-6]
dash/stable 0.5.10.2-2 aarch64 [upgradable from: 0.5.10.2-1]
findutils/stable 4.7.0 aarch64 [upgradable from: 4.6.0-4]
gawk/stable 5.0.1-4 aarch64 [upgradable from: 5.0.1-3]
libandroid-support/stable 25-2 aarch64 [upgradable from: 25-1]
libcurl/stable 7.66.0 aarch64 [upgradable from: 7.65.3-6]
libexpat/stable 2.2.8 aarch64 [upgradable from: 2.2.7-1]
libgcrypt/stable 1.8.5 aarch64 [upgradable from: 1.8.4-1]
libiconv/stable 1.16-3 aarch64 [upgradable from: 1.16-2]
libllvm/stable 8.0.1-2 aarch64 [upgradable from: 8.0.1]
libnghttp2/stable 1.39.2 aarch64 [upgradable from: 1.39.1-1]
libuv/stable 1.32.0-1 aarch64 [upgradable from: 1.31.0]
ndk-sysroot/stable 20-4 aarch64 [upgradable from: 20-1]
openssl/stable 1.1.1d aarch64 [upgradable from: 1.1.1c-2]
openssl-tool/stable 1.1.1d aarch64 [upgradable from: 1.1.1c-2]
readline/stable 8.0.1 aarch64 [upgradable from: 8.0-3]
termux-tools/stable 0.71 all [upgradable from: 0.69-2]
unzip/stable 6.0-5 aarch64 [upgradable from: 6.0-4]
vim/stable 8.1.2050 aarch64 [upgradable from: 8.1.1850]
vim-runtime/stable 8.1.2050 all [upgradable from: 8.1.1850]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.111-16052094 #1 SMP PREEMPT Thu Jun 20 15:19:53 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-M205F

**Comment by Grimler91** [comment] 2019-09-20 06:42
Happens to me too. Might be another issue open with the same problem. 

Sidenote: to change to the textual keyboard you can also flip the screen to change to landscape/portrait mode and then flip it back

**Comment by xeffyr** [comment] 2019-09-20 09:19
That's known **Samsung-specific** issue.
And duplicate of https://github.com/termux/termux-app/issues/706.

**Closed by xeffyr** 2019-09-20 09:19 UTC
