### ISSUE TITLE
[Bug]: `apt update` or `pkg update` doesn't work

### ISSUE THREAD

**Issue by lua-rocks** [termux/termux-app#2909] opened 2022-07-28 00:33 UTC
### Problem description

`apt update` or `pkg update` doesn't work

### Steps to reproduce the behavior.

Run `apt update` or `pkg update`

Get error:

```
Get:1 https://deb.kcubeterm.me/termux-main stable InRelease [507 B]
Err:1 https://deb.kcubeterm.me/termux-main stable InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists... Done
E: Failed to fetch https://deb.kcubeterm.me/termux-main/dists/stable/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://deb.kcubeterm.me/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.
```

### System information

* Termux application version: termux-app_v0.118.0+github-debug_universal.apk
* Android OS version: 9
* Device model: ZTE Blade A3 2020

**Comment by agnostic-apollo** [comment] 2022-07-28 00:35
Duplicate of #2874

**Closed by agnostic-apollo** 2022-07-28 00:35 UTC
Labels: bug report

**Comment by lua-rocks** [comment] 2022-07-28 00:58
I have no idea why default repos wasn't selected by default but after switching using `termux-change-repo` command everything works fine.

**Comment by agnostic-apollo** [comment] 2022-07-28 01:01
If on fresh install, you only used `apt`, then default repo would have been used, but if you used `pkg` even once, then [weight based repo selection](https://github.com/termux/termux-packages/blob/058b1c7ad40f081f450b3f71c807f22806b4264f/packages/termux-tools/pkg#L101` would have been done to change repo.

**Comment by 2096779623** [comment] 2022-07-28 01:02
> I have no idea why default repos wasn't selected by default but after switching using `termux-change-repo` command everything works fine.

https://github.com/termux/termux-packages/issues/10647

**Comment by lua-rocks** [comment] 2022-07-28 01:02
Ok, thanks!
