### ISSUE TITLE
Termux Crash while try to open 0.105 on android 7 Vivo V5

### ISSUE THREAD

**Issue by DXR101** [termux/termux-app#1897] opened 2021-01-21 23:01 UTC
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by xeffyr** [comment] 2021-01-21 23:06
v0.105 is broken.

Duplicate of https://github.com/termux/termux-app/issues/1896.

**Closed by xeffyr** 2021-01-21 23:06 UTC
