### ISSUE TITLE
Termux generate many "WARNING: linker" on each command execution

### ISSUE THREAD

**Issue by Symbian9** [termux/termux-app#1004] opened 2019-01-30 16:44 UTC
**Problem description**

During executing any command in Termux many warnings "WARNING: linker..." shown
 
**Steps to reproduce**

Execute any command in Termux.

**Expected behavior**

There should be no such warnings if all work as expected.

**Additional information**

Version(s) tested: `0.65`; `0.66`

```
$ pkg install
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease
Get:3 https://dl.bintray.com/xeffyr/unstable-packages unstable Release [6065 B]
Hit:3 https://dl.bintray.com/xeffyr/unstable-packages unstable Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
9 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
```

**Comment by xeffyr** [comment] 2019-01-30 16:53
Duplicate of https://github.com/termux/termux-packages/issues/2846.

**Closed** 2019-01-30 16:54 UTC
Labels: duplicate
