### ISSUE TITLE
[Bug]: Can't use rsync - "cannot locate symbol "locale_charset"

### ISSUE THREAD

**Issue by closewall** [termux/termux-app#3145] opened 2022-12-16 06:06 UTC
### Problem description

I am trying to use rsync on Termux.

I installed it, but whenever I try to run any kind of rsync command, I get this error message:

`CANNOT LINK EXECUTABLE "rsync": cannot locate symbol "locale_charset" referenced by "/data/data/com.termux/files/usr/bin/rsync"...`

I looked the problem up, and found no reliable solution.

### Steps to reproduce the behavior.

1. pkg install rsync
2. Type "rsync"

### What is the expected behavior?

It should provide usage instructions.

### System information

* Termux application version: 0.118.0
* Android OS version: 13
* Device model: Google Pixel 6
* ROM: GrapheneOS

**Comment by 2096779623** [comment] 2022-12-16 13:48
Not reproducible on my device (Android 10):
```bash
$ rsync --list-only rsync://mirrors.utermux.dev
termux
~ $ rsync --version
rsync  version 3.2.7  protocol version 31
Copyright (C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    no socketpairs, symlinks, symtimes, hardlinks, no hardlink-specials,
    no hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, no ACLs,
    no xattrs, optional secluded-args, iconv, prealloc, stop-at, no crtimes
Optimizations:
    no SIMD-roll, no asm-roll, openssl-crypto, no asm-MD5
Checksum list:
    md5 md4 sha1 none
Compress list:
    zstd lz4 zlibx zlib none
Daemon auth list:
    sha512 sha256 sha1 md5 md4

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
~ $
```

**Comment by anilatx** [comment] 2022-12-16 19:44
I am experiencing the same.

Termux application version: 0.118.0
Android OS version: 12
Device model: Samsung S10
ROM: (vanilla)

**Comment by Haiz14** [comment] 2022-12-23 12:54
You should close it since the problem is over.

**Closed** 2022-12-24 00:41 UTC
Labels: bug report

**Comment by QkiZMR** [comment] 2023-01-16 23:45
Same problem here.

Termux version: 0.118.0
Android OS: 12
Device: Motorola G100
ROM: stock

Any way to debug this? Any other command is working fine.

**Comment by karlicoss** [comment] 2023-02-22 02:47
Had the same issue on Pixel 7 (Android 13) -- fixed by running `pkg install libiconv`

**Comment by fragtion** [comment] 2023-02-28 21:55
> Had the same issue on Pixel 7 (Android 13) -- fixed by running `pkg install libiconv`
Same problem here on stock termux install installed via F-Droid on WSA (Windows Subsystem for Android). Resolved with libiconv, thanks!
