### ISSUE TITLE
Cannot use mercurial

### ISSUE THREAD

**Issue by Yajo** [termux/termux-app#22] opened 2015-11-28 18:31 UTC
I keep on getting amazed by this app. I'm trying to use mercurial, I installed it by:

```
apt install python2 python2-dev gcc
pip2 install mercurial
```

It works! But then:

```
$ hg help
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/hg", line 41, in <module>
    mercurial.util.setbinary(fp)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mercurial/demandimport.py", line 130, in __getattribute__
    self._load()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mercurial/demandimport.py", line 96, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mercurial/util.py", line 33, in <module>
    cachestat = platform.cachestat
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mercurial/demandimport.py", line 130, in __getattribute__
    self._load()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mercurial/demandimport.py", line 96, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mercurial/posix.py", line 32, in <module>
    oslink = os.link
AttributeError: 'module' object has no attribute 'link'
```

I'm not sure if I did something wrong, if it is Termux bug, Mercurial's, or if the fix would be a Mercurial package. Any help please?

**Comment by fornwall** [comment] 2015-11-29 00:53
The root cause is that the python2 package is compiled without os.link support, since hard links are not supported on Android (starting in Android version 6). This causes the line `oslink = os.link` to fail with the above exception.

- Adding back os.link (as a method which would would not work on Android 6) would unfortunately cause `pip` to break, see https://github.com/termux/termux-packages/issues/29.
- If mercurial was changed to work without os.link (at least on Android) that would be great, but probably not very likely to be accepted by the mercurial project.

Does changing the line `oslink = os.link` to something like `oslink = os.symlink` in `$PREFIX/lib/python2.7/site-packages/mercurial/posix.py` cause mercurial to run (with basic functionality such as cloning and pushing working)?

**Comment by Yajo** [comment] 2015-12-01 18:15
I think symlinks are more error-prone than just copying (that's what AFAIK mercurial does in Windows), so I added:

```
[...]
import shutil
[...]
oslink = shutil.copy2
[...]
```

And it works like a charm!

**Comment by fornwall** [comment] 2015-12-01 19:58
Great work reporting it to mercurial! I'll look into how much work it would be to package mercurial with this patch (otherwise I'll add a note about the manual patching steps needed when installing from pip in an upcoming collection of help pages)!

**Comment by fornwall** [comment] 2015-12-01 19:59
A reference for the removed hard links support in Android 6 is https://code.google.com/p/android-developer-preview/issues/detail?id=3150

**Comment by durin42** [comment] 2015-12-01 20:04
Please DO NOT package mercurial with symlinks replacing hardlinks. Copies are fine, that's what we'll fall back to anyway.

FWIW, I've mailed a fix for this to our list, and it should get reviewed in the next few days, at which point I'd really appreciate someone testing it (I'm not sure how to test it myself.)

**Comment by fornwall** [comment] 2015-12-01 20:43
@durin42 Yes, let's forget I ever mentioned symlinks as fallbacks :).

Great, let us know here if you want us to help testing a patch (and perhaps write down instructions/steps for anything special to be tested)!

If you want to test anything yourself, install the Termux app, and then install required packages by executing

    apt install python2-dev gcc

You should now be able to install mercurial with

    pip2 install mercurial

**Comment by durin42** [comment] 2015-12-08 00:38
Alrighty, if someone could test http://selenic.com/hg (if a zip is easier: https://selenic.com/hg/archive/42aa0e570eaa.zip) and let me know if it works, I'd greatly appreciate it.

Thanks!

**Comment by fornwall** [comment] 2015-12-11 23:48
@durin42 Nice work! I built mercurial with `make local` and verified that basic cloning, pushing, committing, pulling and pushing works.

Do you have an estimate for which version this would be available in mercurial (and when)?

**Comment by durin42** [comment] 2015-12-12 01:10
The patch is on our default branch for our next major release, which will be on February 1, 2016. The patch should apply to the stable branch, so if you want you can point people at a custom zip that has that applied for now.

(https://www.mercurial-scm.org/wiki/TimeBasedReleasePlan if you're curious)

**Comment by fornwall** [comment] 2015-12-12 01:21
Ok, interested people can apply https://selenic.com/repo/hg/rev/b0d90fef16b6 to `$PREFIX/python2.7/site-packages/mercurial/posix.py` after installing mercurial through pip in the meantime.

Thanks for the help!

**Closed by fornwall** 2015-12-12 01:21 UTC

**Comment by Yajo** [comment] 2015-12-15 18:48
Works perfectly. Anybody interested can run `pip2 install https://selenic.com/hg/archive/42aa0e570eaa.zip` (add `--upgrade` if you had a previous version).

**Comment by fornwall** [comment] 2015-12-16 01:28
@Yajo That's great! Didn't know that you could point pip to the zip file directly.
