### ISSUE TITLE
Add android.permission.READ_LOGS

### ISSUE THREAD

**Issue by henrik-lindqvist** [termux/termux-app#1821] opened 2020-11-17 06:52 UTC
Please add `<uses-permission android:name="android.permission.READ_LOGS" />` to the `AndroidManifest.xml`. It's a "development" permission which can be granted to via ADB, no root required, so the `logcat` command can print messages logged from all processes.

**Comment by Grimler91** [comment] 2020-11-17 10:17
Duplicate of https://github.com/termux/termux-app/issues/873

**Closed by Grimler91** 2020-11-17 10:17 UTC

**Comment by henrik-lindqvist** [comment] 2020-11-17 10:53
Sorry, couldn't find the posts. I don't want to revive the old threads, why was the previous requests denied?

@xeffyr seem to think it doesn't work for regular apps, but it does since its a "development" permission, and ADB is only required once, to grant it. A few extra bytes of binary XML for a <use-permission> tag in the `AndroidManifest.xml` is hardly "bloated code", Termux already include 8 of them.

Sad, now i'll have to resort to some (shady) logcat reader app instead, or spend hours building Termux.

**Comment by Grimler91** [comment] 2020-11-17 13:01
I am open for re-visiting the decision.

The permission is not strictly required for anything in termux-app/termux-api, and is only useful if the user runs an adb command, it feels a bit shady to add it as it is not clear what it is needed for. User still needs to find out that they need to run the adb command before it is useful.

If we document it clearly then maybe it is okay. 

@xeffyr what do you think?

**Comment by xeffyr** [comment] 2020-11-17 13:21
@Grimler91 As Termux now is updated on F-Droid only, I'm okay with adding permissions.

May add it today as well as update bootstraps and release Termux v0.103.

**Comment by henrik-lindqvist** [comment] 2020-11-17 21:34
@Grimler91 If uninformed, every permission could be seen as "shady". The "development" permissions are more secure since they can only be granted via ADB or as root, and not at run-time like other permissions.

@xeffyr Great! FYI, the Google Play Store has no issue with "development" permissions, my app has included them for years.
