### ISSUE TITLE
Text not visible with samsung's native keyboard after android 10 upgrade. Problem is seen only with termux and not with other terminal emulator apps tested.

### ISSUE THREAD

**Issue by warriorstar123** [termux/termux-app#1493] opened 2020-03-17 09:52 UTC
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:Latest
* Android OS version:10
* Device model:SAMSUNG SM-A750F

After upgrading my samsung A7 to android 10 the native samsung keyboard was not working in termux. Whenever i was typing any specific alphanumeric characters they get written on termux screen but are not visible. Also when hypen is inserted then text cannot be written with hyphen so commands having hyphen in arguments does not works. However i have testes the same samsung keyboard on other terminal emulators app and it works properly however only in termux this issue was seed. Please provide a solution.

**Comment by xeffyr** [comment] 2020-03-17 10:02
Duplicate of https://github.com/termux/termux-app/issues/686.

**Closed by xeffyr** 2020-03-17 10:02 UTC
