### ISSUE TITLE
[Bug]: Termux does not see external drives

### ISSUE THREAD

**Issue by xb3b6** [termux/termux-app#2268] opened 2021-09-12 03:07 UTC
### Problem description

`termux-setup-storage`

I give permission.  Things are good.  Termux sees all internal storage excluding external (flash drive).  The 'storage/external-1/' directory exists, but it is empty.  Assembled correctly too.

[screen TC](https://user-images.githubusercontent.com/80679015/132969962-313c1d39-b5de-4765-a8d2-f61d4ff94b76.jpg) 

```
$ ls storage/external-1/
$
```

the link is created to a directory deep on the flash drive: 'storage/43DD-13FE/Android/data/com.termux/files'.  Expected behavior link to 'storage/43DD-13FE/*'

* Android, DCIM, Download, Movies, Music, Pictures.

I can create links to standard directories by 'ln -s' myself, but I expected them to be created by default.
### Steps to reproduce the behavior.

in description...

### System information

Application version:
0.117
Packages CPU architecture:
arm
Android version:
10 (GSI/root)
Redmi

**Comment by agnostic-apollo** [comment] 2021-09-12 05:03
Duplicate of #20 , #1683, #1886, #1942, #2082 and possibly others.

**Closed by agnostic-apollo** 2021-09-12 05:03 UTC
Labels: bug report
