### ISSUE TITLE
[BUG] Native Panda3D package not work 

### ISSUE THREAD

**Issue by milen-prg** [termux/termux-app#4211] opened 2024-10-17 07:02 UTC
### Problem description

I installed in termux the native package python and panda3d. But when I tried to import it in python, it returns error:
>>> from direct.showbase.ShowBase import ShowBase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'direct'

### Steps to reproduce the behavior.

pkg install python 
pkg install panda3d

python 
>>> from direct.showbase.ShowBase import ShowBase
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'direct'

### What is the expected behavior?

The python module must exist and work.

### System information

* Termux application version:
* Android OS version:
* Device model:
Last termux version. Android 16, Redmi 12

**Comment by twaik** [comment] 2024-10-19 11:16
Duplicate of https://github.com/termux/termux-packages/issues/21869 .

**Closed by twaik** 2024-10-19 11:16 UTC
Labels: bug report
