### ISSUE TITLE
[Feature]: terminal-only or proot support for secondary users

### ISSUE THREAD

**Issue by chriswoope** [termux/termux-app#2730] opened 2022-04-23 17:52 UTC
### Feature description

Currently Termux refuses to work at all in secondary user accounts due to the hardcoded prefix issue.

It seems to me that it could at least skip the whole package installation and just run /system/bin/sh in the terminal.

Also it could support optionally using proot instead on secondary users with the Termux packages, which while not ideal, is certainly better than not working at all.

### Additional information

Yes, most other terminal applications do exactly this.

**Comment by agnostic-apollo** [comment] 2022-04-23 19:36
Duplicate of #2201

**Closed by agnostic-apollo** 2022-04-23 19:36 UTC
