### ISSUE TITLE
Touch keyboard weird behavior on Samsung Note 8

### ISSUE THREAD

**Issue by AndriusWild** [termux/termux-app#706] opened 2018-06-07 14:16 UTC
When I type anything in Termux installed on my Note8 no letters show up until I press . or , or - etc.
Also, very often when "Process completed - press Enter" tapping on Enter does not work.

**Comment by l-jonas** [comment] 2018-06-10 12:52
@AndriusWild Is this a duplicate of https://github.com/termux/termux-app/issues/126 (issues with Samsungs Keyboard "predictive text" feature)?

**Comment by Grimler91** [comment] 2020-01-01 10:03
Duplicate of https://github.com/termux/termux-app/issues/686

**Closed by Grimler91** 2020-01-01 10:03 UTC
