### ISSUE TITLE
[Bug]: termux Frida(15.1.12) empty/missing DT_HASH/DT_GNU_HASH

### ISSUE THREAD

**Issue by djerryz** [termux/termux-app#2521] opened 2022-01-12 09:04 UTC
### Problem description

frida-server , frida-tools cannot be execute

### Steps to reproduce the behavior.

```
apt update && apt upgrade -y
apt install frida-server
apt install frida-tools
```

```
~ $ frida-server --version
CANNOT LINK EXECUTABLE "frida-server": empty/missing DT_HASH/DT_GNU_HASH in "/data/data/com.termux/files/usr/bin/frida-server" (new hash type from the future?)
```
```
~ $ frida-ps --version

Failed to load the Frida native extension: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/com.termux/files/usr/lib/python3.10/site-packages/_frida.so" (new hash type from the future?)
Please ensure that the extension was compiled for Python 3.x.

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/frida-ps", line 10, in <module>
    frida_tools.ps.main()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/frida_tools/ps.py", line 17, in main
    from frida_tools.application import ConsoleApplication
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/frida_tools/application.py", line 23, in <module>
    import frida
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/frida/__init__.py", line 24, in <module>
    raise ex
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/frida/__init__.py", line 7, in <module>
    import _frida
ImportError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/com.termux/files/usr/lib/python3.10/site-packages/_frida.so" (new hash type from the future?)
```

### What is the expected behavior?

show frida version

### System information
```
~ $ termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24 stable main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# sources.list.d/game.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/game-packages-24 games stable
# sources.list.d/science.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux kali 3.18.140-Re4son-r1b1-1 #1 SMP PREEMPT Fri May 1 10:20:30 AEST 2020 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A3000
```

ref: https://github.com/frida/frida/issues/1984, https://github.com/termux/termux-root-packages/issues/284

**Comment by Grimler91** [comment] 2022-01-12 11:21
Duplicate of https://github.com/termux/termux-root-packages/issues/284

**Closed by Grimler91** 2022-01-12 11:21 UTC
Labels: bug report
