### ISSUE TITLE
[bug] 0.65 ver termux set .bash_history file to bad se-linux permission

### ISSUE THREAD

**Issue by Justsoos** [termux/termux-app#861] opened 2018-10-04 04:04 UTC
updated from F-Droid, but bash history has bad behavior, can not use command history or read this file, so 

```
$/system/bin/ls -aZ
-rw------- u0_a373  u0_a373           u:object_r:app_data_file:s0 .bash_history
-rw------- u0_a373  u0_a373           u:object_r:app_data_file:s0:c512,c768 .bashrc
drwx------ u0_a373  u0_a373           u:object_r:app_data_file:s0:c512,c768 .cache
```
I restorecon it by tsu, but after restarting termux everytime, the permission initialized ....

**Comment by Justsoos** [comment] 2018-10-04 04:12
further findings:
the file `/data/data/com.termux/files/home/.bash_history` stores the commands history of `root`, but not the common users', does it exist a user confusion of termux?

**Comment by Grimler91** [comment] 2018-10-04 05:03
You have to restorecon it in a none-interactive shell I believe, otherwise the permissions are changed again when you exit tsu (when it prints your history to the file). 

Moving the file to /sdcard should also work, so you can move it there as root and then move it back as the normal user. 

I would say that this is something that should be fixed in the [tsu repo](github.com/cswl/tsu) rather than termux-app

**Comment by Justsoos** [comment] 2018-10-04 08:13
I have repired the bug by adb shell or by `su` but `tsu`, so odd way: 
I logged on by sshd and then `su` , run restorecon on the file `.bash_history`, then restart termux, the permission was fixed with correct one. 

the old content of `.bash_history` made by root user, now belongs to common user.

**Comment by xeffyr** [comment] 2019-01-25 16:44
Closing since Termux doesn't have any control over SELinux.

**Closed by xeffyr** 2019-01-25 16:44 UTC

**Comment by Justsoos** [comment] 2019-02-02 10:05
Seems a bug of termux, I have to add this line to `.bashrc` now, 
```
tsu -c /system/bin/restorecon -R /data/data/com.termux/files/home/
```
If not doing that, the bash history and command prompt won't work

**Comment by Quasic** [comment] 2019-02-02 22:34
Is this related to termux-packages#3304?

**Comment by xeffyr** [comment] 2019-02-03 00:13
@Quasic Yes, related. But technically, this is not a bug.

**Comment by Justsoos** [comment] 2019-02-05 10:58
@Quasic yeah, this error actually was from an install try of zsh, and then run some su root  commands, then uninstalled zsh, but the error remains

**Comment by Quasic** [comment] 2019-02-20 15:33
Would restorecon help? See #445

**Comment by Quasic** [comment] 2019-02-20 15:43
Also see #341

**Comment by Justsoos** [comment] 2019-06-19 04:13
it is an collision of SElinux  on Termux indeed, I found the config files' SElinux permission will be changed so much so that they can not be run as Non-Root user well after run `tsu -c` or `tsudo` with related programs, 
such as 
```
.sqlite_history
.bash_history
.viminfo
.zshrc
.wget-hsts

```
etc.
