### ISSUE TITLE
EMUI: recent Apps kills Termux completely

### ISSUE THREAD

**Issue by MathiasHabel** [termux/termux-app#1205] opened 2019-08-08 16:07 UTC
**Problem description**
On my Huawei Honor View 10 pressing the bin button oder swiping away the termux window in 'recent apps' will completely close the termux app including all background processes (e. g. sshd)

**Steps to reproduce**
1.) Start Termux, notification will appear
2.) start sshd
3.) long press home button or otherwise call recent apps
4.) swipe Termux window away or press the little bin button in 'recent apps'
5.) Termux is completely killed, notification vanishes, sshd is killed

**Expected behavior**
'Recent apps' should just kill the active Termux View or Activity, not Termux at all. As far as I remember this was the default behaviour not long ago. I am not sure, whether the change happened after upgrading to EMUI 9.1 or after a recent Termux update.

**Additional information**
Toggling the wake lock button on the notification does not change anything.
Not all Terminal apps respond like Termux; the Terminal Emulator of Jack Palewitch (?) cannot be killed via 'recent apps'.

**Comment by xeffyr** [comment] 2019-08-08 16:31
> 'Recent apps' should just kill the active Termux View or Activity, not Termux at all. 

You can't stop "active Termux View" without killing whole Termux.

>  am not sure, whether the change happened after upgrading to EMUI 9.1 or after a recent Termux update.

Go to [F-Droid](https://f-droid.org/en/packages/com.termux/), install previous application version (probably with uninstalling the current one) and verify.

In v0.73 update nothing was changed regarding Termux functionality that may affect described behaviour.

> Not all Terminal apps respond like Termux; the Terminal Emulator of Jack Palewitch (?) cannot be killed via 'recent apps'.

*Terminal Emulator of Jack Palewitch* is targeted at low Android APi versions while Termux is targeted at the latest one. Probably this is the cause, but doesn't mean that we should downgrade targeted API level.

***

Android isn't same on all devices and therefore it is not possible to have expected behaviour everywhere.

Maybe this https://www.digitalcitizen.life/stop-huawei-from-closing-apps-when-you-lock-screen will be useful. Or following one: https://dontkillmyapp.com/huawei

**Closed by xeffyr** 2019-08-08 16:31 UTC

**Comment by MathiasHabel** [comment] 2019-08-08 17:24
Hi xeffyr,

thanks for your quick answer....)

I am not sure, if the low API version of Jacks Terminal Emulator is responsible for its behaviour though.

Tasker for instance does not show the above mentioned behaviour either, that means if I close its last activity or view (or how its called) in 'recent apps', its background services will not be killed. They remain active. Its API Target version ist 28/Androi 9 Pie.

I already disabled EMUIs power management for Termux (and Tasker). I do not have any problems with premature killing, in fact I run some quite lengthy Termux jobs in the night, which completes without problems (and without beeing killed). I just have to refrain from swiping Termux away in recent apps meanwhile.

Mathias

**Comment by xeffyr** [comment] 2019-08-08 18:51
Without understanding logic of how launcher decides to close application nothing can be done from Termux side. It just seems that Termux service is getting killed, which is only possible if application was force-closed.

Check if your launcher has settings related to closing applications.

**Comment by MathiasHabel** [comment] 2019-08-09 06:21
Ok, found it. According to logcat ApplicationManager force-closed the whole package com.termux, if I closed its view (or activity or...) in 'recent apps' I have no idea why. I found though, that a lot of my apps showed this problem (including quite ironically the logcat reader app). I assume, its due to a bug in EMUI 9.1 after the update. I had to un- and then reinstall the affected packages including termux. Due to restic this was very troublefree...:) at least for termux.

Thanks for your help,

Mathias

**Comment by xeffyr** [comment] 2019-08-18 10:44
Seems issue happens on non-emui ROMs. Discussion is continued in https://github.com/termux/termux-app/issues/1219.

I also noticed that if Termux installed as system app, it may not be killed when swiping it out from recents.

> I am not sure, if the low API version of Jacks Terminal Emulator is responsible for its behaviour though.

Regarding this terminal emulator, it is saved from killing by low target api level. If it changed to 28, the Jackpals Terminal Emulator will be killed like Termux.
