### ISSUE TITLE
Using Samsung keyboard, characters don't appear until I hit a whitespace

### ISSUE THREAD

**Issue by amoawad** [termux/termux-app#1469] opened 2020-02-20 07:50 UTC
**Problem description**

When I use Samsung keyboard to type in any commands, characters don't appear until I hit space or enter.

**Steps to reproduce**

- Open the app
- Make sure keyboard in use is Samsung Keyboard
- Type in any command, e.g., `ls`
- Notice that no characters appear on screen
- Hit space
- Notice that `ls` now appears
 
**Expected behavior**

Characters should appear on screen with each keystroke. No need to wait for hitting space.

**Important Note**

Switching to Google Keyboard (Gboard) fixes the problem.

**Additional information**

- Termux version: 0.92
- Termux API version: 0.41
- Device: Samsung Galaxy Tab S6 (SM-T865N)
- OS: Android 9

**Comment by Grimler91** [comment] 2020-02-20 11:03
Problem with some samsung devices. Duplicate of https://github.com/termux/termux-app/issues/686

**Closed by Grimler91** 2020-02-20 11:03 UTC
